/*
La table TA_SOURCE permet de rassembler toutes les données sources provenant d'une source extérieure à la MEL.
*/

-- 1. Création de la table TA_SOURCE
CREATE TABLE G_GEO.TA_SOURCE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    nom_source VARCHAR2(4000),
    description VARCHAR2(4000)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_GEO.TA_SOURCE IS 'Table rassemblant toutes les sources des données utilisées par la MEL.';
COMMENT ON COLUMN G_GEO.TA_SOURCE.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN G_GEO.TA_SOURCE.nom_source IS 'Nom de la source des données.';
COMMENT ON COLUMN G_GEO.TA_SOURCE.description IS 'Description de la source de données..';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_SOURCE 
ADD CONSTRAINT TA_SOURCE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GEO.TA_SOURCE TO G_ADMIN_SIG;