-- création d'un vue permettant l'édition sous elyx
CREATE OR REPLACE VIEW ELYX_DATA.V_POINT_WARNING (OBJECTID, OBJECTID_DUPLICATE, CLA_INU_FK, MATRICULE_AUTEUR_FK, DATE_CREATION, DATE_CLOTURE, VALIDE, EXPLICATION, GEOM) AS
SELECT
  OBJECTID,
	OBJECTID AS OBJECTID_DUPLICATE,
	CLA_INU_FK,
	MATRICULE_AUTEUR_FK,
	DATE_CREATION,
	DATE_CLOTURE,
	VALIDE,
	EXPLICATION,
	GEOM
FROM GEO.TA_POINT_WARNING
WHERE VALIDE = 1

-- création d'un synonyme pour la séquence de la clé primaire
CREATE OR REPLACE SYNONYM ELYX_DATA.V_POINT_WARNING_SEQ FOR GEO.TA_POINT_WARNING_pk_seq;
