-- CREATION DE LA STRUCTURE POUR L'INSERTION DES DONNEES BPE

-- 1. Creation de la table TA_BPE
-- Création de la table TA_BPE qui recense les équipements de la base permanente des equipements.

-- 1.1 Création de la table
CREATE TABLE ta_bpe(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_metadonnee NUMBER(38,0),
	);


-- 1.2 Création des commentaires
COMMENT ON TABLE ta_bpe IS 'Table regroupant les equipements de la Base Permanente des Equipements.';
COMMENT ON COLUMN ta_bpe.objectid IS 'clé primare de la table TA_BPE.';
COMMENT ON COLUMN ta_bpe.fid_metadonnee IS 'Clé étrangère vers la table TA_METADONNEE  pour connaitre la source de la données.';


-- 1.3 Création de la clé primaire
ALTER TABLE ta_bpe
ADD CONSTRAINT ta_bpe_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 1.4 Création de la clé étrangère vers la table ta_metadonnée
ALTER TABLE ta_bpe
ADD CONSTRAINT  "TA_METADONNE_OBJECTID_FK"
FOREIGN KEY ("FID_METADONNEE")
REFERENCES  "G_GEO"."TA_METADONNEE" ("OBJECTID");


-- 1.5 Création des index sur les cléfs étrangères.
CREATE INDEX ta_bpe_fid_metadonnee_IDX ON ta_bpe(fid_metadonnee)
TABLESPACE G_ADT_INDX;


-- 2. Création de la table TA_BPE_GEOM
-- Creation de la table TA_BPE_GEOM qui recense les géométrie que peuvent prendre les equipements de la Base Permanente des Equipements.

-- 2.1 Création de la table
CREATE TABLE ta_bpe_geom(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    geom SDO_GEOMETRY
	);

-- 2.2 Création des commentaires
COMMENT ON TABLE ta_bpe_geom IS 'Table regroupant les positions que peuvent prendre les équipements de la Base Permanente des Equipements';
COMMENT ON COLUMN ta_bpe_geom.objectid IS 'Clé primaire de la table TA_BPE.';
COMMENT ON COLUMN ta_bpe_geom.geom IS 'Position géographique que peuvent prendre les équipements.';

-- 2.3 Création de la clé primaire
ALTER TABLE ta_bpe_geom
ADD CONSTRAINT ta_bpe_geom_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 2.4 Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'ta_bpe_geom',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);

-- 2.5 Création de l'index spatial sur le champ geom
CREATE INDEX ta_bpe_geom_SIDX
ON ta_bpe_geom(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_DATA, work_tablespace=DATA_TEMP');


-- 3. Création de la table TA_RELATION_BPE_GEOM
-- Creation de la table TA_RELATION_BPE_GEOM, table de correspondance entre les BPE et leurs positions géographiques.

-- 3.1 Creation de la table
CREATE TABLE TA_BPE_RELATION_GEOM(
	fid_bpe NUMBER(38,0),
	fid_bpe_geom NUMBER(38,0)
	);

-- 3.2 Création des commentaires des colonnes
COMMENT ON TABLE TA_BPE_RELATION_GEOM IS 'Table de liaison entre les équipements et leurs géométries';
COMMENT ON COLUMN TA_BPE_RELATION_GEOM.fid_bpe IS 'Clé étrangère vers la table TA_BPE. Composante de la clé primaire.';
COMMENT ON COLUMN TA_BPE_RELATION_GEOM.fid_bpe_geom IS 'Clé étrangère vers la table TA_BPE_GEOM. Composante de la clé primaire.';

-- 3.3 Ajout de la clé primaire
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT ta_bpe_relation_geom_PK 
PRIMARY KEY(fid_bpe,fid_bpe_geom)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 3.4 Création des clés étrangères

-- 3.4.1 vers la table ta_bpe
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT ta_bpe_relation_geom_bpe_fk
FOREIGN KEY (fid_bpe)
REFERENCES ta_bpe(objectid);

-- 3.4.2 vers la table ta_bpe_geom
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT ta_bpe_relation_geom_bpe_geom_fk 
FOREIGN KEY (fid_bpe_geom)
REFERENCES ta_bpe_geom(objectid);

-- 3.5 Création des index sur les cléfs étrangères.
CREATE INDEX ta_bpe_relation_geom_fid_bpe_IDX ON ta_bpe_relation_geom(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_relation_geom_fid_bpe_geom_IDX ON ta_bpe_relation_geom(fid_bpe_geom)
    TABLESPACE G_ADT_INDX;


-- 4. Création de la table TA_BPE_CARACTERISTIQUE NOMBRE
-- Creation de la table TA_BPE_CARACTERISTIQUE_NOMBRE pour faire la liaison entre un equipement de la BPE vers ses caractéristiques numerique.

-- 4.1 Création de la table
CREATE TABLE ta_bpe_caracteristique_nombre(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_bpe NUMBER(38,0),
    fid_libelle NUMBER(38,0),
    nombre NUMBER(38,0)
	);

-- 4.2 Création des commentaires
COMMENT ON TABLE ta_bpe_caracteristique_nombre IS 'Table de relation entre les equipements et les libelles ou l''information et sous la forme d''un nombre: exemple NB_SALLES: 4. L''équipement dispose de 4 salles';
COMMENT ON COLUMN ta_bpe_caracteristique_nombre.objectid IS 'clé primaire de la table TA_BPE_CARACTERISTIQUE_NOMBRE.';
COMMENT ON COLUMN ta_bpe_caracteristique_nombre.fid_bpe IS 'clé étrangère vers la table TA_BPE';
COMMENT ON COLUMN ta_bpe_caracteristique_nombre.fid_libelle IS 'clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l''équipement';
COMMENT ON COLUMN ta_bpe_caracteristique_nombre.nombre IS 'nombre de salles de théatre par cinéma, théatre ou nombre d''aires de pratique d''un même type au sein de l''équipement';

-- 4.3 Création de la clé primaire
ALTER TABLE ta_bpe_caracteristique_nombre
ADD CONSTRAINT ta_bpe_caracteristique_nombre_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4.5 clé étrangère

-- 4.5.1 clé étrangère vers la table TA_BPE
ALTER TABLE ta_bpe_caracteristique_nombre
ADD CONSTRAINT  "TA_BPE_CARACTERISTIQUE_NOMBRE_TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES  "G_GEO"."TA_BPE" ("OBJECTID");

-- 4.5.2 clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l'equipement
ALTER TABLE ta_bpe_caracteristique_nombre
ADD CONSTRAINT  "TA_BPE_CARACTERISTIQUE_NOMBRE_TA_LIBELLE_OBJECTID_FK"
FOREIGN KEY ("FID_LIBELLE")
REFERENCES  "G_GEO"."TA_LIBELLE" ("OBJECTID");

-- 4.5 Création des index sur les cléfs étrangères.

CREATE INDEX ta_bpe_caracteristique_nombre_fid_bpe_IDX ON ta_bpe_caracteristique_nombre(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_caracteristique_nombre_fid_libelle_IDX ON ta_bpe_caracteristique_nombre(fid_libelle)
    TABLESPACE G_ADT_INDX;


-- 5 Création de la table TA_BPE_CARACTERISTIQUE
-- Creation de la table TA_BPE_CARACTERISTIQUE pour faire la liaison entre un equipement de la BPE vers ses caractéristique.

-- 5.1 Création de la table
CREATE TABLE ta_bpe_caracteristique(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_bpe NUMBER(38,0),
    fid_libelle_fils NUMBER(38,0),
    fid_libelle_parent NUMBER(38,0)
	);

-- 5.2 Création des commentaires
COMMENT ON TABLE ta_bpe_caracteristique IS 'Table de relation entre les equipements et les libelles pour connaitre les caractéristiques des équipements';
COMMENT ON COLUMN ta_bpe_caracteristique.objectid IS 'clé primaire de la table TA_BPE_CARACTERISTIQUE.';
COMMENT ON COLUMN ta_bpe_caracteristique.fid_bpe IS 'clé étrangère vers la table TA_BPE';
COMMENT ON COLUMN ta_bpe_caracteristique.fid_libelle_fils IS 'clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l''equipement';
COMMENT ON COLUMN ta_bpe_caracteristique.fid_libelle_parent IS 'clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique parent de l''equipement';

-- 5.3 Création de la clé primaire
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT ta_bpe_caracteristique_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 5.4 clé étrangère
-- 5.4.1 clé étrangère vers la table TA_BPE
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT "TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES "G_GEO"."TA_BPE" ("OBJECTID");

-- 5.4.2 clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l'equipement
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT "TA_LIBELLE_FILS_OBJECTID_FK"
FOREIGN KEY ("FID_LIBELLE_FILS")
REFERENCES "G_GEO"."TA_LIBELLE" ("OBJECTID");

-- 5.4.3 clé étrangère vers la table TA_LIBELLE pour connaitre le libelle parent de la caractéristique de l'equipement
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT  "TA_LIBELLE_PARENT_OBJECTID_FK"
FOREIGN KEY ("FID_LIBELLE_PARENT")
REFERENCES "G_GEO"."TA_LIBELLE" ("OBJECTID");

-- 5.5 Création des index sur les clés étrangères.

CREATE INDEX ta_bpe_caracteristique_fid_bpe_IDX ON ta_bpe_caracteristique(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_caracteristique_fid_libelle_fils_IDX ON ta_bpe_caracteristique(fid_libelle_fils)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_caracteristique_fid_libelle_parent_IDX ON ta_bpe_caracteristique(fid_libelle_parent)
    TABLESPACE G_ADT_INDX;


-- 6 Création de la table TA_BPE_RELATION_CODE
-- Création de la table TA_BPE_RELATION_CODE qui sert à faire la correspondance entre les equipements et leurs IRIS ou commune d'implantation.

-- 6.1 Création de la table
CREATE TABLE ta_bpe_relation_code(
  fid_bpe NUMBER(38,0), 
  fid_code NUMBER(38,0)
  );

-- 6.2 Création des commentaires
COMMENT ON TABLE ta_bpe_relation_code  IS 'Table indiquant les correspondances entre les libelles et leurs communes ou iris d''implantation';
COMMENT ON COLUMN ta_bpe_relation_code.fid_bpe IS 'Clé etrangere vers la table TA_BPE. Composante de la clé primaire';
COMMENT ON COLUMN ta_bpe_relation_code.fid_code IS 'Clé etrangere vers la table TA_CODE pour connaitre la commune ou IRIS d''implantation';

-- 6.3 Création de la clef primaire
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT ta_bpe_relation_code_PK 
PRIMARY KEY(fid_bpe,fid_code)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 6.4 Création de la séquence d'auto-incrémentation de la clef primaire

-- 6.4.1 Clé étrangère vers la table TA_LIBELLE pour connaitre le libelle
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT  "TA_BPE_RELATION_CODE_FID_BPE_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES "TA_BPE" ("OBJECTID");

-- 6.4.2 Clé étrangère vers la table TA_BPE_LIBELLE_COURT pour connaitre le libelle court
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT "TA_BPE_RELATION_CODE_FID_CODE_FK"
FOREIGN KEY ("FID_CODE")
REFERENCES "TA_CODE" ("OBJECTID");


-- 6.5 Creation des index

CREATE INDEX ta_bpe_relation_code_fid_bpe_IDX ON ta_bpe_relation_code(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_relation_code_fid_code_IDX ON ta_bpe_relation_code(fid_code)
    TABLESPACE G_ADT_INDX;