-- Requête SQL necessaire à la création de la structure utilisée pour insérer les donnnées de la base BPE

-- 1. Création de la table TA_BPE_GEOM
-- Creation de la table TA_BPE_GEOM qui recense les géométries que peuvent prendre les equipements de la Base Permanente des Equipements.

-- 1.1 Création de la table
CREATE TABLE ta_bpe_geom(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    geom SDO_GEOMETRY
	);


-- 1.2 Création des commentaires
COMMENT ON TABLE ta_bpe_geom IS 'Table regroupant les positions que peuvent prendre les équipements de la Base Permanente des Equipements';
COMMENT ON COLUMN ta_bpe_geom.objectid IS 'Clé primaire de la table TA_BPE.';
COMMENT ON COLUMN ta_bpe_geom.geom IS 'Position géographique que peuvent prendre les équipements.';


-- 1.3 Création de la clé primaire
ALTER TABLE ta_bpe_geom
ADD CONSTRAINT ta_bpe_geom_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 1.4 Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'ta_bpe_geom',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);


-- 1.5 Création de l'index spatial sur le champ geom
CREATE INDEX ta_bpe_geom_SIDX
ON ta_bpe_geom(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 2. Creation de la table TA_BPE
-- Création de la table TA_BPE qui recense les équipements de la base permanente des equipements.

-- 2.1 Création de la table
CREATE TABLE ta_bpe(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_metadonnee NUMBER(38,0)
    );


-- 2.2 Création des commentaires
COMMENT ON TABLE ta_bpe IS 'Table regroupant les equipements de la Base Permanente des Equipements.';
COMMENT ON COLUMN ta_bpe.objectid IS 'Clé primaire de la table TA_BPE.';
COMMENT ON COLUMN ta_bpe.fid_metadonnee IS 'Clé étrangère vers la table TA_METADONNEE  pour connaitre la source de la données.';


-- 2.3 Création de la clé primaire
ALTER TABLE ta_bpe
ADD CONSTRAINT ta_bpe_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 2.4 Création des clés étrangères

-- 2.4.1 Création de la clé étrangère vers la table ta_metadonnée
ALTER TABLE ta_bpe
ADD CONSTRAINT  "TA_METADONNE_OBJECTID_FK"
FOREIGN KEY ("FID_METADONNEE")
REFERENCES  "TA_METADONNEE" ("OBJECTID");


-- 2.5 Création des index sur les cléfs étrangères.
CREATE INDEX ta_bpe_fid_metadonnee_IDX ON ta_bpe(fid_metadonnee)
TABLESPACE G_ADT_INDX;


-- 3. Création de la table TA_RELATION_BPE_GEOM
-- Creation de la table TA_RELATION_BPE_GEOM, table de correspondance entre les BPE et leurs positions géographiques.

-- 3.1 Creation de la table
CREATE TABLE TA_BPE_RELATION_GEOM(
	fid_bpe NUMBER(38,0),
	fid_bpe_geom NUMBER(38,0)
	);

-- 3.2 Création des commentaires des colonnes
COMMENT ON TABLE TA_BPE_RELATION_GEOM IS 'Table de liaison entre les équipements et leurs géométries';
COMMENT ON COLUMN TA_BPE_RELATION_GEOM.fid_bpe IS 'Clé étrangère vers la table TA_BPE. Composante de la clé primaire.';
COMMENT ON COLUMN TA_BPE_RELATION_GEOM.fid_bpe_geom IS 'Clé étrangère vers la table TA_BPE_GEOM. Composante de la clé primaire.';

-- 3.3 Ajout de la clé primaire
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT ta_bpe_relation_geom_PK 
PRIMARY KEY(fid_bpe,fid_bpe_geom)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 3.4 Création des clés étrangères

-- 3.4.1 vers la table ta_bpe
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT "TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES "TA_BPE"("OBJECTID");

-- 3.4.2 vers la table ta_bpe_geom
ALTER TABLE ta_bpe_relation_geom
ADD CONSTRAINT "TA_BPE_GEOM_OBJECTID_FK"
FOREIGN KEY ("FID_GEOM")
REFERENCES "TA_BPE_GEOM"("OBJECTID");


-- 3.5 Création des index sur les cléfs étrangères.
CREATE INDEX ta_bpe_relation_geom_fid_bpe_IDX ON ta_bpe_relation_geom(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_relation_geom_fid_bpe_geom_IDX ON ta_bpe_relation_geom(fid_bpe_geom)
    TABLESPACE G_ADT_INDX;


-- 4. Création de la table TA_BPE_CARACTERISTIQUE QUANTITATIVE
-- Creation de la table TA_BPE_CARACTERISTIQUE_QUANTITATIVE pour faire la liaison entre un equipement de la BPE vers ses caractéristiques numerique.

-- 4.1 Création de la table
CREATE TABLE ta_bpe_caracteristique_quantitative(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_bpe NUMBER(38,0),
    fid_libelle NUMBER(38,0),
    nombre NUMBER(38,0)
	);


-- 4.2 Création des commentaires
COMMENT ON TABLE ta_bpe_caracteristique_quantitative IS 'Table de relation entre les equipements et les libelles ou l''information et sous la forme d''un nombre: exemple NB_SALLES: 4. L''équipement dispose de 4 salles';
COMMENT ON COLUMN ta_bpe_caracteristique_quantitative.objectid IS 'Clé primaire de la table ta_bpe_caracteristique_quantitative.';
COMMENT ON COLUMN ta_bpe_caracteristique_quantitative.fid_bpe IS 'Clé étrangère vers la table TA_BPE';
COMMENT ON COLUMN ta_bpe_caracteristique_quantitative.fid_libelle IS 'Clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l''équipement';
COMMENT ON COLUMN ta_bpe_caracteristique_quantitative.nombre IS 'Nombre de salles de théatre par cinéma, théatre ou nombre d''aires de pratique d''un même type au sein de l''équipement';


-- 4.3 Création de la clé primaire
ALTER TABLE ta_bpe_caracteristique_quantitative
ADD CONSTRAINT ta_bpe_caracteristique_quantitative_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 4.4 clé étrangère

-- 4.4.1 clé étrangère vers la table TA_BPE
ALTER TABLE ta_bpe_caracteristique_quantitative
ADD CONSTRAINT  "TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES  "TA_BPE" ("OBJECTID");

-- 4.4.2 clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l'equipement
ALTER TABLE ta_bpe_caracteristique_quantitative
ADD CONSTRAINT  "TA_LIBELLE_OBJECTID_FK"
FOREIGN KEY ("FID_LIBELLE")
REFERENCES  "TA_LIBELLE" ("OBJECTID");


-- 4.5 Création des index sur les cléfs étrangères.

CREATE INDEX ta_bpe_caracteristique_quantitative_fid_bpe_IDX ON ta_bpe_caracteristique_quantitative(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_caracteristique_quantitative_fid_libelle_IDX ON ta_bpe_caracteristique_quantitative(fid_libelle)
    TABLESPACE G_ADT_INDX;


-- 5 Création de la table TA_BPE_CARACTERISTIQUE
-- Creation de la table TA_BPE_CARACTERISTIQUE pour faire la liaison entre un equipement de la BPE vers ses caractéristiques.

-- 5.1 Création de la table
CREATE TABLE ta_bpe_caracteristique(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_bpe NUMBER(38,0),
    fid_libelle NUMBER(38,0)
	);


-- 5.2 Création des commentaires
COMMENT ON TABLE ta_bpe_caracteristique IS 'Table de relation entre les equipements et les libelles pour connaitre les caractéristiques des équipements';
COMMENT ON COLUMN ta_bpe_caracteristique.objectid IS 'Clé primaire de la table TA_BPE_CARACTERISTIQUE.';
COMMENT ON COLUMN ta_bpe_caracteristique.fid_bpe IS 'Clé étrangère vers la table TA_BPE';
COMMENT ON COLUMN ta_bpe_caracteristique.fid_libelle IS 'Clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l''equipement';


-- 5.3 Création de la clé primaire
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT ta_bpe_caracteristique_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 5.4 clé étrangère

-- 5.4.1 clé étrangère vers la table TA_BPE
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT "TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES "TA_BPE" ("OBJECTID");

-- 5.4.2 clé étrangère vers la table TA_LIBELLE pour connaitre la caractéristique de l'equipement
ALTER TABLE ta_bpe_caracteristique
ADD CONSTRAINT "TA_LIBELLE_OBJECTID_FK"
FOREIGN KEY ("FID_LIBELLE")
REFERENCES "TA_LIBELLE" ("OBJECTID");


-- 5.5 Création des index sur les clés étrangères.

CREATE INDEX ta_bpe_caracteristique_fid_bpe_IDX ON ta_bpe_caracteristique(fid_bpe)
    TABLESPACE G_ADT_INDX;

CREATE INDEX ta_bpe_caracteristique_fid_libelle_fils_IDX ON ta_bpe_caracteristique(fid_libelle)
    TABLESPACE G_ADT_INDX;


-- 6. Creation de la table TA_BPE_RELATION_CODE
-- Création de la table TA_BPE_RELATION_CODE, table de relation entre les équipements et les codes insee des communes ainsi que les codes IRIS d'implantation.

-- 6.1 Création de la table
CREATE TABLE ta_bpe_relation_code(
    fid_bpe NUMBER(38,0),
    fid_code NUMBER(38,0)
    );


-- 6.2 Création des commentaires
COMMENT ON TABLE ta_bpe_relation_code IS 'Table regroupant les equipements de la Base Permanente des Equipements et leurs code d''INSEE et IRIS.';
COMMENT ON COLUMN ta_bpe_relation_code.fid_bpe IS 'Clé primaire de la table TA_BPE pour connaitre l''identifiant de l''équipement BPE.';
COMMENT ON COLUMN ta_bpe_relation_code.fid_code IS 'Clé étrangère vers la table TA_CODE pour connaitre les codes insee des communes ainsi que les codes IRIS des zones IRIS d''implantation de l''équipement';


-- 6.3 Création de la clé primaire.
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT ta_bpe_relation_code_PK 
PRIMARY KEY("FID_BPE","FID_CODE")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 6.4. Création des clés étrangères
-- 6.4.1. Création de la clé étrangère vers la table ta_libelle pour connaitre le BPE concerné par le code.
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT  "TA_BPE_OBJECTID_FK"
FOREIGN KEY ("FID_BPE")
REFERENCES  "TA_BPE" ("OBJECTID");

-- 6.4.2. Création de la clé étrangère vers la table ta_libelle pour connaitre le code de la commune d'implantation de l'équipement.
ALTER TABLE ta_bpe_relation_code
ADD CONSTRAINT  "TA_CODE_OBJECTID_FK"
FOREIGN KEY ("FID_CODE")
REFERENCES  "TA_CODE" ("OBJECTID");