--------------------------------------------------------
-- CREATION_V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE --
--------------------------------------------------------

-- 1. creation de la vue:
CREATE OR REPLACE FORCE EDITIONABLE VIEW G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE
    (
    IDENTIFIANT,
    IDENTIFIANT_ELEMENT,
    SOURCE,
    NUMERO_DOSSIER,
    IDENTIFIANT_TYPE,
    CODE_TYPE,
    LIBELLE_TYPE,
    COORD_Z,
    AGENT_CREATION,
    DATE_CREATION,
    AGENT_MODIFICATION,
    DATE_MODIFICATION,
    GEOM,
CONSTRAINT "V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE_PK" PRIMARY KEY ("IDENTIFIANT") DISABLE) AS
WITH CTE_1 AS
    (
    SELECT 
        a.objectid AS IDENTIFIANT_ELEMENT,
        'G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION' AS SOURCE,
        a.FID_NUMERO_DOSSIER,
        b.OBJECTID AS IDENTIFIANT_TYPE,
        b.LIBELLE_COURT AS CODE_TYPE,
        b.LIBELLE_LONG AS LIBELLE_TYPE,
        CAST(a.GEOM.sdo_point.z AS NUMBER(9,2)) AS COORD_Z,
        c.OBJECTID AS AGENT_CREATION,
        a.DATE_CREATION,
        d.PNOM AS AGENT_MODIFICATION,
        a.DATE_MODIFICATION,
        SDO_CS.MAKE_2D(a.geom, 2154) AS GEOM
    FROM
        G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION a
        INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.objectid
        INNER JOIN G_GESTIONGEO.TA_GG_AGENT c ON c.OBJECTID = a.FID_PNOM_CREATION
        LEFT JOIN G_GESTIONGEO.TA_GG_AGENT d ON d.OBJECTID = a.FID_PNOM_MODIFICATION
        ),
CTE_2 AS
    (
    SELECT 
        a.objectid AS IDENTIFIANT_ELEMENT,
        'G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION' AS SOURCE,
        a.FID_NUMERO_DOSSIER,
        b.OBJECTID AS IDENTIFIANT_TYPE,
        b.LIBELLE_COURT AS CODE_TYPE,
        b.LIBELLE_LONG AS LIBELLE_TYPE,
        CAST(t.z AS NUMBER(9,2)) AS COORD_Z,
        c.OBJECTID AS AGENT_CREATION,
        a.DATE_CREATION,
        d.PNOM AS AGENT_MODIFICATION,
        a.DATE_MODIFICATION,
        SDO_GEOMETRY(2001, 2154,
            SDO_POINT_TYPE(t.X,t.Y,NULL),
            NULL, NULL) AS GEOM
    FROM
        G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION a
        INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.objectid
        INNER JOIN G_GESTIONGEO.TA_GG_AGENT c ON c.OBJECTID = a.FID_PNOM_CREATION
        LEFT JOIN G_GESTIONGEO.TA_GG_AGENT d ON d.OBJECTID = a.FID_PNOM_MODIFICATION,
    TABLE
        (SDO_UTIL.GETVERTICES(a.GEOM)) t
    ),
CTE_3 AS
    (
    SELECT
        CTE_1.*
    FROM
        CTE_1
    UNION ALL
    SELECT
        CTE_2.*
    FROM
        CTE_2
    )
    SELECT
        ROWNUM as IDENTIFIANT,
        CTE_3.*
    FROM
        CTE_3
    ;


-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE  IS 'Vue permettant d''analyser les coordonnées X,Y et Z des sommets des lignes contenus dans les tables : TA_RTGE_POINT_FIN et TA_RTGE_LINEAIRE_FIN.';

COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.IDENTIFIANT IS 'Clé primaire de la vue.';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.IDENTIFIANT_ELEMENT IS 'Identifiant de l''entité d''origine présente dans les tables TA_RTGE_POINT_FIN et TA_RTGE_LINEAIRE_FIN.';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.SOURCE IS 'Source de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.NUMERO_DOSSIER IS 'Numéro de dossier de l''objet.';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.COORD_Z IS 'Coordonnée Z du point.';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.AGENT_CREATION IS 'Agent qui a créé l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.DATE_CREATION IS 'Date de création de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.AGENT_MODIFICATION IS 'Agent qui est intervenu sur l''objet en dernier';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE.GEOM IS 'Géométrie de l''objet - point.';

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE';

-- 3. Métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)),
    2154
);

-- 4. DROIT
GRANT SELECT ON G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE TO G_GESTIONGEO_MAJ;

/
