-- Creation de la vue V_DOSSIER afin de restituer les informations des dossiers

-- 1. Creation de la vue.
CREATE OR REPLACE FORCE VIEW G_GESTIONGEO.V_GG_DOSSIER (NUMERO_DOSSIER, TYPE_DE_DOSSIER, AVANCEMENT, DATE_SAISIE, DATE_MODIFICATION, DATE_CLOTURE, DATE_DEBUT_LEVE, DATE_FIN_LEVE, DATE_DEBUT_TRAVAUX, DATE_FIN_TRAVAUX, DATE_COMMANDE_DOSSIER, MAITRE_OUVRAGE, RESPONSABLE_LEVE, ENTREPRISE_TRAVAUX, REMARQUE_GEOMETRE, REMARQUE_PHOTO_INTERPRETE, GEOM,
CONSTRAINT "V_GG_DOSSIER_PK" PRIMARY KEY ("NUMERO_DOSSIER") DISABLE) 
AS
SELECT
	a.OBJECTID AS NUMERO_DOSSIER,
	b.LIBELLE AS TYPE_DE_DOSSIER,
	c.LIBELLE_COURT AS AVANCEMENT,
	a.DATE_SAISIE AS DATE_SAISIE,
	a.DATE_MODIFICATION AS DATE_MODIFICATION,
	a.DATE_CLOTURE AS DATE_CLOTURE,
	a.DATE_DEBUT_LEVE AS DATE_DEBUT_LEVE,
	a.DATE_FIN_LEVE AS DATE_FIN_LEVE,
	a.DATE_DEBUT_TRAVAUX AS DATE_DEBUT_TRAVAUX,
	a.DATE_FIN_TRAVAUX AS DATE_FIN_TRAVAUX,
	a.DATE_COMMANDE_DOSSIER AS DATE_COMMANDE_DOSSIER,
	a.MAITRE_OUVRAGE AS MAITRE_OUVRAGE,
	a.RESPONSABLE_LEVE AS RESPONSABLE_LEVE,
	a.ENTREPRISE_TRAVAUX AS ENTREPRISE_TRAVAUX,
	a.REMARQUE_GEOMETRE AS REMARQUE_GEOMETRE,
	a.REMARQUE_PHOTO_INTERPRETE AS REMARQUE_PHOTO_INTERPRETE,
	d.GEOM AS GEOM
FROM
	G_GESTIONGEO.TA_GG_DOSSIER a
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE b ON b.objectid = a.fid_famille
	INNER JOIN G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT c ON c.objectid = a.fid_etat_avancement
	INNER JOIN G_GESTIONGEO.TA_GG_GEO d ON d.objectid = a.fid_perimetre
;


-- 2. Commentaire de la vue.
COMMENT ON TABLE G_GESTIONGEO.V_GG_DOSSIER IS 'Vue qui présente les dossiers de l''appplication gestiongeo avec leurs informations. Les dossiers gestiongeo contiennent les périmètres des surfaces sur lesquelles les éléments urbains ont été relevés par des géomètres';


-- 3. Creation des commentaires des colonnes.
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.NUMERO_DOSSIER IS 'Numéro du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.TYPE_DE_DOSSIER IS 'Type de dossier: Investigation Complémentaire (IC) ou RECOLEMENT)';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.AVANCEMENT IS 'Etat d''avancement du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_SAISIE IS 'Date de création du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_MODIFICATION IS 'Date de modification du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_CLOTURE IS 'Date de cloture du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_DEBUT_LEVE IS 'Date de début du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_FIN_LEVE IS 'Date de fin du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_DEBUT_TRAVAUX IS 'Date de début des travaux';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_FIN_TRAVAUX IS 'Date de fin des travaux';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.DATE_COMMANDE_DOSSIER IS 'Date de commande du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.MAITRE_OUVRAGE IS 'Nom du maître d''ouvrage';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.RESPONSABLE_LEVE IS 'Nom de l''entreprise responsable du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.ENTREPRISE_TRAVAUX IS 'Entreprise ayant effectué les travaux de levé (si l''entreprise responsable du levé utilise un sous-traitant, alors c''est le nom du sous-traitant qu''il faut mettre ici).';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.REMARQUE_GEOMETRE IS 'Précision apportée au dossier par le géomètre telle que sa surface et l''origine de la donnée.';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.REMARQUE_PHOTO_INTERPRETE IS 'Remarque du photo-interprète lors de la création du dossier permettant de préciser la raison de sa création, sa délimitation ou le type de bâtiment/voirie qui a été construit/détruit.';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER.GEOM IS 'Géométrie du dossier - type multipolygone';


-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'V_GG_DOSSIER',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- 5. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER TO G_GESTIONGEO_MAJ;

/