/*
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_OCSMEL_CONSULTATION';
DROP VIEW G_GESTIONGEO.V_OCSMEL_CONSULTATION;
*/
----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la V_OCSMEL_CONSULTATION-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue pour afficher les objets contenus dans la table G_GESTIONGEO.TA_OCSMEL.
--1. Creation
CREATE OR REPLACE FORCE EDITIONABLE VIEW G_GESTIONGEO.V_OCSMEL_CONSULTATION
    (
    IDENTIFIANT_OBJET,
    IDENTIFIANT_TYPE,
    CODE_TYPE,
    LIBELLE_TYPE,
    DATE_MAJ,
    SURFACE,
    GEOM,
CONSTRAINT "V_OCSMEL_CONSULTATION_IDENTIFIANT_OBJET_PK" PRIMARY KEY ("IDENTIFIANT_OBJET") DISABLE) AS 
SELECT
    a.OBJECTID AS IDENTIFIANT_OBJET,
    a.FID_IDENTIFIANT_TYPE AS IDENTIFIANT_TYPE,
    b.LIBELLE_COURT  AS CODE_TYPE,
    b.LIBELLE_LONG AS LIBELLE_TYPE,
    COALESCE(a.DATE_MODIFICATION, a.DATE_CREATION) AS DATE_MAJ,
    SURFACE,
    a.GEOM
FROM
    G_GESTIONGEO.TA_OCSMEL a
    INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.OBJECTID
;


-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.V_OCSMEL_CONSULTATION IS 'Vue qui présente les objets contenus dans la table G_GESTIONGEO.TA_OCSMEL';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique - Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.DATE_MAJ IS 'Date de deniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.SURFACE IS 'Surface de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.V_OCSMEL_CONSULTATION.GEOM IS 'Geometrie de l''objet - type point';


-- 3. Création de la clé primaire
/*
ALTER MATERIALIZED VIEW G_GESTIONGEO.VM_OCSMEL
ADD CONSTRAINT VM_OCSMEL_IDENTIFIANT_OBJET_PK 
PRIMARY KEY (IDENTIFIANT_OBJET);
*/

-- 4. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'V_OCSMEL_CONSULTATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005)),
    2154
);
COMMIT;


-- 5. Création de l'index spatial sur le champ geom
/*
CREATE INDEX G_GESTIONGEO.VM_OCSMEL_SIDX
ON G_GESTIONGEO.VM_OCSMEL(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');
*/


-- 6. INDEX
-- 6.1. Sur le champ IDENTIFIANT_TYPE.
/*
CREATE INDEX V_OCSMEL_CONSULTATION_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.V_OCSMEL_CONSULTATION(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.2. Sur le champ CODE_TYPE.
CREATE INDEX V_OCSMEL_CONSULTATION_CODE_TYPE_IDX ON G_GESTIONGEO.V_OCSMEL_CONSULTATION(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX V_OCSMEL_CONSULTATION_LIBELLE_TYPE_IDX ON G_GESTIONGEO.V_OCSMEL_CONSULTATION(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;
*/

-- 7. Droits
GRANT SELECT ON G_GESTIONGEO.V_OCSMEL_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.V_OCSMEL_CONSULTATION TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_OCSMEL_CONSULTATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.V_OCSMEL_CONSULTATION TO ISOGEO_LEC;