-- Creation de la vue V_GG_DOSSIER_REPERTOIRE afin de restituer les informations des dossiers

-- 1. Creation de la vue.
CREATE OR REPLACE FORCE VIEW G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE (
	NUMERO_DOSSIER, 
	TYPE_DE_DOSSIER, 
	AVANCEMENT, 
	PNOM_CREATION, 
	DATE_CREATION, 
	PNOM_MODIFICATION, 
	DATE_MODIFICATION, 
	DATE_DEBUT_LEVE, 
	DATE_FIN_LEVE, 
	DATE_DEBUT_TRAVAUX, 
	DATE_FIN_TRAVAUX, 
	DATE_COMMANDE_DOSSIER, 
	DATE_CLOTURE, 
	MAITRE_OUVRAGE, 
	RESPONSABLE_LEVE, 
	ENTREPRISE_TRAVAUX, 
	REMARQUE_GEOMETRE, 
	REMARQUE_PHOTO_INTERPRETE, 
	REPERTOIRE, 
	NOM_FICHIER, 
	GEOM,
CONSTRAINT "V_GG_DOSSIER_REPERTOIRE_PK" PRIMARY KEY ("NUMERO_DOSSIER") DISABLE) 
AS
WITH CTE AS
	(
		SELECT
			a.FID_DOSSIER AS NUMERO_DOSSIER,
			a.FICHIER AS FICHIER
		FROM
			G_GESTIONGEO.TA_GG_FICHIER a
		WHERE
			a.INTEGRATION = 1
	)
SELECT
	a.OBJECTID AS NUMERO_DOSSIER,
	b.LIBELLE AS TYPE_DE_DOSSIER,
	c.LIBELLE_COURT AS AVANCEMENT,
	e.PNOM AS PNOM_CREATION,
	a.DATE_SAISIE AS DATE_CREATION,
	f.PNOM AS PNOM_MODIFICATION,
	a.DATE_MODIFICATION AS DATE_MODIFICATION,
	a.DATE_DEBUT_LEVE AS DATE_DEBUT_LEVE,
	a.DATE_FIN_LEVE AS DATE_FIN_LEVE,
	a.DATE_DEBUT_TRAVAUX AS DATE_DEBUT_TRAVAUX,
	a.DATE_FIN_TRAVAUX AS DATE_FIN_TRAVAUX,
	a.DATE_COMMANDE_DOSSIER AS DATE_COMMANDE_DOSSIER,
	a.DATE_CLOTURE AS DATE_CLOTURE,
	a.MAITRE_OUVRAGE AS MAITRE_OUVRAGE,
	a.RESPONSABLE_LEVE AS RESPONSABLE_LEVE,
	a.ENTREPRISE_TRAVAUX AS ENTREPRISE_TRAVAUX,
	a.REMARQUE_GEOMETRE AS REMARQUE_GEOMETRE,
	a.REMARQUE_PHOTO_INTERPRETE AS REMARQUE_PHOTO_INTERPRETE,
    g.REPERTOIRE || a.objectid AS REPERTOIRE,
    COALESCE(cte.FICHIER,'Fichier intégré non determiné') AS NOM_FICHIER,
	d.GEOM AS GEOM
FROM
	G_GESTIONGEO.TA_GG_DOSSIER a
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE b ON b.objectid = a.fid_famille
	INNER JOIN G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT c ON c.objectid = a.fid_etat_avancement
	INNER JOIN G_GESTIONGEO.TA_GG_GEO d ON d.objectid = a.fid_perimetre
	INNER JOIN G_GESTIONGEO.TA_GG_AGENT e ON e.objectid = a.fid_pnom_creation
	LEFT JOIN G_GESTIONGEO.TA_GG_AGENT f ON f.objectid = a.fid_pnom_modification
    LEFT JOIN CTE cte ON cte.numero_dossier = a.objectid,
    G_GESTIONGEO.TA_GG_REPERTOIRE g
WHERE
    g.objectid = 2
;


-- 2. Commentaire de la vue.
COMMENT ON TABLE G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE IS 'Vue qui présente les dossiers de l''appplication gestiongeo avec leurs informations. Les dossiers gestiongeo contiennent les périmètres des surfaces sur lesquelles les éléments urbains ont été relevés par des géomètres. Cette vue présente également le chemin vers le repertoires des fichiers relevés du dossier';

-- 3. Creation des commentaires des colonnes.
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.NUMERO_DOSSIER IS 'Numéro du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.TYPE_DE_DOSSIER IS 'Type de dossier: Investigation Complémentaire (IC) ou RECOLEMENT)';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.AVANCEMENT IS 'Etat d''avancement du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.PNOM_CREATION IS 'Agent qui a créé le dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_CREATION IS 'Date de création du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.PNOM_MODIFICATION IS 'Agent qui a modifié le dossier pour la dernière fois';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_MODIFICATION IS 'Date de modification du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_DEBUT_LEVE IS 'Date de début du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_FIN_LEVE IS 'Date de fin du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_DEBUT_TRAVAUX IS 'Date de début des travaux';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_FIN_TRAVAUX IS 'Date de fin des travaux';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_COMMANDE_DOSSIER IS 'Date de commande du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.DATE_CLOTURE IS 'Date de clôture du dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.MAITRE_OUVRAGE IS 'Nom du maître d''ouvrage';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.RESPONSABLE_LEVE IS 'Nom de l''entreprise responsable du levé';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.ENTREPRISE_TRAVAUX IS 'Entreprise ayant effectué les travaux de levé (si l''entreprise responsable du levé utilise un sous-traitant, alors c''est le nom du sous-traitant qu''il faut mettre ici).';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.REMARQUE_GEOMETRE IS 'Précision apportée au dossier par le géomètre telle que sa surface et l''origine de la donnée.';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.REMARQUE_PHOTO_INTERPRETE IS 'Remarque du photo-interprète lors de la création du dossier permettant de préciser la raison de sa création, sa délimitation ou le type de bâtiment/voirie qui a été construit/détruit.';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.REPERTOIRE IS 'Répertoire dans lequel sont rangés les fichiers attachés au dossier';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.NOM_FICHIER IS 'Nom du fichier ayant permis l''intégration des données en base.';
COMMENT ON COLUMN G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE.GEOM IS 'Géométrie du dossier - type multipolygone';


-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'V_GG_DOSSIER_REPERTOIRE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;


-- 5. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.V_GG_DOSSIER_REPERTOIRE TO G_GESTIONGEO_MAJ;


/