/*
Requêtes nécessaires à la suppression des table temporaire nécessaire à la création de la vue matérialisée G_REFERENTIEL.ADMIN_IRIS.
*/

-- 9. Suppression des tables temporaire
-- 9.1
DROP TABLE G_REFERENTIEL.TEMP_COMMUNES_VM CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE table_name = 'TEMP_COMMUNES_VM';

-- 9.2
DROP TABLE G_REFERENTIEL.TEMP_COMMUNES_SURFACES CASCADE CONSTRAINTS;

-- 9.3
DROP TABLE G_REFERENTIEL.TEMP_COMMUNES_SURFACES_MAX CASCADE CONSTRAINTS;