/*
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_CONSULTATION';
DROP INDEX TA_RTGE_POINT_CONSULTATION_SIDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_LIBELLE_TYPE_IDX;
DROP TABLE TA_RTGE_POINT_CONSULTATION CASCADE CONSTRAINTS;
*/

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la table TA_RTGE_POINT_CONSULTATION-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue pour afficher les points contenus dans la table G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION avec l'altitude dans un nouveau champ.
--1. Creation
CREATE TABLE G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION
    (
    IDENTIFIANT_OBJET NUMBER(38,0),
    IDENTIFIANT_TYPE NUMBER(38,0),
    CODE_TYPE VARCHAR2(20 BYTE),
    LIBELLE_TYPE VARCHAR2(1000 BYTE),
    LONGUEUR NUMBER(38,3),
    LARGEUR NUMBER(38,3),
    ORIENTATION NUMBER(5,2),
    COORD_Z NUMBER(9,3),
    DATE_MAJ DATE,
    GEOM SDO_GEOMETRY
    )
;


-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION IS 'Table qui présente les points contenus dans la table G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION, avec la coordonnée Z dans un champ spécifique';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique - Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.LONGUEUR IS 'Longueur de l''objet (en cm)';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.LARGEUR IS 'Largeur de l''objet (en cm)';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.ORIENTATION IS 'Orientation de l''objet (en degre)';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.COORD_Z IS 'Altitude du point';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.DATE_MAJ IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION.GEOM IS 'Geometrie de l''objet - type point';


-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION
ADD CONSTRAINT TA_RTGE_POINT_CONSULTATION_IDENTIFIANT_OBJET_PK 
PRIMARY KEY (IDENTIFIANT_OBJET);

-- 4. Clés étrangères
-- Champ FID_IDENTIFIANT_TYPE vers TA_GG_CLASSE

ALTER TABLE G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION
ADD CONSTRAINT TA_RTGE_POINT_CONSULTATION_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 5. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_POINT_CONSULTATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005),SDO_DIM_ELEMENT('Z', -1000, 10000, 0.005)),
    2154
);
COMMIT;


-- 6. Création de l'index spatial sur le champ geom
CREATE INDEX G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION_SIDX
ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 7. INDEX
-- 6.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_RTGE_POINT_CONSULTATION_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.2. Sur le champ CODE_TYPE.
CREATE INDEX TA_RTGE_POINT_CONSULTATION_CODE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_POINT_CONSULTATION_LIBELLE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 8. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_POINT_CONSULTATION TO ISOGEO_LEC;

COMMIT;

/
