/*
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_CONSULTATION';
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_SIDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_LIBELLE_TYPE_IDX;
DROP TABLE TA_RTGE_LINEAIRE_CONSULTATION CASCADE CONSTRAINTS;
*/

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la table TA_RTGE_LINEAIRE_CONSULTATION-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation de la vue G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION qui présente les éléments contenus dans la table G_GESTIONGEO.TA_LIG_TOPO_F_ARCS_LINEARISES
--1. Creation
CREATE TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION
    (
    IDENTIFIANT_OBJET NUMBER(38,0),
    IDENTIFIANT_TYPE NUMBER(38,0),
    CODE_TYPE VARCHAR2(20 BYTE),
    LIBELLE_TYPE VARCHAR2(1000 BYTE),
    DECALAGE_DROITE NUMBER(38,3),
    DECALAGE_GAUCHE NUMBER(38,3),
    DATE_MAJ DATE,
    GEOM SDO_GEOMETRY
    )
;


-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION IS 'Table qui présente les éléments contenus dans la table G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION. Les arcs sont linéarisés';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique - Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.DATE_MAJ IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION.GEOM IS 'Geometrie de l''objet - type ligne';


-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_CONSULTATION_IDENTIFIANT_OBJET_PK 
PRIMARY KEY (IDENTIFIANT_OBJET);


-- 4. Clés étrangères
-- Champ FID_IDENTIFIANT_TYPE vers TA_GG_CLASSE

ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_CONSULTATION_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);


-- 5. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_LINEAIRE_CONSULTATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005),SDO_DIM_ELEMENT('Z', -1000, 10000, 0.005)),
    2154
);
COMMIT;


-- 6. Création de l'index spatial sur le champ geom
CREATE INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=LINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 7. INDEX
-- 7.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_CONSULTATION_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.2. Sur le champ CODE_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_CONSULTATION_CODE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_CONSULTATION_LIBELLE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;


-- 8. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_CONSULTATION TO ISOGEO_LEC;

COMMIT;

/
