/*
TA_GG_FME_FILTRE_SUR_LIGNE : La table TA_GG_FME_FILTRE_SUR_LIGNE est utilisée par la chaine de traitement FME pour corriger certains noms de couches autocad.
*/

-- 1. Création de la table TA_GG_FME_FILTRE_SUR_LIGNE
CREATE TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE (
	OBJECTID NUMBER(38,0) DEFAULT G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID.NEXTVAL NOT NULL,
	"FID_CLASSE" NUMBER(38,0) NOT NULL,
	"FID_CLASSE_SOURCE" NUMBER(38,0) NOT NULL
 );

 -- 2. Les commentaires
COMMENT ON TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE IS 'Table utilisée par la chaîne d''intégration FME pour modifier le nom de certains blocks autocad.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE.OBJECTID IS 'Clé primaire de la table.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE.FID_CLASSE IS 'Clé étrangère vers la table TA_CLASSE. Afin de connaitre la classe à attribuer au block autocad renseigné dans la colonne VALEUR_SOURCE de la table.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE.FID_CLASSE_SOURCE IS 'Valeur source à corriger dans les fichiers à intégrer.';

-- 3. Les contraintes
-- 3.1. Contrainte de clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE
ADD CONSTRAINT TA_GG_FME_FILTRE_SUR_LIGNE_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- 3.2. Contraintes de clé étrangère
ALTER TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE
ADD CONSTRAINT TA_GG_FME_FILTRE_SUR_LIGNE_FID_CLASSE_FK
FOREIGN KEY("FID_CLASSE")
REFERENCES G_GESTIONGEO.TA_GG_CLASSE ("OBJECTID");

-- 4. Création des index sur les clés étrangères
CREATE INDEX TA_GG_FME_FILTRE_SUR_LIGNE_FID_CLA_INU_IDX ON G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE(fid_classe)
	TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE TO G_ADMIN_SIG;

/

