-- 1.2. Creation de la table TA_RTGE_LINEAIRE_ERREUR

-- 1.2.1. Création de la table
CREATE TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR
	(
	OBJECTID NUMBER(38,0),
	GEOM SDO_GEOMETRY NOT NULL,
	FID_NUMERO_DOSSIER NUMBER(38,0),
	FID_IDENTIFIANT_TYPE NUMBER(38,0)
	)
;

-- 1.2.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR IS 'Table utilisée pour stocker les géométries en erreur';

-- 1.2.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR.OBJECTID IS 'Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR.GEOM IS 'Geometrie de la table - type ligne';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Reference du dossier pour lequel l''objet a ete releve';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR.FID_IDENTIFIANT_TYPE IS 'Clé étrangère vers la table TA_GG_CLASSE. Identifiant de la classe de l''objet';

-- 1.2.4. Contraintes

-- 1.2.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR
ADD CONSTRAINT TA_RTGE_LINEAIRE_ERREUR_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";



-- 1.2.5. Création des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME ='TA_RTGE_LINEAIRE_ERREUR';
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_LINEAIRE_ERREUR',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);
COMMIT;

-- creation des index
-- 1.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_ERREUR_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=COLLECTION, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 1.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_ERREUR_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

CREATE INDEX TA_RTGE_LINEAIRE_ERREUR_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 1.2.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_GESTIONGEO_LEC;
GRANT SELECT, UPDATE, DELETE, INSERT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_GESTIONGEO_MAJ;
GRANT INSERT ("GEOM") ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_GESTIONGEO_MAJ;
GRANT UPDATE ("GEOM") ON G_GESTIONGEO.TA_RTGE_LINEAIRE_ERREUR TO G_GESTIONGEO_MAJ;

/
