/*
TA_GG_RELATION_CLASSE_DOMAINE : Cette table de relation permet d'associer une classe à ses domaines d'utilisation.
*/

-- 1. Creation de la table
CREATE TABLE G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE(
    fid_classe NUMBER(38,0) NOT NULL,
    fid_domaine NUMBER(38,0) NOT NULL
);

-- 2. Commentaires
COMMENT ON TABLE G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE IS 'Table de relation permettant d''associer une classe à ses domaines d''utilisation.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE.FID_CLASSE IS 'Clé étrangère vers la table TA_GG_CLASSE.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE.FID_DOMAINE IS 'Clé étrangère vers la table TA_GG_DOMAINE.';

-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE 
ADD CONSTRAINT TA_GG_RELATION_CLASSE_DOMAINE_PK 
PRIMARY KEY("FID_CLASSE","FID_DOMAINE") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des index
CREATE INDEX TA_GG_RELATION_CLASSE_DOMAINE_FID_CLASSE_IDX ON G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE(FID_CLASSE)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GG_RELATION_CLASSE_DOMAINE_FID_DOMAINE_IDX ON G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE(FID_DOMAINE)
    TABLESPACE G_ADT_INDX;

-- 2.4. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE TO G_ADMIN_SIG;

/

