/*
La table TA_GG_DOSSIER_LOG  permet d''avoir l''historique de toutes les évolutions des périmètres des dossiers des géomètres (GestionGeo).
*/

-- 1. Création de la table TA_GG_DOSSIER_LOG
CREATE TABLE G_GESTIONGEO.TA_GG_DOSSIER_LOG(
    "OBJECTID" NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    "ID_DOSSIER" NUMBER(38,0) NOT NULL,
    "ID_ETAT_AVANCEMENT" NUMBER(38,0),
    "ID_FAMILLE" NUMBER(38,0),
    "ID_PERIMETRE" NUMBER(38,0),
    "DATE_DEBUT_LEVE" DATE,
    "DATE_FIN_LEVE" DATE,
    "DATE_DEBUT_TRAVAUX" DATE,
    "DATE_FIN_TRAVAUX" DATE,
    "DATE_COMMANDE_DOSSIER" DATE,
    "MAITRE_OUVRAGE" VARCHAR2(200 BYTE),
    "RESPONSABLE_LEVE" VARCHAR2(200 BYTE),
    "ENTREPRISE_TRAVAUX" VARCHAR2(200 BYTE),
    "REMARQUE_GEOMETRE" VARCHAR2(4000 BYTE),
    "REMARQUE_PHOTO_INTERPRETE" VARCHAR2(4000 BYTE),
    "DATE_ACTION" DATE NOT NULL,
    "FID_TYPE_ACTION" NUMBER(38,0) NOT NULL,
    "FID_PNOM" NUMBER(38,0) NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_GESTIONGEO.TA_GG_DOSSIER_LOG IS 'Table de log de la table TA_GG_DOSSIER permettant d''avoir l''historique de toutes les évolutions des dossiers des levés des géomètres. Précision : cette table contient au maximum l''état n-1 de chaque entité.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.id_dossier IS 'Identifiant de la table TA_GG_DOSSIER permettant de savoir sur quel dossier les actions ont été entreprises.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.id_etat_avancement IS 'Identifiants de la table TA_GG_ETAT_AVANCEMENT dans laquelle se trouve tous les états d''avancement que peuvent prendre les dossiers.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.id_famille IS 'Identifiant de la table TA_GG_FAMILLE permettant de savoir à quelle famille appartient chaque dossier : plan de récolement, investigation complémentaire, maj carto.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.id_perimetre IS 'Identifiant de la table TA_GG_GEO, permettant d''associer un périmètre à un dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_debut_leve IS 'Date de début des levés de l''objet (du dossier) par les géomètres.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_fin_leve IS 'Date de fin des levés de l''objet (du dossier) par les géomètres.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_debut_travaux IS 'Date de début des travaux sur l''objet concerné par le dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_fin_travaux IS 'Date de fin des travaux sur l''objet concerné par le dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_commande_dossier IS 'Date de commande ou de création de dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.maitre_ouvrage IS 'Nom du maître d''ouvrage.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.responsable_leve IS 'Nom de l''entreprise responsable du levé.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.entreprise_travaux IS 'Entreprise ayant effectué les travaux de levé (si l''entreprise responsable du levé utilise un sous-traitant, alors c''est le nom du sous-traitant qu''il faut mettre ici).';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.remarque_geometre IS 'Précision apportée au dossier par le géomètre telle que sa surface et l''origine de la donnée.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.remarque_photo_interprete IS 'Remarque du photo-interprète lors de la création du dossier permettant de préciser la raison de sa création, sa délimitation ou le type de bâtiment/voirie qui a été construit/détruit.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.date_action IS 'Date de création, modification ou suppression de la géométrie d''un dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.fid_type_action IS 'Clé étrangère vers la table TA_LIBELLE permettant de savoir quelle action a été effectuée sur le périmètre du dossier.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_LOG.fid_pnom IS 'Clé étrangère vers la table TA_GG_AGENT permettant d''associer le pnom d''un agent au périmètre du dossier qu''il a créé, modifié ou supprimé.';

-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_LOG 
ADD CONSTRAINT TA_GG_DOSSIER_LOG_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_LOG
ADD CONSTRAINT TA_GG_DOSSIER_LOG_FID_TYPE_ACTION_FK 
FOREIGN KEY (fid_type_action)
REFERENCES G_GEO.TA_LIBELLE(objectid);

ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_LOG
ADD CONSTRAINT TA_GG_DOSSIER_LOG_FID_PNOM_FK
FOREIGN KEY (fid_pnom)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 5. Création des index sur les clés étrangères et autres
CREATE INDEX TA_GG_DOSSIER_LOG_FID_PERIMETRE_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(id_dossier)
    TABLESPACE G_ADT_INDX;
    
CREATE INDEX TA_GG_DOSSIER_LOG_ID_DOSSIER_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(id_perimetre)
    TABLESPACE G_ADT_INDX;
    
CREATE INDEX TA_GG_DOSSIER_LOG_FID_TYPE_ACTION_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(fid_type_action)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GG_DOSSIER_LOG_FID_PNOM_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(fid_pnom)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GG_DOSSIER_LOG_ACTION_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(fid_type_action, fid_pnom, date_action)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GG_DOSSIER_LOG_ID_ETAT_AVANCEMENT_IDX ON G_GESTIONGEO.TA_GG_DOSSIER_LOG(id_etat_avancement)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GESTIONGEO.TA_GG_DOSSIER_LOG TO G_ADMIN_SIG;

/

