/*
TA_GG_PRIX: Affecte à chaque classe de trafic des troncons un cout à l'hectometre utilisé pour calculer les devis des dossiers GestionGeo à relever
*/

-- 1.1. Creation de la table.
CREATE TABLE G_GESTIONGEO.TA_GG_PRIX (
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
	fid_libelle NUMBER(38,0),
	prix NUMBER(38,0)
	)
;


-- 1.2. Commentaire de la table et des colonnes
COMMENT ON TABLE G_GESTIONGEO.TA_GG_PRIX IS 'Affecte à chaque classe de trafic des troncons un cout à l''hectometre utilisé pour calculer les devis des dossiers GestionGeo à relever';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_PRIX.fid_libelle IS 'Clé étrangère vers la table TA_GG_LIBELLE pour identier le type de voie estime par le cout';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_PRIX.PRIX IS 'Prix à l''hectometre du releve du type de voie considere.';


-- 1.3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_PRIX 
ADD CONSTRAINT TA_GG_PRIX_HIERARCHIE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";


-- 1.4. Création des clés étrangères
-- 1.4.1. Vers la table TA_GG_LIBELLE
ALTER TABLE G_GESTIONGEO.TA_GG_PRIX
ADD CONSTRAINT TA_GG_PRIX_FID_LIBELLE_FK
FOREIGN KEY("FID_LIBELLE")
REFERENCES G_GESTIONGEO.TA_GG_LIBELLE(objectid);


-- 1.5. Création des index sur les clés étrangères
CREATE INDEX TA_GG_PRIX_FID_LIBELLE_IDX ON G_GESTIONGEO.TA_GG_PRIX(fid_libelle)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GG_PRIX_TRONCON_PRIX_IDX ON G_GESTIONGEO.TA_GG_PRIX(prix)
    TABLESPACE G_ADT_INDX;

-- 1.6. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_GG_PRIX TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_GG_PRIX TO G_GESTIONGEO_LEC;