-- 2.2. Creation de la table TA_IC_LINEAIRE

-- 2.2.1. Creation de la table

CREATE TABLE G_GESTIONGEO.TA_IC_LINEAIRE
	(
	OBJECTID NUMBER(38,0),
	GEOM SDO_GEOMETRY NOT NULL,
	FID_NUMERO_DOSSIER NUMBER(38,0) NOT NULL,
	FID_IDENTIFIANT_TYPE NUMBER(38,0) NOT NULL,
--	GEO_INSEE CHAR(3 BYTE),
--	DATE_DEBUT_VALIDITE DATE,
--	DATE_FIN_VALIDITE DATE,
--	VALIDITE NUMBER(1,0),
--	GEO_TEXTE VARCHAR2(2048 BYTE),
--	DECALAGE_DROITE NUMBER(8,0),
--	DECALAGE_GAUCHE NUMBER(8,0),
--	GEO_TYPE CHAR(1 BYTE),
	FID_PNOM_CREATION NUMBER(38,0) NOT NULL,
	DATE_CREATION DATE NOT NULL,
	FID_PNOM_MODIFICATION NUMBER(38,0),
	DATE_MODIFICATION DATE,
	LONGUEUR NUMBER(38,0) AS (ROUND(GET_LONGUEUR_LIGNE(GEOM,'TA_IC_LINEAIRE')))
	)
;

-- 2.2.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_IC_LINEAIRE IS 'Table utilisée pour inserer les points releves par le geometre avant leur validation';

-- 2.2.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.OBJECTID IS 'Clé primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.GEOM IS 'Géometrie de la table - type ligne';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Référence du dossier pour lequel l''objet a été relevé';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.FID_IDENTIFIANT_TYPE IS 'Clé étrangère vers la table TA_GG_CLASSE. Identifiant de la classe de l''objet';
--COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DATE_DEBUT_VALIDITE IS 'Date de debut de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DATE_FIN_VALIDITE IS 'Date de fin de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.VALIDITE IS 'Validite de l''objet';
--COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
--COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.FID_PNOM_CREATION IS 'Clé étrangère vers la table TA_GG_AGENT. Agent qui a créé l''objet.';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DATE_CREATION IS 'Date de creation de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.FID_PNOM_MODIFICATION IS 'Clé étrangère vers la table TA_GG_AGENT. Dernier agent qui a modifié l''objet.';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.DATE_MODIFICATION IS 'Date de dernière modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_IC_LINEAIRE.LONGUEUR IS 'Longueur arrondie du linéaire';


-- 2.2.4. Contraintes

-- 2.2.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_IC_LINEAIRE
ADD CONSTRAINT TA_IC_LINEAIRE_OBJECTID_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 2.2.4.2. Clés étrangères

-- 2.2.4.2.1. CHAMP FID_IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_IC_LINEAIRE
ADD CONSTRAINT TA_IC_LINEAIRE_FID_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (FID_IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 2.2.4.2.2. CHAMP PNOM_CREATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_IC_LINEAIRE
ADD CONSTRAINT TA_IC_LINEAIRE_PNOM_CREATION_FK 
FOREIGN KEY (FID_PNOM_CREATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.2.4.2.3. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_IC_LINEAIRE
ADD CONSTRAINT TA_IC_LINEAIRE_PNOM_MODIFICATION_FK 
FOREIGN KEY (FID_PNOM_MODIFICATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.2.4.2.4. CHAMP FID_NUMERO_DOSSIER VERS G_GESTIONGEO.TA_GG_DOSSIER
ALTER TABLE G_GESTIONGEO.TA_IC_LINEAIRE
ADD CONSTRAINT TA_IC_LINEAIRE_FID_NUMERO_DOSSIER_FK 
FOREIGN KEY (FID_NUMERO_DOSSIER)
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 2.2.5. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_IC_LINEAIRE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);


-- 2.2.6. Creation des index
-- 2.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_IC_LINEAIRE_SIDX
ON G_GESTIONGEO.TA_IC_LINEAIRE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 2.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_IC_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;


-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_IC_LINEAIRE_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- 2.2.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_IC_LINEAIRE TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_IC_LINEAIRE TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_IC_LINEAIRE TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_IC_LINEAIRE TO G_GESTIONGEO_LEC;
GRANT SELECT, UPDATE, DELETE, INSERT ON  G_GESTIONGEO.TA_IC_LINEAIRE TO G_GESTIONGEO_MAJ;
GRANT UPDATE ("GEOM") ON G_GESTIONGEO.TA_IC_LINEAIRE TO G_GESTIONGEO_MAJ;

/
