-- 1. TA_GG_DOSSIER_DEVIS
-- Creation de la table TA_GG_DOSSIER_DEVIS
-- Recapitule pour chaque dossier la longueur de chaque type de voie (selon la table SIREO.OUT_CLAS_TRAF) intersectée et le cout estimé du relevé de cette longueur.


-- 1.1. Creation de la table.
CREATE TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS
  (
    OBJECTID NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1, 
    NUMERO_DOSSIER NUMBER(38,0), 
    TYPE_VOIE NUMBER(38,0),
    LONGUEUR_VOIE NUMBER(38,2) AS (GET_LONGUEUR_TYPE_VOIE(numero_dossier, type_voie)),
    DEVIS NUMBER(38,2) AS (GET_DEVIS_TYPE_VOIE(numero_dossier, type_voie))
  );

-- 1.2. Les contraintes
-- 1.2.1. Contrainte de clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS
ADD CONSTRAINT TA_GG_DOSSIER_DEVIS_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- 1.2.2. Contrainte unicité
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS
ADD CONSTRAINT TA_GG_DOSSIER_DEVIS_NUMERO_DOSSIER_TYPE_VOIE_UNIQUE UNIQUE("NUMERO_DOSSIER", "TYPE_VOIE");

-- 1.2.3. Contraintes de clé étrangère
-- 1.2.3.1. Clé étrangère sur le champ NUMERO DOSSIER
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS
ADD CONSTRAINT TA_GG_DOSSIER_DEVIS_NUMERO_DOSSIER_FK
FOREIGN KEY("NUMERO_DOSSIER")
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER("OBJECTID");


-- 1.2.3.2. Clé étrangère sur le champ TYPE_VOIE
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS
ADD CONSTRAINT TA_GG_DOSSIER_DEVIS_TYPE_VOIE_FK
FOREIGN KEY("TYPE_VOIE")
REFERENCES G_GESTIONGEO.TA_GG_LIBELLE("OBJECTID");


-- 1.3. Commentaire de la table
COMMENT ON TABLE G_GESTIONGEO.TA_GG_DOSSIER_DEVIS  IS 'devis estimé du relevé d''un dossier par type de voie de l''application GestionGeo';


-- 1.4. Commentaire des champs
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_DEVIS.OBJECTID IS 'Clé primaire de la vue.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_DEVIS.NUMERO_DOSSIER IS 'Numéro du dossier considéré, clé étrangère vers la table TA_GG_DOSSIER';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_DEVIS.TYPE_VOIE IS 'Type de voie à relevé en terme de traffic clé étrangère vers la table TA_GG_LIBELLE';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_DEVIS.LONGUEUR_VOIE IS 'Longueur de voie estimée à relever en hectomètre';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_DOSSIER_DEVIS.DEVIS IS 'Prix du devis selon le type de voie et le dossier';

-- 1.5. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_GG_DOSSIER_DEVIS TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_GG_DOSSIER_DEVIS TO G_GESTIONGEO_LEC;