-- 2.2. Creation de la table TA_RTGE_LINEAIRE_FIN

-- 2.2.1. Creation de la table

CREATE TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
	(
	OBJECTID NUMBER(38,0),
	GEOM SDO_GEOMETRY,
	NUMERO_DOSSIER VARCHAR2(13 BYTE),	
	IDENTIFIANT_TYPE NUMBER(8,0),
--	GEO_INSEE CHAR(3 BYTE),
--	DATE_DEBUT_VALIDITE DATE,
--	DATE_FIN_VALIDITE DATE,
--	VALIDITE NUMBER(1,0),
--	GEO_TEXTE VARCHAR2(2048 BYTE),
	DECALAGE_DROITE NUMBER(8,0),
	DECALAGE_GAUCHE NUMBER(8,0),
--	GEO_TYPE CHAR(1 BYTE),
	FID_PNOM_CREATION NUMBER(38,0),
	DATE_CREATION DATE,
	FID_PNOM_MODIFICATION NUMBER(38,0),
	DATE_MODIFICATION DATE,
	LONGUEUR NUMBER(38,0) AS (ROUND(GET_LONGUEUR_LIGNE(GEOM,'TA_RTGE_LINEAIRE_FIN')))
	)
;

-- 2.2.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN IS 'Table utilisée pour inserer les points releves par le geometre avant leur validation';

-- 2.2.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.OBJECTID IS 'Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.GEOM IS 'Geometrie de la table - type ligne';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.NUMERO_DOSSIER IS 'Reference du dossier pour lequel l''objet a ete releve';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.IDENTIFIANT_TYPE IS 'Identifiant de la classe de l''objet';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DATE_DEBUT_VALIDITE IS 'Date de debut de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DATE_FIN_VALIDITE IS 'Date de fin de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.VALIDITE IS 'Validite de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.FID_PNOM_CREATION IS 'Agent qui a cree l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DATE_CREATION IS 'Date de creation de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.FID_PNOM_MODIFICATION IS 'Dernier agent qui a modifie l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN.LONGUEUR IS 'Longueur du lineaire';


-- 2.2.4. Contraintes

-- 2.2.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
ADD CONSTRAINT TA_RTGE_LINEAIRE_FIN_OBJECTID_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 2.2.4.2. Clés étrangères

-- 2.2.4.2.1. CHAMP IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
ADD CONSTRAINT TA_RTGE_LINEAIRE_FIN_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 2.2.4.2.2. CHAMP PNOM_CREATION VERS G_GESTIONGEO.TA_GG_AGENT
-- ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
-- ADD CONSTRAINT TA_RTGE_LINEAIRE_FIN_PNOM_CREATION_FK 
-- FOREIGN KEY (PNOM_CREATION)
-- REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.2.4.2.3. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
-- ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
-- ADD CONSTRAINT TA_RTGE_LINEAIRE_FIN_PNOM_MODIFICATION_FK 
-- FOREIGN KEY (PNOM_MODIFICATION)
-- REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.2.4.2.4. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
--ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN
--ADD CONSTRAINT TA_RTGE_LINEAIRE_FIN_NUMERO_DOSSIER_FK 
--FOREIGN KEY (NUMERO_DOSSIER)
--REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 2.2.5. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_LINEAIRE_FIN',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);


-- 2.2.6. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_FIN_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=LINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 2.2.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_FIN TO G_GESTIONGEO_MAJ;
/
