/*
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_SOMMET';
DROP INDEX TA_RTGE_LINEAIRE_SOMMET_SIDX;
DROP INDEX TA_RTGE_LINEAIRE_SOMMET_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_SOMMET_LIBELLE_COURT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_SOMMET_LIBELLE_TYPE_IDX;
DROP TABLE TA_RTGE_LINEAIRE_SOMMET;
*/

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la table TA_RTGE_LINEAIRE_SOMMET-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue matérialisée pour afficher les sommets des linéaires contenus dans la table G_GESTIONGEO.TA_LIG_TOPO_F avec l'altitude dans un champ.
--1. Creation
CREATE TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
    (
    OBJECTID NUMBER(38,0),
    IDENTIFIANT_OBJET NUMBER(38,0),
    FID_NUMERO_DOSSIER NUMBER(38,0),
    FID_IDENTIFIANT_TYPE NUMBER(38,0),
    LIBELLE_COURT_TYPE VARCHAR2(6 BYTE),
    LIBELLE_TYPE VARCHAR2(100 BYTE),
    DECALAGE_DROITE NUMBER(8,3),
    DECALAGE_GAUCHE NUMBER(8,3),
    COORD_Z NUMBER(9,2),
    FID_PNOM_CREATION NUMBER(38,0),
    DATE_CREATION DATE,
    FID_PNOM_MODIFICATION NUMBER(38,0),
    DATE_MODIFICATION DATE,
    GEOM SDO_GEOMETRY
    )
;


-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET IS 'Table qui présente les sommets des lineaires contenus dans la table GEO@cudl.TA_LIG_TOPO_F, avec la coordonée Z dans un champ spécifique';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.OBJECTID IS 'Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique d''appartenance';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Référence du dossier pour lequel l''objet a ete releve';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.FID_IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.LIBELLE_COURT_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.COORD_Z IS 'Altitude du sommet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT.FID_PNOM_CREATION IS 'Clé étrangère vers la table TA_GG_AGENT. Agent qui a cree l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT.DATE_CREATION IS 'Date de creation de l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT.FID_PNOM_MODIFICATION IS 'Clé étrangère vers la table TA_GG_AGENT. Dernier agent qui a modifie l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_POINT.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET.GEOM IS 'Geometrie du sommet - type point';


-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
ADD CONSTRAINT TA_RTGE_LINEAIRE_SOMMET_OBJECTID_PK 
PRIMARY KEY (OBJECTID);


-- 2.1.4.2. Clés étrangères

-- 2.1.4.2.1. CHAMP FID_IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
ADD CONSTRAINT TA_RTGE_LINEAIRE_SOMMET_FID_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (FID_IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 2.1.4.2.2. CHAMP PNOM_CREATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
ADD CONSTRAINT TA_RTGE_LINEAIRE_SOMMET_PNOM_CREATION_FK 
FOREIGN KEY (FID_PNOM_CREATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.1.4.2.3. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
ADD CONSTRAINT TA_RTGE_LINEAIRE_SOMMET_PNOM_MODIFICATION_FK 
FOREIGN KEY (FID_PNOM_MODIFICATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.1.4.2.4. CHAMP FID_NUMERO_DOSSIER vers G_GESTIONGEO.TA_GG_DOSSIER
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET
ADD CONSTRAINT TA_RTGE_LINEAIRE_SOMMET_FID_NUMERO_DOSSIER_FK 
FOREIGN KEY (FID_NUMERO_DOSSIER)
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 4. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_LINEAIRE_SOMMET',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005),SDO_DIM_ELEMENT('Z', -1000, 10000, 0.005)),
    2154
);
COMMIT;


-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 6. INDEX
-- 6.1. Sur le champ FID_IDENTIFIANT_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_SOMMET_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET(FID_IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.2. Sur le champ LIBELLE_COURT_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_SOMMET_LIBELLE_COURT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET(LIBELLE_COURT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_LINEAIRE_SOMMET_LIBELLE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.4 Sur les champs objectid et identifiant objet
CREATE INDEX TA_RTGE_LINEAIRE_SOMMET_OBJECTID_IDENTIFIANT_OBJET_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET(OBJECTID, IDENTIFIANT_OBJET)
    TABLESPACE G_ADT_INDX;

-- 8. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET TO ISOGEO_LEC;