-- 1.2. Creation de la table TA_RTGE_LINEAIRE_INTEGRATION

-- 1.2.1. Création de la table
CREATE TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
	(
	OBJECTID NUMBER(38,0) DEFAULT G_GESTIONGEO.SEQ_TA_RTGE_LINEAIRE_INTEGRATION_OBJECTID.NEXTVAL NOT NULL ENABLE, 
	GEOM SDO_GEOMETRY NOT NULL,
	FID_NUMERO_DOSSIER NUMBER(38,0) NOT NULL,
	FID_IDENTIFIANT_TYPE NUMBER(38,0) NOT NULL,
--	GEO_INSEE CHAR(3 BYTE),
--	DATE_DEBUT_VALIDITE DATE,
--	DATE_FIN_VALIDITE DATE,
--	VALIDITE NUMBER(1,0),
--	GEO_TEXTE VARCHAR2(2048 BYTE),
	DECALAGE_DROITE NUMBER(38,3),
	DECALAGE_GAUCHE NUMBER(38,3),
--	GEO_TYPE CHAR(1 BYTE),
	FID_PNOM_CREATION NUMBER(38,0) NOT NULL,
	DATE_CREATION DATE NOT NULL,
	FID_PNOM_MODIFICATION NUMBER(38,0),
	DATE_MODIFICATION DATE,
	LONGUEUR NUMBER(38,0) AS (GET_LONGUEUR_LIGNE(GEOM, 'TA_RTGE_LINEAIRE_INTEGRATION')),
	ETAT_INTEGRATION NUMBER (1,0) DEFAULT 0
	)
;

-- 1.2.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION IS 'Table utilisée pour inserer les points releves par le geometre avant leur validation';

-- 1.2.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.OBJECTID IS 'Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.GEOM IS 'Geometrie de la table - type ligne';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Reference du dossier pour lequel l''objet a ete releve';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.FID_IDENTIFIANT_TYPE IS 'Clé étrangère vers la table TA_GG_CLASSE. Identifiant de la classe de l''objet';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DATE_DEBUT_VALIDITE IS 'Date de debut de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DATE_FIN_VALIDITE IS 'Date de fin de validite';
--COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.VALIDITE IS 'Validite de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.FID_PNOM_CREATION IS 'Clé étrangère vers la table TA_GG_AGENT. Agent qui a cree l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DATE_CREATION IS 'Date de creation de l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.FID_PNOM_MODIFICATION IS 'Clé étrangère vers la table TA_GG_AGENT. Dernier agent qui a modifie l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.LONGUEUR IS 'Longueur du lineaire';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION.ETAT_INTEGRATION IS 'Colonne pour indiquer si l''objet est a migrer - 0 non, 1 oui';


-- 1.2.4. Contraintes

-- 1.2.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_INTEGRATION_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 1.2.4.2. Clés étrangères

-- 1.2.4.2.1. CHAMP FID_IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_INTEGRATION_FID_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (FID_IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 1.2.4.2.2. CHAMP PNOM_CREATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_INTEGRATION_PNOM_CREATION_FK 
FOREIGN KEY (FID_PNOM_CREATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 1.2.4.2.3. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_INTEGRATION_PNOM_MODIFICATION_FK 
FOREIGN KEY (FID_PNOM_MODIFICATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 1.2.4.2.4. CHAMP FID_NUMERO_DOSSIER vers G_GESTIONGEO.TA_GG_DOSSIER
ALTER TABLE G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION
ADD CONSTRAINT TA_RTGE_LINEAIRE_INTEGRATION_FID_NUMERO_DOSSIER_FK 
FOREIGN KEY (FID_NUMERO_DOSSIER)
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 1.2.5. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_LINEAIRE_INTEGRATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);

-- creation des index
-- 1.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 1.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 1.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 1.2.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_GESTIONGEO_LEC;
GRANT SELECT, UPDATE, DELETE, INSERT ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_GESTIONGEO_MAJ;
GRANT INSERT ("GEOM") ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_GESTIONGEO_MAJ;
GRANT UPDATE ("GEOM") ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION TO G_GESTIONGEO_MAJ;

/
