-- Création de la table G_GESTIONGEO.TA_RTGE_SURFACE
-- Table qui sert à accueillir les objets topographiques polygonisés.


-- 2.1.1. Création de la table.
CREATE TABLE G_GESTIONGEO.TA_RTGE_SURFACE
	(
	OBJECTID NUMBER(38,0) DEFAULT G_GESTIONGEO.SEQ_TA_RTGE_SURFACE_OBJECTID.NEXTVAL NOT NULL ENABLE, 
	GEOM SDO_GEOMETRY,
    SOURCE_IDENTIFIANT_OBJET NUMBER(38,0),
	FID_NUMERO_DOSSIER NUMBER(38),
	FID_IDENTIFIANT_TYPE NUMBER(38),
	FID_PNOM_CREATION NUMBER(38),
	DATE_CREATION DATE,
	FID_PNOM_MODIFICATION NUMBER(38),
	DATE_MODIFICATION DATE,
	FID_IDENTIFIANT_OBJET_INTEGRATION NUMBER(38,0),
    SOURCE_ELEMENT NUMBER(1),
    TYPE_GEOM NUMBER(1)
	)
;


-- 2.1.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_SURFACE IS 'Table qui sert à accueillir les objets topographiques contenus dans la table TA_RTGE_POINT polygonisés ainsi que les polygones des MUFs';


-- 2.1.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.OBJECTID IS 'Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.SOURCE_IDENTIFIANT_OBJET IS 'Identifiant de l''entité dans la table source G_GEO.TA_RTGE_POINT, G_GEO.TA_RTGE_LINAIRE_SOMMET';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.GEOM IS 'Géometrie des éléments de la table - type polygones';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Référence du dossier pour lequel l''objet a ete releve';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.FID_IDENTIFIANT_TYPE IS 'Clé étrangère vers la table TA_GG_CLASSE. Identifiant de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.FID_PNOM_CREATION IS 'Clé étrangère vers la table TA_GG_AGENT. Agent qui a cree l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.DATE_CREATION IS 'Date de creation de l''element';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.FID_PNOM_MODIFICATION IS 'Clé étrangère vers la table TA_GG_AGENT. Dernier agent qui a modifie l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.FID_IDENTIFIANT_OBJET_INTEGRATION IS 'Clé étrangère vers la table TA_RTGE_SURFACE_INTEGRATION_LOG. Permet d''avoir l''historique de l''objet depuis son intégration.';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.SOURCE_ELEMENT IS 'Provenance du point, 1: G_GEO.TA_RTGE_POINT; 2: G_GEO.TA_RTGE_LINEAIRE';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_SURFACE.TYPE_GEOM IS 'Type du polygone, 1: quadrilatere; 2: cercle';


-- 2.1.4. Contraintes

-- 2.1.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_SURFACE
ADD CONSTRAINT TA_RTGE_SURFACE_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 2.1.4.2. Clés étrangères

-- 2.1.4.2.1. CHAMP FID_IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_RTGE_SURFACE
ADD CONSTRAINT TA_RTGE_SURFACE_FID_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (FID_IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);

-- 2.1.4.2.2. CHAMP PNOM_CREATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_SURFACE
ADD CONSTRAINT TA_RTGE_SURFACE_PNOM_CREATION_FK 
FOREIGN KEY (FID_PNOM_CREATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.1.4.2.3. CHAMP PNOM_MODIFICATION VERS G_GESTIONGEO.TA_GG_AGENT
ALTER TABLE G_GESTIONGEO.TA_RTGE_SURFACE
ADD CONSTRAINT TA_RTGE_SURFACE_PNOM_MODIFICATION_FK 
FOREIGN KEY (FID_PNOM_MODIFICATION)
REFERENCES G_GESTIONGEO.TA_GG_AGENT(objectid);

-- 2.1.4.2.4. CHAMP FID_NUMERO_DOSSIER vers G_GESTIONGEO.TA_GG_DOSSIER
ALTER TABLE G_GESTIONGEO.TA_RTGE_SURFACE
ADD CONSTRAINT TA_RTGE_SURFACE_FID_NUMERO_DOSSIER_FK 
FOREIGN KEY (FID_NUMERO_DOSSIER)
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 2.1.5. Création des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME ='TA_RTGE_SURFACE';
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_SURFACE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);
COMMIT;

-- 2.1.6. Creation des index
-- 2.1.6.1 Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_SURFACE_SIDX
ON G_GESTIONGEO.TA_RTGE_SURFACE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 2.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_SURFACE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 2.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_SURFACE_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 2.1.6.4. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_SURFACE_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_IDENTIFIANT_OBJET_INTEGRATION) TABLESPACE G_ADT_INDX;


-- 2.1.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_SURFACE TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_SURFACE TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_SURFACE TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_SURFACE TO G_GESTIONGEO_LEC;
GRANT SELECT, UPDATE, DELETE, INSERT ON G_GESTIONGEO.TA_RTGE_SURFACE TO G_GESTIONGEO_MAJ;
GRANT UPDATE ("GEOM") ON G_GESTIONGEO.TA_RTGE_SURFACE TO G_GESTIONGEO_MAJ;

/
