-- 1.3. Creation de la table TA_PTTOPO_INTEGRATION

-- 1.3.1. Creation de la table
CREATE TABLE G_GESTIONGEO.TA_PTTOPO_INTEGRATION
	(
	OBJECTID NUMBER(38,0)DEFAULT G_GESTIONGEO.SEQ_TA_PTTOPO_INTEGRATION_OBJECTID.NEXTVAL NOT NULL ENABLE, 
	GEOM SDO_GEOMETRY NOT NULL,
	FID_NUMERO_DOSSIER NUMBER(38,0) NOT NULL,
	ALT NUMBER(6,3),
	MAT NUMBER(38,0),
    FID_PNOM_CREATION NUMBER(38,0) NOT NULL,
    DATE_CREATION DATE NOT NULL, 
    FID_PNOM_MODIFICATION NUMBER(38,0),
    DATE_MODIFICATION DATE
	)
;

-- 1.3.2. Commentaire de la table

COMMENT ON TABLE TA_PTTOPO_INTEGRATION IS 'Table qui contient les points topographique releves par les geometre';

-- 1.3.3. Commentaires des colonnes
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.OBJECTID IS 'Cle primaire de la table';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.GEOM IS 'Geometrie de l''element - type point';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.FID_NUMERO_DOSSIER IS 'Clé étrangère vers la table TA_GG_DOSSIER. Numero du dossier pour lequel le point a été relevé.';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.ALT IS 'Altitude du point';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.MAT IS 'Matricule du point';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.FID_PNOM_CREATION IS 'Clé étrangère vers la table TA_GG_AGENT. Agent qui a cree l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.DATE_CREATION IS 'Date de creation de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.FID_PNOM_MODIFICATION IS 'Clé étrangère vers la table TA_GG_LIBELLE. Dernier agent qui a modifie l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_PTTOPO_INTEGRATION.DATE_MODIFICATION IS 'Date de derniere modification de l''objet';

-- 1.3.4. Contraintes
-- 1.3.4.1 Clé primaire

ALTER TABLE G_GESTIONGEO.TA_PTTOPO_INTEGRATION
ADD CONSTRAINT TA_PTTOPO_INTEGRATION_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 1.3.4.2 Clé étrangères

-- 1.3.4.2.1. CHAMP FID_NUMERO_DOSSIER vers G_GESTIONGEO.TA_GG_DOSSIER
ALTER TABLE G_GESTIONGEO.TA_PTTOPO_INTEGRATION
ADD CONSTRAINT TA_PTTOPO_INTEGRATION_FID_NUMERO_DOSSIER_FK 
FOREIGN KEY (FID_NUMERO_DOSSIER)
REFERENCES G_GESTIONGEO.TA_GG_DOSSIER(objectid);


-- 1.3.5. Création des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME ='TA_PTTOPO_INTEGRATION';
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_PTTOPO_INTEGRATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005),SDO_DIM_ELEMENT('Z', -100, 100, 0.005)),
    2154
);

COMMIT;


-- 1.3.6. Création de l'index spatial sur le champ geom
CREATE INDEX TA_PTTOPO_INTEGRATION_SIDX
ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.1.6.3. Creation d'un index sur le champ numero dossier
CREATE INDEX TA_PTTOPO_INTEGRATION_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 1.3.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION TO G_GESTIONGEO_LEC;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_GESTIONGEO.TA_PTTOPO_INTEGRATION TO G_GESTIONGEO_MAJ;

/
