/*
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_ALTI_CONSULTATION';
DROP INDEX TA_RTGE_ALTI_CONSULTATION_SIDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_LIBELLE_TYPE_IDX;
DROP TABLE TA_RTGE_ALTI_CONSULTATION CASCADE CONSTRAINTS;
*/

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la table TA_RTGE_ALTI_CONSULTATION----------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue matérialisée pour afficher les sommets des linéaires contenus dans la table G_GESTIONGEO.TA_LIG_TOPO_F avec l'altitude dans un champ.
--1. Creation
CREATE TABLE G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION
    (
    OBJECTID NUMBER(38,0) DEFAULT G_GESTIONGEO.SEQ_TA_RTGE_ALTI_CONSULTATION_OBJECTID.NEXTVAL NOT NULL ENABLE,
    FID_IDENTIFIANT NUMBER(38,0),
    IDENTIFIANT_OBJET NUMBER(38,0),
    IDENTIFIANT_TYPE NUMBER(38,0),
    CODE_TYPE VARCHAR2(20 BYTE),
    LIBELLE_TYPE VARCHAR2(1000 BYTE),
    COORD_Z NUMBER(9,3),
    SOURCE_ELEMENT NUMBER(1),
    DATE_MAJ DATE,
    GEOM SDO_GEOMETRY
)
;

-- 2. Commentaire
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION IS 'Table qui présente les éléments contenus dans les tables G_GESTIONGEO.TA_RTGE_POINT et G_GESTIONGEO.TA_RTGE_LINAIRE_SOMMET_CONSULTATION situés dans le perimètre de la MEL et dont l''altitude est comprise entre 0 et 130 m';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.OBJECTID IS 'Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.FID_IDENTIFIANT IS 'Identifiant de l''entité dans la table source G_GESTIONGEO.TA_RTGE_POINT, G_GESTIONGEO.TA_RTGE_LINAIRE_SOMMET_CONSULTATION';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique d''appartenance dans les tables G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION et G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.COORD_Z IS 'Altitude du sommet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.SOURCE_ELEMENT IS 'Provenance du point, 1: G_GESTIONGEO.TA_RTGE_POINT; 2: G_GESTIONGEO.TA_RTGE_LINAIRE_SOMMET_CONSULTATION';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.DATE_MAJ IS 'Date de derniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION.GEOM IS 'Geometrie de l''objet - type ligne';


-- 3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION
ADD CONSTRAINT TA_RTGE_ALTI_CONSULTATION_OBJECTID_PK 
PRIMARY KEY (OBJECTID);


-- 4. Clés étrangères
-- Champ FID_IDENTIFIANT_TYPE vers TA_GG_CLASSE

ALTER TABLE G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION
ADD CONSTRAINT TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_TYPE_FK 
FOREIGN KEY (IDENTIFIANT_TYPE)
REFERENCES G_GESTIONGEO.TA_GG_CLASSE(objectid);


-- 5. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_RTGE_ALTI_CONSULTATION',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005),SDO_DIM_ELEMENT('Z', 1, 200, 0.005)),
    2154
);
COMMIT;


-- 6. Création de l'index spatial sur le champ geom
CREATE INDEX G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION_SIDX
ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 7. INDEX
-- 7.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.2. Sur le champ CODE_TYPE.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_CODE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_LIBELLE_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.4. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_FID_IDENTIFIANT_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(FID_IDENTIFIANT)
    TABLESPACE G_ADT_INDX;

-- 7.5. Sur le champ LIBELLE_TYPE.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_OBJET_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(IDENTIFIANT_OBJET)
    TABLESPACE G_ADT_INDX;

-- 7.6. Sur les champs FID_IDENTIFIANT et IDENTIFIANT_OBJET.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_FID_IDENTIFIANT_IDENTIFIANT_OBJET_IDX ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION(FID_IDENTIFIANT, IDENTIFIANT_OBJET)
    TABLESPACE G_ADT_INDX;

-- 7.7. Sur les champs OBJECTID, FID_IDENTIFIANT, IDENTIFIANT_OBJET.
CREATE INDEX TA_RTGE_ALTI_CONSULTATION_OBJECTID_FID_IDENTIFIANT_IDENTIFIANT_OBJET_IDX ON TA_RTGE_ALTI_CONSULTATION (OBJECTID, FID_IDENTIFIANT, IDENTIFIANT_OBJET) TABLESPACE G_ADT_INDX;


-- 8. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO ISOGEO_LEC;
GRANT INSERT ("GEOM") ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT UPDATE ("GEOM") ON G_GESTIONGEO.TA_RTGE_ALTI_CONSULTATION TO G_GESTIONGEO_MAJ;
GRANT SELECT ON SEQ_TA_RTGE_ALTI_CONSULTATION_OBJECTID TO G_GESTIONGEO_MAJ;

COMMIT;

/
