/*
TA_GG_FME_DECALAGE_ABSCISSE : La table TA_GG_FME_DECALAGE_ABSCISSE est utilisée par la chaine de traitement FME pour attribuer un décalage d'abcisse à certain CLA_CODE.
*/

-- 1. Creation de la table
CREATE TABLE G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE (
	OBJECTID NUMBER(38,0) DEFAULT G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID.NEXTVAL NOT NULL,
	FID_CLASSE NUMBER(38,0) NOT NULL,
	DECALAGE_ABSCISSE_D NUMBER(38,0) NOT NULL,
	DECALAGE_ABSCISSE_G NUMBER(38,0)
 );

-- 2. Les commentaires
COMMENT ON TABLE G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE IS 'Table utilisée par la chaîne d''intégration FME. Cette table permet d''attribuer à chaque type de ligne son décalage d''abscisse correspondant.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE.OBJECTID IS 'Clé primaire de la table auto-incrémentée.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE.FID_CLASSE IS 'Clé étrangère vers la table TA_GG_CLASSE afin de connaitre les classes des objets qui doivent être décalés.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE.DECALAGE_ABSCISSE_D IS 'Valeur du décalage d''abscisse vers la droite.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE.DECALAGE_ABSCISSE_G IS 'Valeur du décalage d''abscisse vers la gauche.';

-- 3. Les contraintes
-- 3.1. Contrainte de clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE
ADD CONSTRAINT TA_GG_FME_DECALAGE_ABSCISSE_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- 3.2. Contraintes de clé étrangère
ALTER TABLE G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE
ADD CONSTRAINT TA_GG_FME_DECALAGE_ABSCISSE_FID_CLASSE_FK
FOREIGN KEY("FID_CLASSE")
REFERENCES G_GESTIONGEO.TA_GG_CLASSE ("OBJECTID");

-- 4. Création des index sur les clés étrangères
CREATE INDEX G_GESTIONGEO."TA_GG_FME_DECALAGE_ABSCISSE_FID_CLASSE_IDX" ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE("FID_CLASSE")
    TABLESPACE G_ADT_INDX;

CREATE INDEX G_GESTIONGEO."TA_GG_FME_DECALAGE_ABSCISSE_DECALAGE_ABSCISSE_D_IDX" ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE ("DECALAGE_ABSCISSE_D") 
	TABLESPACE G_ADT_INDX;

CREATE INDEX G_GESTIONGEO."TA_GG_FME_DECALAGE_ABSCISSE_DECALAGE_ABSCISSE_G_IDX" ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE ("DECALAGE_ABSCISSE_G") 
	TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE TO G_GESTIONGEO_R;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID TO G_GESTIONGEO_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID TO G_GESTIONGEO_RW;

/

