-- 2.1. Creation de la table TA_RTGE_MUF_POINT_PTTOPO
-- Table qui permet de connaitre les lignes dont le start point croise un point topographique

-- 2.1.1. Creation de la table

CREATE TABLE G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO
	(
	OBJECTID_OBJET NUMBER(38,0), 
	OBJECTID_PTTOPO NUMBER(38,0),
	STATUT NUMBER(1)
	)
;


-- 2.1.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO IS 'Table qui permet de connaitre les lignes dont le start point croise un point topographique dans le cadre du calcul de la largeur des murs';


-- 2.1.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO.OBJECTID_OBJET IS 'Identifiant de la ligne considérée';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO.OBJECTID_PTTOPO IS 'Identifiant du point considéré';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO.STATUT IS 'Statut pour savoir si le point de départ ou d''arriver croise un point topo est un point de départ ou d''arriver';


-- 2.1.4. Contraintes

-- 2.1.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO
ADD CONSTRAINT TA_RTGE_MUF_POINT_PTTOPO_PK 
PRIMARY KEY (OBJECTID_OBJET, STATUT)
USING INDEX TABLESPACE "G_ADT_INDX";


-- 2.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_MUF_POINT_PTTOPO_OBJECTID_OBJET_IDX ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO(OBJECTID_OBJET) TABLESPACE G_ADT_INDX;

-- 2.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_MUF_POINT_PTTOPO_STATUT_IDX ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO(STATUT) TABLESPACE G_ADT_INDX;

-- 2.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_MUF_POINT_PTTOPO_OBJECTID_PTTOPO_IDX ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO(OBJECTID_PTTOPO) TABLESPACE G_ADT_INDX;

-- 2.1.7. Affection des droits de lecture
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO TO G_ADMIN_SIG;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO TO ISOGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO TO G_GESTIONGEO_LEC;
GRANT SELECT, UPDATE, DELETE, INSERT ON G_GESTIONGEO.TA_RTGE_MUF_POINT_PTTOPO TO G_GESTIONGEO_MAJ;

/
