-- Creation d'une table de relation entre les table TA_RTGE_POINT et TA_RTGE_POINT_INTEGRATION pour relier chaque entité intégrée avec son entité copiée.

CREATE TABLE TA_RTGE_OBJECTID
	(
		OBJECTID NUMBER(38,0),
		OBJECTID_ELEMENT_INTEGRE NUMBER(38,0),
		OBJECTID_ELEMENT_COPIE NUMBER(38,0),
		FID_TYPE_ENTITE NUMBER(38,0),
	)
;


-- 2.1.2. Commentaire des tables
COMMENT ON TABLE G_GESTIONGEO.TA_RTGE_OBJECTID IS 'Table utilisée pour relier chaque entité intégrée avec son entité copiée.';

-- 2.1.3. Commentaire de la colonne
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_OBJECTID.OBJECTID IS 'Cle primaire de la table.';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_OBJECTID.OBJECTID_ELEMENT_INTEGRE IS 'Identifiant de l''objet dans les tables d''integration.';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_OBJECTID.OBJECTID_ELEMENT_COPIE IS 'Identifiant de l''objet dans les tables de production.';
COMMENT ON COLUMN G_GESTIONGEO.TA_RTGE_OBJECTID.FID_TYPE_ENTITE IS 'Type de l''objet: point ou lineaire.';


-- 2.2.4. Contraintes

-- 2.2.4.1. Clé primaire
ALTER TABLE G_GESTIONGEO.TA_RTGE_OBJECTID
ADD CONSTRAINT TA_RTGE_OBJECTID_PK 
PRIMARY KEY (OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";


-- 2.2.4.2. Clés étrangères

-- 2.2.4.2.1. CHAMP FID_IDENTIFIANT_TYPE VERS TA_GG_CLASSE
ALTER TABLE G_GESTIONGEO.TA_RTGE_OBJECTID
ADD CONSTRAINT TA_RTGE_OBJECTID_FID_TYPE_ENTITE_FK 
FOREIGN KEY (FID_TYPE_ENTITE)
REFERENCES G_GESTIONGEO.TA_GG_LIBELLE(OBJECTID);