/*
TA_GG_LIBELLE_LONG: Contient les libelles longs qui caractérises les éléments contenus dans le schéma G_GESTIONGEO.
*/

-- 1. TA_GG_LIBELLE_LONG
-- 1.1. Création de la table
CREATE TABLE G_GESTIONGEO.TA_GG_LIBELLE_LONG(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    valeur VARCHAR2(255)
);

-- 1.2. Création des commentaires
COMMENT ON TABLE G_GESTIONGEO.TA_GG_LIBELLE_LONG IS 'Table regroupant les libelles longs pouvant être pris par les libelles du schema G_GESTIONGEO.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_LIBELLE_LONG.objectid IS 'Clé primaire de la table TA_GG_LIBELLE_LONG.';
COMMENT ON COLUMN G_GESTIONGEO.TA_GG_LIBELLE_LONG.valeur IS 'Valeur pouvant être prises par les libelles longs du schema G_GESTIONGEO.';

-- 1.3. Création de la clé primaire
ALTER TABLE G_GESTIONGEO.TA_GG_LIBELLE_LONG
ADD CONSTRAINT TA_GG_LIBELLE_LONG_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 1.4. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GESTIONGEO.TA_GG_LIBELLE_LONG TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.TA_GG_LIBELLE_LONG TO G_GESTIONGEO_LEC;