-- 1.3. Insertion des données dans la table TA_PTTOPO_INTEGRATION
MERGE INTO G_GESTIONGEO.TA_PTTOPO_INTEGRATION a
USING
	(
		SELECT
			ALT AS ALTITUDE,
			MAT AS MATRICULE,
			TO_NUMBER(ID_DOS) AS NUMERO_DOSSIER,
			OBJECTID AS OBJECTID,
			GEOM AS GEOM
		FROM
			G_GESTIONGEO.TEMP_PTTOPO
        WHERE ID_DOS NOT IN (44780)
	)b
ON(a.OBJECTID = b.OBJECTID)
WHEN NOT MATCHED THEN INSERT (a.ALTITUDE, a.MATRICULE, a.NUMERO_DOSSIER, a.OBJECTID, a.GEOM)
VALUES (b.ALTITUDE, b.MATRICULE, b.NUMERO_DOSSIER, b.OBJECTID, b.GEOM)
;

/
