-- Insertion des données dans la table TA_RTGE_MUF_END_POINT

MERGE INTO G_GESTIONGEO.TA_RTGE_MUF_END_POINT a
USING
	(
	SELECT
		a.OBJECTID AS OBJECTID,
		a.FID_NUMERO_DOSSIER AS FID_NUMERO_DOSSIER,
		SDO_LRS.GEOM_SEGMENT_END_PT(SDO_CS.MAKE_2D(SDO_LRS.CONVERT_TO_LRS_GEOM(a.geom))) as geom
	FROM
	    TA_RTGE_LINEAIRE_INTEGRATION a
	WHERE
	    a.FID_IDENTIFIANT_TYPE = 703
	) b
ON(a.OBJECTID = b.OBJECTID
AND a.FID_NUMERO_DOSSIER = b.FID_NUMERO_DOSSIER)
WHEN NOT MATCHED THEN 
INSERT (a.OBJECTID, a.FID_NUMERO_DOSSIER, a.GEOM)
VALUES (b.OBJECTID, b.FID_NUMERO_DOSSIER, b.GEOM)
;

COMMIT;

/
