-- 1.2. Insertion des données dans la table TA_RTGE_LINEAIRE_INTEGRATION
MERGE INTO G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION a
USING
	(
		SELECT
		    a.OBJECTID AS OBJECTID,
		    a.CLA_INU AS IDENTIFIANT_TYPE,
		    TO_NUMBER(a.GEO_REF) AS NUMERO_DOSSIER,
		    a.GEOM AS GEOM,
		    a.GEO_LIG_OFFSET_D AS DECALAGE_DROITE,
		    a.GEO_LIG_OFFSET_G AS DECALAGE_GAUCHE,
		    b.OBJECTID AS FID_PNOM_CREATION,
		    a.GEO_DS AS DATE_CREATION,
		    c.OBJECTID AS FID_PNOM_MODIFICATION,
		    a.GEO_DM AS DATE_MODIFICATION
		FROM
		    G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS a
		    LEFT JOIN G_GESTIONGEO.TA_GG_AGENT b ON TRIM(a.GEO_NMS) = TRIM(b.PNOM)
		    LEFT JOIN G_GESTIONGEO.TA_GG_AGENT c ON TRIM(a.GEO_NMN) = TRIM(c.PNOM)
		WHERE
		    a.GEO_ON_VALIDE = 0
		    AND a.GEO_REF IN (SELECT a.NUMERO_DOSSIER FROM TA_RTGE_POINT_INTEGRATION a)
	) b
ON(a.OBJECTID = b.OBJECTID)
WHEN NOT MATCHED THEN INSERT (a.OBJECTID, a.IDENTIFIANT_TYPE, a.NUMERO_DOSSIER, a.GEOM, a.DECALAGE_DROITE, a.DECALAGE_GAUCHE, a.FID_PNOM_CREATION, a.DATE_CREATION, a.FID_PNOM_MODIFICATION, a.DATE_MODIFICATION)
VALUES (b.OBJECTID, b.IDENTIFIANT_TYPE, b.NUMERO_DOSSIER, b.GEOM, b.DECALAGE_DROITE, b.DECALAGE_GAUCHE, b.FID_PNOM_CREATION, b.DATE_CREATION, b.FID_PNOM_MODIFICATION, b.DATE_MODIFICATION)
;

/