-- 2.1. Insertion des données dans la table TA_RTGE_POINT_PRODUCTION
MERGE INTO G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION a
USING
	(
		SELECT
			a.OBJECTID AS OBJECTID,
			a.CLA_INU AS FID_IDENTIFIANT_TYPE,
			TO_NUMBER(a.GEO_REF) AS FID_NUMERO_DOSSIER,
			SDO_GEOMETRY(3001, 2154,
                SDO_POINT_TYPE(a.GEOM.sdo_point.x, a.GEOM.sdo_point.y, COALESCE(a.GEOM.sdo_point.z,0)),
                NULL, NULL) AS GEOM,
		    CAST(TRIM(a.GEO_TEXTE) AS VARCHAR2 (2048 BYTE)) AS TEXTE,
			a.GEO_POI_LN/100 AS LONGUEUR,
			a.GEO_POI_LA/100 AS LARGEUR,
			a.GEO_POI_AG_ORIENTATION AS ORIENTATION,
			a.GEO_POI_HA/100 AS HAUTEUR,
			a.GEO_POI_AG_INCLINAISON AS INCLINAISON,
			b.OBJECTID AS FID_PNOM_CREATION,
			a.GEO_DS AS DATE_CREATION,
			c.OBJECTID AS FID_PNOM_MODIFICATION,
			a.GEO_DM AS DATE_MODIFICATION,
			a.OBJECTID AS FID_IDENTIFIANT_OBJET_INTEGRATION
		FROM
			G_GESTIONGEO.TEMP_TA_POINT_TOPO_F a
		    LEFT JOIN G_GESTIONGEO.TA_GG_AGENT b ON TRIM(LOWER(a.GEO_NMS)) = TRIM(LOWER(b.PNOM))
		    LEFT JOIN G_GESTIONGEO.TA_GG_AGENT c ON TRIM(LOWER(a.GEO_NMN)) = TRIM(LOWER(c.PNOM))
		WHERE
			a.GEO_ON_VALIDE =0
            AND a.GEOM IS NOT NULL
	) b
ON(a.OBJECTID = b.OBJECTID)
WHEN NOT MATCHED THEN INSERT (a.OBJECTID, a.FID_IDENTIFIANT_TYPE, a.FID_NUMERO_DOSSIER, a.GEOM, a.TEXTE, a.LONGUEUR, a.LARGEUR, a.ORIENTATION, a.HAUTEUR, a.INCLINAISON, a.FID_PNOM_CREATION, a.DATE_CREATION, a.FID_PNOM_MODIFICATION, a.DATE_MODIFICATION, a.FID_IDENTIFIANT_OBJET_INTEGRATION)
VALUES(b.OBJECTID, b.FID_IDENTIFIANT_TYPE, b.FID_NUMERO_DOSSIER, b.GEOM, b.TEXTE, b.LONGUEUR, b.LARGEUR, b.ORIENTATION, b.HAUTEUR, b.INCLINAISON, b.FID_PNOM_CREATION, b.DATE_CREATION, b.FID_PNOM_MODIFICATION, b.DATE_MODIFICATION, b.FID_IDENTIFIANT_OBJET_INTEGRATION)
;

/
