-- Initialisation de la table G_GESTIONGEO.TA_RTGE_MUF_STATUT

MERGE INTO G_GESTIONGEO.TA_RTGE_MUF_STATUT a
USING
	(
	WITH MUF_RELEVE AS
		(
		    SELECT
		        DISTINCT a.OBJECTID_LIGNE AS OBJECTID,
		        2 AS STATUT
		    FROM
		        TA_RTGE_MUF_START_POINT_PTTOPO a INNER JOIN TA_RTGE_MUF_END_POINT_PTTOPO b on a.OBJECTID_LIGNE = b.OBJECTID_LIGNE
		),
		MUF_PARRALLELE AS
		(
		    SELECT
		        a.OBJECTID_LIGNE AS OBJECTID,
		        1 AS STATUT
		    FROM
		        TA_RTGE_MUF_START_POINT_PTTOPO a
		    WHERE
		        a.OBJECTID_LIGNE NOT IN (SELECT a.OBJECTID_LIGNE FROM TA_RTGE_MUF_END_POINT_PTTOPO a)
		    UNION 
		    SELECT
		        a.OBJECTID_LIGNE AS OBJECTID,
		        1 AS STATUT
		    FROM
		        TA_RTGE_MUF_END_POINT_PTTOPO a
		    WHERE
		        a.OBJECTID_LIGNE NOT IN (SELECT a.OBJECTID_LIGNE FROM TA_RTGE_MUF_START_POINT_PTTOPO a)
		),
		MUF_CONSTRUIT AS
		(
		    SELECT
		    	DISTINCT a.OBJECTID AS OBJECTID,
		    	0 AS STATUT
		    FROM
		        TA_RTGE_MUF_START_POINT a
		    WHERE
		    	OBJECTID NOT IN (SELECT OBJECTID FROM MUF_RELEVE)
		    	AND OBJECTID NOT IN (SELECT OBJECTID FROM MUF_PARRALLELE)
        )
	SELECT
		a.OBJECTID,
		A.STATUT
	FROM
		MUF_RELEVE a
	UNION
	SELECT
		a.OBJECTID,
		A.STATUT
	FROM
		MUF_PARRALLELE a
	UNION
	SELECT
		a.OBJECTID,
		A.STATUT
	FROM
		MUF_CONSTRUIT a
	)b
ON(a.OBJECTID = b.OBJECTID
AND a.STATUT = b.STATUT)
WHEN NOT MATCHED THEN 
INSERT(a.OBJECTID, a.STATUT)
VALUES(b.OBJECTID, b.STATUT)
;

COMMIT;

/
