-- 1.3. Insertion des données dans la table TA_PTTOPO_INTEGRATION
MERGE INTO G_GESTIONGEO.TA_PTTOPO_INTEGRATION a
USING
	(
		SELECT
			a.ALT AS ALT,
			a.MAT AS MAT,
			TO_NUMBER(a.ID_DOS) AS FID_NUMERO_DOSSIER,
			a.OBJECTID AS OBJECTID,
			a.GEOM AS GEOM
		FROM
			G_GESTIONGEO.TEMP_PTTOPO a
        WHERE a.ID_DOS IN (SELECT a.OBJECTID FROM G_GESTIONGEO.TA_GG_DOSSIER a)
	)b
ON(a.OBJECTID = b.OBJECTID)
WHEN NOT MATCHED THEN INSERT (a.ALT, a.MAT, a.FID_NUMERO_DOSSIER, a.OBJECTID, a.GEOM)
VALUES (b.ALT, b.MAT, b.FID_NUMERO_DOSSIER, b.OBJECTID, b.GEOM)
;

/
