/*
Code permettant d'insérer les données gestiongeo des tables temporaires dans les tables finales suite aux corrections des données.
*/

-- 1. TA_GG_SOURCE
INSERT INTO G_GESTIONGEO.TA_GG_SOURCE(SRC_ID, SRC_LIBEL, SRC_VAL)
SELECT
	SRC_ID, 
	SRC_LIBEL, 
	SRC_VAL
FROM
	G_GESTIONGEO.TEMP_TA_GG_SOURCE;

-- 2. TA_GG_FAMILLE
INSERT INTO G_GESTIONGEO.TA_GG_FAMILLE(FAM_ID, FAM_LIB, FAM_VAL, FAM_LIB_SMALL)
SELECT
	FAM_ID, 
	FAM_LIB, 
	FAM_VAL,
	FAM_LIB_SMALL
FROM
	G_GESTIONGEO.TEMP_TA_GG_FAMILLE;

-- 3. TA_GG_ETAT
INSERT INTO G_GESTIONGEO.TA_GG_ETAT(ETAT_ID, ETAT_LIB, ETAT_AFF, ETAT_LIB_SMALL, ETAT_SMALL)
SELECT 
	ETAT_ID, 
	ETAT_LIB, 
	ETAT_AFF, 
	ETAT_LIB_SMALL, 
	ETAT_SMALL
FROM
	G_GESTIONGEO.TEMP_TA_GG_ETAT;

-- 4. TA_GG_GEO
-- 4.1. Désactivation de la clé étrangère TA_GG_GEO_ID_DOS_FK
ALTER TABLE G_GESTIONGEO.TA_GG_GEO
DISABLE CONSTRAINT TA_GG_GEO_ID_DOS_FK ;

-- 4.2. Insertion des données
INSERT INTO G_GESTIONGEO.TA_GG_GEO(ID_GEOM, ID_DOS, ETAT_ID, GEOM, DOS_NUM)
SELECT
	ID_GEOM, 
	ID_DOS, 
	ETAT_ID, 
	GEOM,
	DOS_NUM
FROM
	G_GESTIONGEO.TEMP_TA_GG_GEO;

-- 5. TA_GG_DOSSIER
-- 5.1. Insertiion des données
INSERT INTO G_GESTIONGEO.TA_GG_DOSSIER(ID_DOS, SRC_ID, ETAT_ID, USER_ID, FAM_ID, DOS_DC, DOS_PRECISION, DOS_DMAJ, DOS_RQ, DOS_DT_FIN, DOS_PRIORITE, DOS_IDPERE, DOS_DT_DEB_TR, DOS_DT_FIN_TR, DOS_DT_CMD_SAI, DOS_INSEE, DOS_VOIE, DOS_MAO, DOS_ENTR, DOS_URL_FILE, ORDER_ID, DOS_NUM, DOS_OLD_ID, DOS_DT_DEB_LEVE, DOS_DT_FIN_LEVE, DOS_DT_PREV)
SELECT
	ID_DOS, 
	SRC_ID, 
	ETAT_ID, 
	USER_ID, 
	FAM_ID, 
	DOS_DC, 
	DOS_PRECISION, 
	DOS_DMAJ, 
	DOS_RQ, 
	DOS_DT_FIN, 
	DOS_PRIORITE, 
	DOS_IDPERE, 
	DOS_DT_DEB_TR, 
	DOS_DT_FIN_TR, 
	DOS_DT_CMD_SAI, 
	DOS_INSEE, 
	DOS_VOIE, 
	DOS_MAO, 
	DOS_ENTR, 
	DOS_URL_FILE, 
	ORDER_ID, 
	DOS_NUM, 
	DOS_OLD_ID, 
	DOS_DT_DEB_LEVE, 
	DOS_DT_FIN_LEVE, 
	DOS_DT_PREV	
FROM
	G_GESTIONGEO.TEMP_TA_GG_DOSSIER;

-- 5.2. Réactivation de la contrainte de clé étrangère de TA_GG_GEO
ALTER TABLE G_GESTIONGEO.TA_GG_GEO
ENABLE CONSTRAINT TA_GG_GEO_ID_DOS_FK ;