GRANT SELECT ON G_GEO.TA_FAMILLE TO G_GESTIONGEO;
/
GRANT SELECT ON G_GEO.TA_FAMILLE_LIBELLE TO G_GESTIONGEO;
/
GRANT SELECT ON G_GEO.TA_LIBELLE_LONG TO G_GESTIONGEO;
/
GRANT SELECT, REFERENCES ON G_GEO.TA_LIBELLE TO G_GESTIONGEO;
/