-- décompte des dossiers par communes, type et état
CREATE VIEW GEO.V_ACQ_GG_STAT_COM AS
SELECT
  d.NOM,
  c.FAM_LIB,
  e.ETAT_LIB,
  COUNT(c.FAM_LIB) AS NBR_DOSSIER
FROM GEO.LM_COMMUNES d, GEO.TA_GG_GEO a
JOIN GEO.TA_GG_DOSSIER b ON b.ID_DOS = a.ID_DOS
JOIN GEO.TA_GG_FAMILLE c ON c.FAM_ID = b.FAM_ID
JOIN GEO.TA_GG_ETAT e ON a.ETAT_ID = e.ETAT_ID
WHERE SDO_CONTAINS(d.geom, SDO_GEOM.SDO_CENTROID(a.geom, 2)) = 'TRUE'
GROUP BY d.NOM, c.FAM_LIB, e.ETAT_LIB
ORDER BY d.NOM, c.FAM_LIB, e.ETAT_LIB;

-- décompte des dossiers par zones d'agents, type et état
CREATE VIEW GEO.V_ACQ_GG_STAT_ZONE AS
SELECT
  d.NOM_AGENT,
  c.FAM_LIB,
  e.ETAT_LIB,
  COUNT(c.FAM_LIB) AS NBR_DOSSIER
FROM
  GEO.TA_ACQ_GG_ZONAGE d,
  GEO.TA_GG_GEO a
JOIN GEO.TA_GG_DOSSIER b ON b.ID_DOS = a.ID_DOS
JOIN GEO.TA_GG_FAMILLE c ON c.FAM_ID = b.FAM_ID
JOIN GEO.TA_GG_ETAT e ON a.ETAT_ID = e.ETAT_ID
WHERE SDO_CONTAINS(d.geom, SDO_GEOM.SDO_CENTROID(a.geom, 2)) = 'TRUE'
GROUP BY d.NOM_AGENT, c.FAM_LIB, e.ETAT_LIB
ORDER BY d.NOM_AGENT, c.FAM_LIB, e.ETAT_LIB;
