-- nombre de dossiers clôturées par années
SELECT
  EXTRACT(YEAR FROM DOS_DT_FIN) AS ANNEE,
  COUNT(TA_GG_DOSSIER.ID_DOS)
FROM GEO.TA_GG_DOSSIER
WHERE
  FAM_ID != 2
GROUP BY EXTRACT(YEAR FROM DOS_DT_FIN)
ORDER BY ANNEE;

-- nombre de dossiers ouverts par années
SELECT
  EXTRACT(YEAR FROM DOS_DC) AS ANNEE,
  COUNT(TA_GG_DOSSIER.ID_DOS)
FROM GEO.TA_GG_DOSSIER
WHERE
  FAM_ID != 2
GROUP BY EXTRACT(YEAR FROM DOS_DC)
ORDER BY ANNEE;

-- nombre de dossiers clôturées sur une semaine
SELECT
  COUNT(TA_GG_DOSSIER.ID_DOS)
FROM GEO.TA_GG_DOSSIER
WHERE
  FAM_ID != 2
	AND	DOS_DT_FIN > = (SELECT SYSDATE - 7 FROM dual)
	AND EXTRACT(YEAR FROM DOS_DT_FIN) = EXTRACT(YEAR FROM sysdate)
	AND EXTRACT(MONTH FROM DOS_DT_FIN) = EXTRACT(MONTH FROM sysdate)

-- nombre de dossiers ouverts sur une semaine
SELECT
  EXTRACT(YEAR FROM DOS_DC) AS ANNEE,
  COUNT(TA_GG_DOSSIER.ID_DOS)
FROM GEO.TA_GG_DOSSIER
FROM GEO.TA_GG_DOSSIER
WHERE
  FAM_ID != 2
	AND	DOS_DC > = (SELECT SYSDATE - 7 FROM dual)
	AND EXTRACT(YEAR FROM DOS_DC) = EXTRACT(YEAR FROM sysdate)
	AND EXTRACT(MONTH FROM DOS_DC) = EXTRACT(MONTH FROM sysdate)

-- liste les dossiers clôturés mais sans date de fin indiquée
SELECT
  ID_DOS,
  DOS_NUM,
  EXTRACT(YEAR FROM DOS_DC) AS ANNEE_CREATION,
  EXTRACT(YEAR FROM DOS_DT_FIN) AS ANNEE_FERMETURE,
  DOS_DMAJ
FROM GEO.TA_GG_DOSSIER
WHERE
  FAM_ID != 2
  AND DOS_DT_FIN IS NULL
  AND ETAT_ID = 9
  AND EXTRACT(YEAR FROM DOS_DC) != 2016

-- nombre de dossiers par famille
SELECT
  FAM_ID
	COUNT(ID_DOS)
FROM GEO.TA_GG_DOSSIER
GROUP BY FAM_ID

-- nombre de dossiers par états
SELECT
	ETAT_ID,
	COUNT(ID_DOS)
FROM GEO.TA_GG_DOSSIER
GROUP BY ETAT_ID


UPDATE GEO.TA_GG_DOSSIER
SET DOS_DT_FIN = DOS_DMAJ
WHERE
	ETAT_ID = 9
	AND DOS_DT_FIN IS NULL
	AND FAM_ID !=2
	AND EXTRACT(YEAR FROM DOS_DMAJ) = 2018;

1	Plan de récolement
2	Investigation Complémentaire
3	Maj Carto
