-- vérifie la validité d'une géométrie
-- renvoit un boolean
SELECT
  SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT("GEOM", 0.05)
FROM "GEO"."TA_SUR_TOPO_G"
WHERE OBJECTID = 125949


SELECT
  COUNT("OBJECTID")
FROM GEO.TA_SUR_TOPO_G
WHERE
  "GEO_ON_VALIDE" = 0
  AND SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT("GEOM", 0.05) = 'FALSE';

  SELECT
    COUNT("OBJECTID")
  FROM GEO.TA_SUR_TOPO_G
  WHERE
    "GEO_ON_VALIDE" = 0
    AND GEOM IS NULL;

SELECT
  OBJECTID,
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) AS CONTEXT,
  GEOM
FROM GEO.TA_SUR_TOPO_G
WHERE
  "GEO_ON_VALIDE" = 0 AND
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) <> 'TRUE';


SELECT
  OBJECTID,
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) AS CONTEXT,
  SDO_GTYPE(GEOM) AS GTYPE
FROM GEO.TA_SUR_TOPO_G
WHERE
  "GEO_ON_VALIDE" = 0 AND
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) = 'NULL';


SELECT
  OBJECTID,
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) AS CONTEXT,
  SDO_UTIL.TO_WKTGEOMETRY(SDO_UTIL.EXTRACT(GEOM, 0)) AS WKTGEOM
FROM GEO.TA_SUR_TOPO_G
WHERE
  OBJECTID = 369827

SDO_GEOM.SDO_MBR(GEOM, 2)

-- validité des géométries ta_gg_geo
SELECT
  a.ID_GEOM,
  a.ID_DOS,
  b.DOS_NUM,
  c.NOMUSU,
  SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) AS CONTEXT,
  replace(replace(b.DOS_RQ, CHR(13)), CHR(10), ' - ') AS COMMENTAIRE,
  b.DOS_DC AS creation,
  GEOM
FROM GEO.TA_GG_GEO a
JOIN GEO.TA_GG_DOSSIER b ON b.ID_DOS = a.ID_DOS
JOIN ANNU.POPULATIONS c ON c.CODPOP = b.USER_ID
WHERE
  MDSYS.SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) != '13028'
ORDER BY DOS_NUM;
