-- Code pour créer les indexes des tables suite à l'insertion des données:


-- G_GESTIONGEO.TA_IC_LINEAIRE

-- 2.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_IC_LINEAIRE_SIDX
ON G_GESTIONGEO.TA_IC_LINEAIRE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 2.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_IC_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_IC_LINEAIRE_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_IC_LINEAIRE_LOG

-- 3.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_IC_LINEAIRE_LOG_SIDX
ON G_GESTIONGEO.TA_IC_LINEAIRE_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_IC_LINEAIRE_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_IC_LINEAIRE_LOG_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_IC_LINEAIRE_LOG(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_RTGE_LINEAIRE

-- 2.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 2.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;


-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 3.2.6.4. Creation d'un index sur le champ FID_IDENTIFIANT_OBJET_INTEGRATION
CREATE INDEX TA_RTGE_LINEAIRE_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE(FID_IDENTIFIANT_OBJET_INTEGRATION) TABLESPACE G_ADT_INDX;


-- TA_RTGE_LINEAIRE_LOG

-- 3.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_LOG_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_LINEAIRE_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_LOG_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_LOG(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_OCSMEL_LINEAIRE

-- 1.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCSMEL_LINEAIRE_SIDX
ON G_GESTIONGEO.TA_OCSMEL_LINEAIRE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_OCSMEL_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_OCSMEL_LINEAIRE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;


-- TA_RTGE_LINEAIRE_INTEGRATION

-- 1.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 1.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 1.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_RTGE_LINEAIRE_INTEGRATION

-- 3.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_LOG_SIDX
ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.2.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_LINEAIRE_INTEGRATION_LOG_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_LOG(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_OCSMEL_LINEAIRE_LOG

-- 3.2.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCSMEL_LINEAIRE_LOG_SIDX
ON G_GESTIONGEO.TA_OCSMEL_LINEAIRE_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.2.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_OCSMEL_LINEAIRE_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_OCSMEL_LINEAIRE_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;


-- TA_RTGE_POINT

-- 2.1.6.1 Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_POINT_SIDX
ON G_GESTIONGEO.TA_RTGE_POINT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 2.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_POINT_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 2.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_POINT_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_POINT(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 2.1.6.4. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_POINT_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX ON G_GESTIONGEO.TA_RTGE_POINT(FID_IDENTIFIANT_OBJET_INTEGRATION) TABLESPACE G_ADT_INDX;


-- TA_RTGE_POINT_LOG

-- 3.1.6.1. Creation de l'index sur le champ GEOM
CREATE INDEX TA_RTGE_POINT_LOG_SIDX
ON G_GESTIONGEO.TA_RTGE_POINT_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_POINT_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_POINT_LOG_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_POINT_LOG(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_RTGE_POINT_INTEGRATOIN

-- 1.1.6.1. Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_POINT_INTEGRATION_SIDX
ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 1.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_POINT_INTEGRATION_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 1.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_POINT_INTEGRATION_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_RTGE_POINT_INTEGRATION_LOG

-- 3.1.6.1. Creation de l'index sur le champ GEOM
CREATE INDEX TA_RTGE_POINT_INTEGRATION_LOG_SIDX
ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_LOG(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 3.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_POINT_INTEGRATION_LOG_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_LOG(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 3.1.6.3. Creation d'un index sur le champ numero dossier
CREATE INDEX TA_RTGE_POINT_INTEGRATION_LOG_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_LOG(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;


-- TA_RTGE_SURFACE

-- 2.1.6.1 Création de l'index spatial sur le champ geom
CREATE INDEX TA_RTGE_SURFACE_SIDX
ON G_GESTIONGEO.TA_RTGE_SURFACE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 2.1.6.2. Création d'un index sur le champ FID_IDENTIFIANT_TYPE
CREATE INDEX TA_RTGE_SURFACE_FID_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_IDENTIFIANT_TYPE) TABLESPACE G_ADT_INDX;

-- 2.1.6.3. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_SURFACE_FID_NUMERO_DOSSIER_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_NUMERO_DOSSIER) TABLESPACE G_ADT_INDX;

-- 2.1.6.4. Creation d'un index sur le champ FID_NUMERO_DOSSIER
CREATE INDEX TA_RTGE_SURFACE_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX ON G_GESTIONGEO.TA_RTGE_SURFACE(FID_IDENTIFIANT_OBJET_INTEGRATION) TABLESPACE G_ADT_INDX;

/
