--Requete permettant la mise à jour du numero de dossier des elements (GEO_REF)
/*

METHODOLOGIE

1. Créer un dossier pour les elements avec des numéros de dossier inexistant (IC et RECOL) -> 1
2. Mise à jour 1 des GEO_REF des tables GPS qui ne commencent ni par REC ni IC
3. Mise à jour du GEO_REF pour retirer TOPO les caractères alphabetiques
4. Mise à jour des tables de log

*/

-- 1. Gestion de la table TA_POINT_TOPO_GPS.
UPDATE G_GESTIONGEO.TEMP_PTTOPO
SET ID_DOS = '1'
WHERE ID_DOS NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 2. Mise à jour des numéros de dossier des tables TA_LIG_TOPO_G et TA_LIG_TOPO_GPS

-- 2.1. TA_POINT_TOPO_GPS
MERGE INTO G_GESTIONGEO.TEMP_TA_POINT_TOPO_F a
USING
	(
		SELECT
			a.OBJECTID AS OBJECTID,
			a.GEO_REF AS GEO_REF
		FROM
			G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
	)b
ON(a.OBJECTID = b.OBJECTID)
WHEN MATCHED THEN
UPDATE SET a.GEO_REF = b.GEO_REF
;

-- 2.2. TA_POINT_TOPO_GPS
MERGE INTO G_GESTIONGEO.TEMP_TA_LIG_TOPO_F a
USING
	(
		SELECT
			a.OBJECTID AS OBJECTID,
			a.GEO_REF AS GEO_REF
		FROM
			G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS_BACKUP
	)b
ON(a.OBJECTID = b.OBJECTID)
WHEN MATCHED THEN
UPDATE SET a.GEO_REF = b.GEO_REF
;

-- 2.3. TA_POINT_TOPO_GPS
MERGE INTO G_GESTIONGEO.TEMP_TA_LIG_TOPO_F a
USING
	(
		SELECT
			a.OBJECTID AS OBJECTID,
			a.GEO_REF AS GEO_REF
		FROM
			G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1
	)b
ON(a.OBJECTID = b.OBJECTID)
WHEN MATCHED THEN
UPDATE SET a.GEO_REF = b.GEO_REF
;


-- 3. Gestion de la table TA_POINT_TOPO_GPS.

-- 3.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.
UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 3.2. Mise à 1 des GEO_REF à NULL
UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 3.3. Suppression des caractères 'IC' des GEO_REF
UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 3.4. suppression des caractères 'REC' des GEO_REF 
UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 3.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER
UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_GPS
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 4. Gestion de la table TA_LIG_TOPO_GPS.

-- 4.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 4.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 4.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 4.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 4.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_GPS
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 5. Gestion de la table TA_POINT_TOPO_FIN

-- 5.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 5.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 5.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 5.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 5.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 6. Gestion de la table TA_POINT_TOPO_FIN

-- 6.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 6.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 6.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 6.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 6.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 7. Gestion de la table TA_POINT_TOPO_FIN

-- 7.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 7.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 7.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 7.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 7.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);

-- 8. Gestion de la table TA_POINT_TOPO_FIN

-- 8.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G_LOG
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 8.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G_LOG
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 8.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G_LOG
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 8.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G_LOG
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 8.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_SUR_TOPO_G_LOG
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);

-- 9. Gestion de la table TA_POINT_TOPO_F_LOG
MERGE INTO G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG a
USING
	(
		SELECT
			a.OBJECTID AS FID_IDENTIFIANT,
			a.GEO_REF AS GEO_REF
		FROM
			G_GESTIONGEO.TEMP_TA_POINT_TOPO_F a
	)b
ON(a.FID_IDENTIFIANT = b.FID_IDENTIFIANT)
WHEN MATCHED THEN
UPDATE SET a.GEO_REF = b.GEO_REF
;


-- 10. Gestion de la table TA_LIG_TOPO_F_LOG
MERGE INTO G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG a
USING
	(
		SELECT
			a.OBJECTID AS FID_IDENTIFIANT,
			a.GEO_REF AS GEO_REF
		FROM
			G_GESTIONGEO.TEMP_TA_LIG_TOPO_F
	)b
ON(a.FID_IDENTIFIANT = b.FID_IDENTIFIANT)
WHEN MATCHED THEN
UPDATE SET a.GEO_REF = b.GEO_REF
;

-- 11. Gestion de la table TA_POINT_TOPO_F_LOG

-- 11.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 11.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 11.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 11.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 11.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_POINT_TOPO_F_LOG
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);


-- 12. Gestion de la table TA_POINT_TOPO_F_LOG

-- 12.1. Mise à 1 des GEO_REF qui ne commencent ni par REC ni par IC.

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG
SET GEO_REF = '1'
WHERE 
	GEO_REF NOT LIKE 'IC_%'
    AND GEO_REF NOT LIKE 'REC_%';

-- 12.2. Mise à 1 des GEO_REF à NULL

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG
SET GEO_REF = '1'
WHERE GEO_REF IS NULL;

-- 12.3. Suppression des caractères 'IC' des GEO_REF

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG
SET GEO_REF = REPLACE(GEO_REF,'IC_','')
WHERE GEO_REF LIKE 'IC_%';

-- 12.4. suppression des caractères 'REC' des GEO_REF 

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG
SET GEO_REF = REPLACE(GEO_REF,'REC_','')
WHERE GEO_REF LIKE 'REC_%';

-- 12.5. Mise à 1 des GEO_REF non présents dans G_GESTIONGEO.TEMP_TA_GG_DOSSIER

UPDATE G_GESTIONGEO.TEMP_TA_LIG_TOPO_F_LOG
SET GEO_REF = '1'
WHERE GEO_REF NOT IN (SELECT OBJECTID FROM TA_GG_DOSSIER);

/
