/*
correction de l'erreur ORA-13028 provoquée par Dynmap lors de la création d'un nouveau polygone

# INCORRECT :
MDSYS.SDO_GEOMETRY(2003, 2154, NULL,
MDSYS.SDO_ELEM_INFO_ARRAY(1, 2, 1)

# CORRECT :
MDSYS.SDO_GEOMETRY(2003, 2154, NULL,
MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1)

*/

-- décompte
SELECT
  ID_GEOM
FROM "GEO"."TA_GG_GEO"
WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(GEOM,.005) = '13028';

-- correction
UPDATE "GEO"."TA_GG_GEO" t
SET t.geom.SDO_ELEM_INFO = MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1)
WHERE
 SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(t.GEOM, 0.005) = '13028'
 AND SUBSTR(TO_CHAR("DOS_NUM"),1,2) = '19';
