-- Suppression des données des tables nécessaires au rangement des communes

-- 1. Suppression des tables pivots
DELETE FROM G_GEO.TA_FAMILLE_LIBELLE;
COMMIT;
DELETE FROM G_GEO.TA_IDENTIFIANT_COMMUNE;
COMMIT;
DELETE FROM G_GEO.TA_IDENTIFIANT_ZONE_ADMINISTRATIVE;
COMMIT;
DELETE FROM G_GEO.TA_METADONNEE_RELATION_ORGANISME;
COMMIT;
DELETE FROM G_GEO.TA_METADONNEE;
COMMIT;

-- 2. Supression des tables contenants des clés étrangères
DELETE FROM G_GEO.TA_CODE;
COMMIT;
DELETE FROM G_GEO.TA_ZONE_ADMINISTRATIVE;
COMMIT;
DELETE FROM G_GEO.TA_COMMUNE;
COMMIT;
DELETE FROM G_GEO.TA_LIBELLE;
COMMIT;

-- 3. Suppression des tables ne contenant aucune clé étrangère
DELETE FROM G_GEO.TA_FAMILLE;
COMMIT;
DELETE FROM G_GEO.TA_NOM;
COMMIT;
DELETE FROM G_GEO.TA_LIBELLE_LONG;
COMMIT;
DELETE FROM G_GEO.TA_ORGANISME;
COMMIT;
DELETE FROM G_GEO.TA_SOURCE;
COMMIT;
DELETE FROM G_GEO.TA_DATE_ACQUISITION;
COMMIT;
DELETE FROM G_GEO.TA_ECHELLE;
COMMIT;
DELETE FROM G_GEO.TA_PROVENANCE;
COMMIT;