-- TA_LIG_TOPO_F_ARCS_LINEARISES:
/*
Table regroupant l'ensemble des géométries de la table GEO@cudl.TA_LIG_TOPO_F sur lesquelles la fonction ARC_STROCKER de fme a été apliquée.
Cette table est necessaire pour créer la vue matérialisée G_GEO@multi.VM_RTGE_LINEAIRE et G_GEO@multi.VM_RTGE_SOMMET_LINEAIRE afin de rendre disponible les données de la table GEO@cudl.TA_LIG_TOPO_F à travers GEOSERVER.
*/

-- 1. Creation de la table TA_LIG_TOPO_F_ARCS_LINEARISES.
CREATE TABLE G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES
	(
    IDENTIFIANT_OBJET NUMBER(38,0),
    IDENTIFIANT_TYPE NUMBER(8,0),
    CODE_TYPE CHAR(6 BYTE),
    LIBELLE_TYPE VARCHAR2(100 BYTE),
    DECALAGE_DROITE NUMBER(8,0),
    DECALAGE_GAUCHE NUMBER(8,0),
    DATE_MAJ DATE,
    GEOM SDO_GEOMETRY
    )
;


-- 2. Creation du commentaire de la table.
COMMENT ON MATERIALIZED VIEW G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES IS 'Table qui présente les éléments contenus dans la table GEO@cudl.TA_LIG_TOPO_F sur lesquels a été appliqué la fonction ARC_STROCKER de FME pour convertir les arcs en lignes.';


-- 3. Creation des commentaires des colonnes.
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique - Cle primaire de la table';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.DATE_MAJ IS 'Date de deniere modification de l''objet';
COMMENT ON COLUMN G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES.GEOM IS 'Geometrie de l''objet - type ligne provenant de la table GEO@cudl.TA_LIG_TOPO_F sur lesquelles la fonction ARC_STROKER de FME a été appliquée pour convertir les arcs en lignes.';


-- 4. Creation de la clé primaire.
ALTER TABLE G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES
ADD CONSTRAINT TA_LIG_TOPO_F_ARCS_LINEARISES_PK 
PRIMARY KEY("IDENTIFIANT_OBJET") USING INDEX TABLESPACE "G_ADT_INDX";


-- 5. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_LIG_TOPO_F_ARCS_LINEARISES',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005),SDO_DIM_ELEMENT('Z', -999, 999, 0.005)),
    2154
);
COMMIT;


-- 6. Création de l'index spatial sur le champ geom
CREATE INDEX G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES_SIDX
ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=LINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 7. INDEX
-- 7.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_LIG_TOPO_F_ARCS_LINEARISES_IDENTIFIANT_TYPE_IDX ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.2. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_LIG_TOPO_F_ARCS_LINEARISES_CODE_TYPE_IDX ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7.3. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX TA_LIG_TOPO_F_ARCS_LINEARISES_LIBELLE_TYPE_IDX ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 8. Droits
GRANT SELECT, UPDATE, INSERT, DELETE ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES TO G_GEO_MAJ;
GRANT SELECT ON G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES TO G_GEO_LEC;