DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_RTGE_SOMMET_LINEAIRE';
DROP INDEX VM_RTGE_SOMMET_LINEAIRE_SIDX;
DROP INDEX VM_RTGE_SOMMET_LINEAIRE_IDENTIFIANT_TYPE_IDX;
DROP INDEX VM_RTGE_SOMMET_LINEAIRE_CODE_TYPE_IDX;
DROP INDEX VM_RTGE_SOMMET_LINEAIRE_LIBELLE_TYPE_IDX;
DROP MATERIALIZED VIEW VM_RTGE_SOMMET_LINEAIRE;

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la VM VM_RTGE_SOMMET_LINEAIRE-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue matérialisée pour afficher les sommets des linéaires contenus dans la table G_GEO.TA_LIG_TOPO_F avec l'altitude dans un champ.
--1. Creation
CREATE MATERIALIZED VIEW G_GEO.VM_RTGE_SOMMET_LINEAIRE
    (
    OBJECTID,
    IDENTIFIANT_OBJET,
    IDENTIFIANT_TYPE,
    CODE_TYPE,
    LIBELLE_TYPE,
    DECALAGE_DROITE,
    DECALAGE_GAUCHE,
    COORD_Z,
    DATE_MAJ,
    GEOM
    )
REFRESH ON DEMAND START WITH sysdate+0 NEXT TRUNC(sysdate)+43/24
FORCE
DISABLE QUERY REWRITE AS
SELECT
    CAST(ROWNUM as number(38,0)) AS OBJECTID,
    a.IDENTIFIANT_OBJET AS IDENTIFIANT_OBJET,
    a.IDENTIFIANT_TYPE AS CODE_TYPE,
    a.CODE_TYPE  AS IDENTIFIANT_TYPE,
    a.LIBELLE_TYPE AS LIBELLE_TYPE,
    a.DECALAGE_DROITE AS DECALAGE_DROITE,
    a.DECALAGE_GAUCHE AS DECALAGE_GAUCHE,
    CASE
        WHEN t.z > 0 AND t.z < 130 THEN ROUND(CAST(t.z AS NUMBER(5,2)),2)
        ELSE 0
    END COORD_Z,
    a.DATE_MAJ AS DATE_MAJ,
    SDO_GEOMETRY(2001, 2154,
    SDO_POINT_TYPE(t.X,t.Y,NULL),
    NULL, NULL) AS GEOM
FROM
    G_GEO.TA_LIG_TOPO_F_ARCS_LINEARISES a,
    TABLE
        (SDO_UTIL.GETVERTICES(a.geom)) t
;


-- 2. Commentaire
COMMENT ON MATERIALIZED VIEW G_GEO.VM_RTGE_SOMMET_LINEAIRE IS 'Vue qui présente les sommets des lineaires contenus dans la table GEO@cudl.TA_LIG_TOPO_F_ARCS_LINEARISES';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.OBJECTID IS 'Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.DECALAGE_DROITE IS 'Decallage a droite par rapport a la generatrice';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.DECALAGE_GAUCHE IS 'Decallage a gauche par rapport a la generatrice';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.COORD_Z IS 'Altitude du sommet';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.DATE_MAJ IS 'Date de deniere modification de l''objet';
COMMENT ON COLUMN G_GEO.VM_RTGE_SOMMET_LINEAIRE.GEOM IS 'Geometrie du sommet - type point';


-- 3. Création de la clé primaire
ALTER MATERIALIZED VIEW G_GEO.VM_RTGE_SOMMET_LINEAIRE
ADD CONSTRAINT VM_RTGE_SOMMET_LINEAIRE_IDENTIFIANT_OBJECTID_PK 
PRIMARY KEY (OBJECTID);

-- 4. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_RTGE_SOMMET_LINEAIRE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005)),
    2154
);
COMMIT;


-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX G_GEO.VM_RTGE_SOMMET_LINEAIRE_SIDX
ON G_GEO.VM_RTGE_SOMMET_LINEAIRE(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 6. INDEX
-- 6.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX VM_RTGE_SOMMET_LINEAIRE_IDENTIFIANT_TYPE_IDX ON G_GEO.VM_RTGE_SOMMET_LINEAIRE(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.2. Sur le champ CODE_TYPE.
CREATE INDEX VM_RTGE_SOMMET_LINEAIRE_CODE_TYPE_IDX ON G_GEO.VM_RTGE_SOMMET_LINEAIRE(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX VM_RTGE_SOMMET_LINEAIRE_LIBELLE_TYPE_IDX ON G_GEO.VM_RTGE_SOMMET_LINEAIRE(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;


-- 8. Droits
GRANT SELECT ON G_GEO.VM_RTGE_SOMMET_LINEAIRE TO G_GEO_MAJ;
GRANT SELECT ON G_GEO.VM_RTGE_SOMMET_LINEAIRE TO G_GEO_LEC;
GRANT SELECT ON G_GEO.VM_RTGE_SOMMET_LINEAIRE TO G_SERVICE_WEB;
GRANT SELECT ON G_GEO.VM_RTGE_SOMMET_LINEAIRE TO ISOGEO_LEC;