-- insertion des données du RPG dans le schéma G_ADT_AGRI

------------------------------------------------
-- 1. Traitement SQL pour la couche RPG_2019_MEL
------------------------------------------------

-- 1.1. creation de la clé primaire

-- 1.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 1.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 1.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 1.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_2019_MEL.nextval;
END;

-- 1.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_2019_MEL
SET objectid = SEQ_RPG_2019_MEL.nextval;

-- 1.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_2019_MEL
ADD CONSTRAINT RPG_2019_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";

-- 1.2. Création des métadonnées spatiales

-- 1.2.1. Renommer la colonne ORA_GEOMETRY -> GEOM
ALTER TABLE G_ADT_AGRI.RPG_2019_MEL RENAME COLUMN ORA_GEOMETRY TO GEOM;

-- 1.2.2 Ajout des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ('RPG_2019_MEL', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 2154);
COMMIT;

-- 1.2.3 Ajout des index spatiaux
CREATE INDEX RPG_2019_MEL_SIDX
ON RPG_2019_MEL(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=INDX_G_ADT, work_tablespace=DATA_TEMP');


------------------------------------------------
-- 2. Traitement SQL pour la couche RPG_2019_MEL
------------------------------------------------
-- 2.1. creation de la clé primaire

-- 2.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_PARCELLE_INSTRUITES_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 2.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_PARCELLE_INSTRUITES_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 2.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_PARCELLE_INSTRUITES_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 2.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_PARCELLE_INSTRUITES_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_PARCELLE_INSTRUITES_2019_MEL.nextval;
END;

-- 2.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_PARCELLE_INSTRUITES_2019_MEL
SET objectid = RPG_PARCELLE_INSTRUITES_2019_MEL.nextval;

-- 2.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_PARCELLE_INSTRUITES_2019_MEL
ADD CONSTRAINT RPG_PARCELLE_INSTRUITES_2019_MEL_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";


------------------------------------------------
-- 3. Traitement SQL pour la couche RPG_PACAGE_FORMEJURIDIQUE_2019_MEL
------------------------------------------------
-- 3.1. creation de la clé primaire

-- 3.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_PACAGE_FORMEJURIDIQUE_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 3.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_PACAGE_FORMEJURIDIQUE_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 3.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_PACAGE_FORMEJURIDIQUE_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 3.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_PACAGE_FORMEJURIDIQUE_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_PACAGE_FORMEJURIDIQUE_2019_MEL.nextval;
END;

-- 3.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_PACAGE_FORMEJURIDIQUE_2019_MEL
SET objectid = RPG_PACAGE_FORMEJURIDIQUE_2019_MEL.nextval;

-- 3.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_PACAGE_FORMEJURIDIQUE_2019_MEL
ADD CONSTRAINT RPG_PACAGE_FORMEJURIDIQUE_2019_MEL_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";


------------------------------------------------
-- 4. Traitement SQL pour la couche RPG_ILOTS_DESCRIPTION_2019_MEL
------------------------------------------------
-- 4.1. creation de la clé primaire

-- 4.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_ILOTS_DESCRIPTION_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 4.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_ILOTS_DESCRIPTION_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 4.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_ILOTS_DESCRIPTION_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 4.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_ILOTS_DESCRIPTION_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_ILOTS_DESCRIPTION_2019_MEL.nextval;
END;

-- 4.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_ILOTS_DESCRIPTION_2019_MEL
SET objectid = SEQ_RPG_ILOTS_DESCRIPTION_2019_MEL.nextval;

-- 4.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_ILOTS_DESCRIPTION_2019_MEL
ADD CONSTRAINT RPG_ILOTS_DESCRIPTION_2019_MEL_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";


------------------------------------------------
-- 5. Traitement SQL pour la couche RPG_AIDES_2ND_PILIER_2019_MEL
------------------------------------------------
-- 5.1. creation de la clé primaire

-- 5.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_AIDES_2ND_PILIER_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 5.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_AIDES_2ND_PILIER_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 5.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_AIDES_2ND_PILIER_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 5.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_AIDES_2ND_PILIER_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_AIDES_2ND_PILIER_2019_MEL.nextval;
END;

-- 5.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_AIDES_2ND_PILIER_2019_MEL
SET objectid = SEQ_RPG_AIDES_2ND_PILIER_2019_MEL.nextval;

-- 5.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_AIDES_2ND_PILIER_2019_MEL
ADD CONSTRAINT RPG_AIDES_2ND_PILIER_2019_MEL_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";


------------------------------------------------
-- 6. Traitement SQL pour la couche RPG_AIDES_1ER_PILIER_2019_MEL
------------------------------------------------
-- 6.1. creation de la clé primaire

-- 6.1.1. suppression de la colonne OGR_FID
ALTER TABLE G_ADT_AGRI.RPG_AIDES_1ER_PILIER_2019_MEL DROP COLUMN OGR_FID CASCADE CONSTRAINTS;

-- 6.1.2. Ajout de la colonne OBJECTID
ALTER TABLE G_ADT_AGRI.RPG_AIDES_1ER_PILIER_2019_MEL
ADD (OBJECTID NUMBER(38,0));

-- 6.1.3. Ajout de la séquence
CREATE SEQUENCE SEQ_RPG_AIDES_1ER_PILIER_2019_MEL INCREMENT BY 1 START WITH 1 NOCACHE;

-- 6.1.4. Ajout du trigger
CREATE OR REPLACE TRIGGER BEF_RPG_AIDES_1ER_PILIER_2019_MEL
BEFORE INSERT ON TABLE_NAME FOR EACH ROW
BEGIN
	:new.OBJECTID := SEQ_RPG_AIDES_1ER_PILIER_2019_MEL.nextval;
END;

-- 6.1.5. Mise à jour de la colonne OBJECTID
UPDATE G_ADT_AGRI.RPG_AIDES_1ER_PILIER_2019_MEL
SET objectid = SEQ_RPG_AIDES_1ER_PILIER_2019_MEL.nextval;

-- 6.1.6. Ajout de la contrainte d'unicité clé primaire
ALTER TABLE G_ADT_AGRI.RPG_AIDES_1ER_PILIER_2019_MEL
ADD CONSTRAINT RPG_AIDES_1ER_PILIER_2019_MEL_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "DATA_G_ADT";