CREATE OR REPLACE PROCEDURE GENERATION_VM_OCSMEL()

IS
BEGIN

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_OCSMEL';
DROP INDEX VM_OCSMEL_SIDX;
DROP INDEX VM_OCSMEL_IDENTIFIANT_TYPE_IDX;
DROP INDEX VM_OCSMEL_CODE_TYPE_IDX;
DROP INDEX VM_OCSMEL_LIBELLE_TYPE_IDX;
DROP MATERIALIZED VIEW VM_OCSMEL;

----------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------1. Création de la VM VM_OCSMEL-----------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

-- Creation d'une vue pour afficher les objets contenus dans la table G_GESTIONGEO.TA_OCSMEL.
--1. Creation
CREATE MATERIALIZED VIEW G_GEO.VM_OCSMEL
    (
    IDENTIFIANT_OBJET,
    IDENTIFIANT_TYPE,
    CODE_TYPE,
    LIBELLE_TYPE,
    DATE_MAJ,
    GEOM
    )
REFRESH ON DEMAND
FORCE
DISABLE QUERY REWRITE AS
SELECT
    a.IDENTIFIANT_OBJET AS IDENTIFIANT_OBJET,
    a.IDENTIFIANT_TYPE AS CODE_TYPE,
    b.LIBELLE_COURT  AS IDENTIFIANT_TYPE,
    b.LIBELLE_LONG AS LIBELLE_TYPE,
    COALESCE(a.DATE_MODIFICATION, b.DATE_CREATION) AS DATE_MAJ,
    a.GEOM
FROM
    G_GESTIONGEO.TA_OCSMEL a
    INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.OBJECTID
;


-- 2. Commentaire
COMMENT ON MATERIALIZED VIEW G_GESTIONGEO.VM_OCSMEL IS 'Vue qui présente les objets contenus dans la table G_GESTIONGEO.TA_OCSMEL';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.IDENTIFIANT_OBJET IS 'Identifiant interne de l''objet geographique - Cle primaire de la vue materialisee';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.IDENTIFIANT_TYPE IS 'Identifiant de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.CODE_TYPE IS 'Nom court de la classe a laquelle appartient l''objet';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.LIBELLE_TYPE IS 'Libelle de la classe de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.DATE_MAJ IS 'Date de deniere modification de l''objet';
COMMENT ON COLUMN G_GESTIONGEO.VM_OCSMEL.GEOM IS 'Geometrie de l''objet - type point';


-- 3. Création de la clé primaire
ALTER MATERIALIZED VIEW G_GESTIONGEO.VM_OCSMEL
ADD CONSTRAINT VM_OCSMEL_IDENTIFIANT_OBJET_PK 
PRIMARY KEY (IDENTIFIANT_OBJET);

-- 4. Metadonnee
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_OCSMEL',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 680041, 724322, 0.005),SDO_DIM_ELEMENT('Y', 7039713, 7082570, 0.005)),
    2154
);
COMMIT;


-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX G_GESTIONGEO.VM_OCSMEL_SIDX
ON G_GESTIONGEO.VM_OCSMEL(GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 6. INDEX
-- 6.1. Sur le champ IDENTIFIANT_TYPE.
CREATE INDEX VM_OCSMEL_IDENTIFIANT_TYPE_IDX ON G_GESTIONGEO.VM_OCSMEL(IDENTIFIANT_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.2. Sur le champ CODE_TYPE.
CREATE INDEX VM_OCSMEL_CODE_TYPE_IDX ON G_GESTIONGEO.VM_OCSMEL(CODE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 6.3. Sur le champ LIBELLE_TYPE.
CREATE INDEX VM_OCSMEL_LIBELLE_TYPE_IDX ON G_GESTIONGEO.VM_OCSMEL(LIBELLE_TYPE)
    TABLESPACE G_ADT_INDX;

-- 7. Droits
GRANT SELECT ON G_GESTIONGEO.VM_OCSMEL TO G_GESTIONGEO_MAJ;
GRANT SELECT ON G_GESTIONGEO.VM_OCSMEL TO G_GESTIONGEO_LEC;
GRANT SELECT ON G_GESTIONGEO.VM_OCSMEL TO G_SERVICE_WEB;
GRANT SELECT ON G_GESTIONGEO.VM_OCSMEL TO ISOGEO_LEC;


END GENERATION_VM_OCSMEL;

/
