-- table utilisée pour avoir l'historique de la gestion de chaque zone et des agents associés

DROP TABLE GEO.TA_ACQ_GG_COM;
DROP SEQUENCE GEO.TA_ACQ_GG_COM_pk_seq;
DROP TRIGGER  "GEO"."TA_ACQ_GG_COM";

CREATE TABLE GEO.TA_ACQ_GG_COM
(
  ID SMALLINT NOT NULL,
  INSEE VARCHAR2(5) NOT NULL,
  NOM_AGENT VARCHAR2(20) NOT NULL,
  DATE_DEBUT DATE,
  DATE_FIN VARCHAR2(20),
  VALID NUMBER(1,0),
  CONSTRAINT TA_ACQ_GG_COM_PK
    PRIMARY KEY (ID) ENABLE
);

CREATE SEQUENCE TA_ACQ_GG_COM_pk_seq START WITH 1;

CREATE OR REPLACE TRIGGER "GEO"."TA_ACQ_GG_COM"
	BEFORE INSERT ON "GEO"."TA_ACQ_GG_COM"
	FOR EACH ROW
	BEGIN
	  select TA_ACQ_GG_COM_pk_seq.nextval into :new.ID from dual;
	END;

COMMENT ON COLUMN TA_ACQ_GG_COM.INSEE IS 'code insee de la commune';
COMMENT ON COLUMN TA_ACQ_GG_COM.NOM_AGENT IS 'agent en charge de la commune';
COMMENT ON COLUMN TA_ACQ_GG_COM.DATE_DEBUT IS 'début de l''attribution à l''agent';
COMMENT ON COLUMN TA_ACQ_GG_COM.DATE_FIN IS 'fin de l''attribution à l''agent';
COMMENT ON COLUMN TA_ACQ_GG_COM.VALID IS 'validité de l''attribution';

COMMENT ON TABLE TA_ACQ_GG_COM IS 'table indiquant les communes attribuées à un gestionnaire de territoire';

INSERT INTO GEO.TA_ACQ_GG_COM (INSEE, NOM_AGENT) VALUES
('59128', 'delebarre'),

UPDATE GEO.TA_ACQ_GG_COM
SET DATE_DEBUT =  to_date('2018-01-01', 'yyyy-mm-dd')



/*
DROP INDEX "GEO"."TA_ACQ_GG_ZONAGE"
DROP TABLE "GEO"."TA_ACQ_GG_ZONAGE";
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_ACQ_GG_ZONAGE';
*/

CREATE TABLE GEO.TA_ACQ_GG_ZONAGE AS
SELECT
  NOM_AGENT,
  SDO_UTIL.EXTRACT(
    SDO_AGGR_UNION(SDOAGGRTYPE(LM_COMMUNES.GEOM, 1)),
    1, 1) AS GEOM
FROM GEO.TA_ACQ_GG_COM
JOIN GEO.LM_COMMUNES ON LM_COMMUNES.INSEE = TA_ACQ_GG_COM.INSEE
WHERE TA_ACQ_GG_COM.VALID = 1
GROUP BY TA_ACQ_GG_COM.NOM_AGENT;

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
  'TA_ACQ_GG_ZONAGE',
  'GEOM',
  SDO_DIM_ARRAY(SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005),
  SDO_DIM_ELEMENT('X', 594000, 964000, 0.005)),
  2154
  );

CREATE INDEX "GEO"."TA_ACQ_GG_ZONAGE_SIDX"
  ON "GEO"."TA_ACQ_GG_ZONAGE" ("GEOM")
  INDEXTYPE IS MDSYS.SPATIAL_INDEX
  PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE = POLYGON WORK_TABLESPACE=DATA_TEMP TABLESPACE=ISPA_GEO');

COMMENT ON TABLE GEO.TA_ACQ_GG_ZONAGE IS 'zones couvertes par un agent du plan de gestion';

SELECT a.ID_DOS, d.NOM_AGENT
FROM GEO.TA_ACQ_GG_ZONAGE d, GEO.TA_GG_GEO a
JOIN GEO.TA_GG_DOSSIER b ON b.ID_DOS = a.ID_DOS
JOIN GEO.TA_GG_FAMILLE c ON c.FAM_ID = b.FAM_ID
WHERE SDO_CONTAINS(d.geom, SDO_GEOM.SDO_CENTROID(a.geom)) = 'TRUE'

WITH source AS (
SELECT ID_DOS, SDO_CENTROID(geom)
FROM GEO.TA_GG_GEO)
SELECT COUNT(ID_DOS)
FROM source;
