-- Creation des tables temporaire contenant les données de l'application GESTIONGEO provenant de l'instance CUDL

-- 1. Table TA_POINT_TOPO_GPS
CREATE TABLE TEMP_TA_POINT_TOPO_GPS AS
SELECT * FROM GEO.TA_POINT_TOPO_GPS@DBL_CUDL_GEO;

-- 2. Table TA_LIG_TOPO_GPS
CREATE TABLE TEMP_TA_LIG_TOPO_GPS AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS@DBL_CUDL_GEO;

-- 3. Table PTTOPO
CREATE TABLE TEMP_PTTOPO AS
SELECT * FROM GEO.PTTOPO@DBL_CUDL_GEO;

-- 4. Table TA_POINT_TOPO_F
CREATE TABLE TEMP_TA_POINT_TOPO_F AS
SELECT * FROM GEO.TA_POINT_TOPO_F@DBL_CUDL_GEO;

-- 5. Table TA_LIG_TOPO_F
CREATE TABLE TEMP_TA_LIG_TOPO_F AS
SELECT * FROM GEO.TA_LIG_TOPO_F@DBL_CUDL_GEO;

-- 6. Table TA_SUR_TOPO_G
CREATE TABLE TEMP_TA_POINT_TOPO_GPS AS
SELECT * FROM GEO.TA_POINT_TOPO_GPS@DBL_CUDL_GEO;

-- 7. Table TA_POINT_TOPO_F_LOG
CREATE TABLE TEMP_TA_POINT_TOPO_F_LOG AS
SELECT * FROM GEO.TA_POINT_TOPO_F_LOG@DBL_CUDL_GEO;

-- 8. Table TA_LIG_TOPO_F_LOG
CREATE TABLE TEMP_TA_LIG_TOPO_F_LOG AS
SELECT * FROM GEO.TA_LIG_TOPO_F_LOG@DBL_CUDL_GEO;

-- 9. Table TA_SUR_TOPO_G_LOG
CREATE TABLE TEMP_TA_SUR_TOPO_G_LOG AS
SELECT * FROM GEO.TA_SUR_TOPO_G_LOG@DBL_CUDL_GEO;

-- 10. Table TA_LIG_TOPO_GPS_BACKUP
CREATE TABLE TEMP_TA_LIG_TOPO_GPS_BACKUP AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS_BACKUP@DBL_CUDL_GEO;

-- 11. TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1
CREATE TABLE TEMP_TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1 AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1@DBL_CUDL_GEO;

/
