-- Creation des tables temporaire contenant les données de l'application GESTIONGEO provenant de l'instance CUDL

-- 1. Table TA_POINT_TOPO_GPS
CREATE TABLE TEMP_TA_POINT_TOPO_GPS AS
SELECT * FROM GEO.TA_POINT_TOPO_GPS@DBL_CUDL_GEO WHERE GEO_REF NOT LIKE 'IC_%';


-- 2. Table TA_LIG_TOPO_GPS
CREATE TABLE TEMP_TA_LIG_TOPO_GPS AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS@DBL_CUDL_GEO WHERE GEO_REF NOT LIKE 'IC_%';


-- 3. Table PTTOPO
CREATE TABLE TEMP_PTTOPO AS
SELECT a.* FROM GEO.PTTOPO@DBL_CUDL_GEO a;


-- 4. Table TA_POINT_TOPO_F
CREATE TABLE TEMP_TA_POINT_TOPO_F AS
SELECT * FROM GEO.TA_POINT_TOPO_F@DBL_CUDL_GEO
WHERE OBJECTID NOT IN (SELECT OBJECTID FROM TA_POINT_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE ('IC%')
;


-- 5. Table TA_LIG_TOPO_F
CREATE TABLE TEMP_TA_LIG_TOPO_F AS
SELECT * FROM GEO.TA_LIG_TOPO_F@DBL_CUDL_GEO
WHERE OBJECTID NOT IN (SELECT OBJECTID FROM TA_LIG_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE ('IC%');


-- 6. Table TA_POINT_TOPO_F_LOG
CREATE TABLE TEMP_TA_POINT_TOPO_F_LOG AS
SELECT * FROM GEO.TA_POINT_TOPO_F_LOG@DBL_CUDL_GEO
WHERE FID_IDENTIFIANT NOT IN (SELECT OBJECTID FROM TA_LIG_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE ('IC%');


-- 7. Table TA_LIG_TOPO_F_LOG
CREATE TABLE TEMP_TA_LIG_TOPO_F_LOG AS
SELECT * FROM GEO.TA_LIG_TOPO_F_LOG@DBL_CUDL_GEO
WHERE FID_IDENTIFIANT NOT IN (SELECT OBJECTID FROM TA_LIG_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE ('IC%');


-- 8. Table TA_SUR_TOPO_G
CREATE TABLE TEMP_TA_SUR_TOPO_G AS
SELECT * FROM GEO.TA_SUR_TOPO_G@DBL_CUDL_GEO;


-- 9. Table TA_SUR_TOPO_G_LOG
CREATE TABLE TEMP_TA_SUR_TOPO_G_LOG AS
SELECT * FROM GEO.TA_SUR_TOPO_G_LOG@DBL_CUDL_GEO;


-- 10. Table TA_LIG_TOPO_G
CREATE TABLE TEMP_TA_LIG_TOPO_G AS
SELECT * FROM GEO.TA_LIG_TOPO_G@DBL_CUDL_GEO;


-- 11. Table TA_LIG_TOPO_G_LOG
CREATE TABLE TEMP_TA_LIG_TOPO_G_LOG AS
SELECT * FROM GEO.TA_LIG_TOPO_G_LOG@DBL_CUDL_GEO;


-- 12. Table TA_LIG_TOPO_GPS_BACKUP
CREATE TABLE TEMP_TA_LIG_TOPO_GPS_BACKUP AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS_BACKUP@DBL_CUDL_GEO
WHERE OBJECTID NOT IN (SELECT OBJECTID FROM TA_LIG_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE 'IC_%';


-- 13. TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1
CREATE TABLE TEMP_TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1 AS
SELECT * FROM GEO.TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1@DBL_CUDL_GEO
WHERE OBJECTID NOT IN (SELECT OBJECTID FROM TA_LIG_TOPO_GPS WHERE GEO_REF LIKE ('IC_%'))
OR GEO_REF NOT LIKE 'IC_%';

-- 14. TA_LIG_TOPO_IC
CREATE TABLE TEMP_TA_LIG_TOPO_IC AS
SELECT * FROM GEO.TA_LIG_TOPO_IC@DBL_CUDL_GEO;

/*
-- 15. _V_TA_CLASSE_CAT
CREATE TABLE TEMP_V_TA_CLASSE_CAT AS
SELECT * FROM ELYX_DATA.V_TA_CLASSE_CAT@   // DBL_CUDL_GEO//;
*/
/
