-- Suppression des tables de test
DROP TABLE G_GEO.TEST_TA_IDENTIFIANT_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TEST_TA_ZA_COMMUNES CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TEST_TA_CODE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TEST_TA_COMMUNE CASCADE CONSTRAINTS;

DELETE
FROM USER_SDO_GEOM_METADATA
WHERE
    TABLE_NAME = 'TEST_TA_COMMUNE';
COMMIT;

/*
La table TEST_ta_commune regroupe toutes les communes de la MEL.
*/

-- 1. Création de la table TEST_ta_commune
CREATE TABLE TEST_ta_commune(
    objectid NUMBER(38,0)GENERATED BY DEFAULT AS IDENTITY,
    geom SDO_GEOMETRY,
    fid_lib_type_commune NUMBER(38,0),
    fid_nom NUMBER(38,0),
    fid_metadonnee NUMBER(38,0)    
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE g_geo.TEST_ta_commune IS 'Table testant l''insertion de la nouvelle BdTopo rassemblant tous les contours communaux de la MEL et leur équivalent belge.';
COMMENT ON COLUMN g_geo.TEST_ta_commune.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN g_geo.TEST_ta_commune.geom IS 'Géométrie de chaque commune ou équivalent international.';
COMMENT ON COLUMN g_geo.TEST_ta_commune.fid_lib_type_commune IS 'Clé étrangère permettant de connaître le statut de la commune ou équivalent international - ta_libelle.';
COMMENT ON COLUMN g_geo.TEST_ta_commune.fid_nom IS 'Clé étrangère de la table TA_NOM permettant de connaître le nom de chaque commune ou équivalent international.';
COMMENT ON COLUMN g_geo.TEST_ta_commune.fid_metadonnee IS 'Clé étrangère permettant de retrouver la source à partir de laquelle la donnée est issue - ta_source.';


-- 3. Création de la clé primaire
ALTER TABLE TEST_ta_commune 
ADD CONSTRAINT TEST_ta_commune_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEST_ta_commune',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TEST_ta_commune_SIDX
ON TEST_ta_commune(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 6. Création des clés étrangères
-- 6.1. Clé étrangère vers la table TA_LIBELLE
ALTER TABLE TEST_ta_commune
ADD CONSTRAINT TEST_ta_commune_fid_lib_type_commune_FK 
FOREIGN KEY (fid_lib_type_commune)
REFERENCES ta_libelle(objectid);

-- 6.2. Clé étrangère vers la table TA_NOM
ALTER TABLE TEST_ta_commune
ADD CONSTRAINT TEST_ta_commune_fid_nom_FK 
FOREIGN KEY (fid_nom)
REFERENCES ta_nom(objectid);

-- 6.3. Clé étrangère vers la TA_METADONNEE
ALTER TABLE TEST_ta_commune
ADD CONSTRAINT TEST_ta_commune_fid_metadonnee_FK 
FOREIGN KEY (fid_metadonnee)
REFERENCES ta_metadonnee(objectid);

-- 7. Création des indexes sur les clés étrangères
CREATE INDEX TEST_ta_commune_fid_lib_type_commune_IDX ON TEST_ta_commune(fid_lib_type_commune)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEST_ta_commune_fid_nom_IDX ON TEST_ta_commune(fid_nom)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEST_ta_commune_fid_metadonnee_IDX ON TEST_ta_commune(fid_metadonnee)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON g_geo.TEST_ta_commune TO G_ADMIN_SIG;

-- 1. Création de la table
CREATE TABLE TEST_ta_code(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
	valeur VARCHAR2(50),
	fid_libelle NUMBER(38,0)
);

-- 2. Création des commentaires
COMMENT ON TABLE g_geo.TEST_ta_code IS 'La table testant l''insertion de la nouvelle BdTopo et regroupant tous les codes du schéma G_GEO.';
COMMENT ON COLUMN g_geo.TEST_ta_code.objectid IS 'Clé primaire de la table.';
COMMENT ON COLUMN g_geo.TEST_ta_code.valeur IS 'Codes de chaque donnée du schéma.';
COMMENT ON COLUMN g_geo.TEST_ta_code.fid_libelle IS 'Clé étrangère de ta_libelle permettant de connaître la signification de chaque code.';

-- 3. Création de la clé primaire
ALTER TABLE TEST_ta_code
ADD CONSTRAINT TEST_ta_code_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangère
-- 4.1. Clé étrangère vers la table TA_LIBELLE
ALTER TABLE TEST_ta_code
ADD CONSTRAINT TEST_ta_code_fid_libelle_FK
FOREIGN KEY (fid_libelle)
REFERENCES ta_libelle(objectid);

-- 5. Création de l'index de la clé étrangère
CREATE INDEX TEST_ta_code_fid_libelle_IDX ON TEST_ta_code(fid_libelle)
TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON g_geo.TEST_ta_code TO G_ADMIN_SIG;

/*
La table TEST_ta_identifiant_commune permet de regrouper tous les codes par commune. 
*/

-- 1. Création de la table
CREATE TABLE TEST_ta_identifiant_commune(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
	fid_commune NUMBER(38,0),
	fid_identifiant NUMBER(38,0)
);

-- 2. Création des commentaires
COMMENT ON TABLE g_geo.TEST_ta_identifiant_commune IS 'La table testant l''insertion de la nouvelle BdTopo permettant de regrouper tous les codes par commune.';
COMMENT ON COLUMN g_geo.TEST_ta_identifiant_commune.objectid IS 'Clé primaire de la table.';
COMMENT ON COLUMN g_geo.TEST_ta_identifiant_commune.fid_commune IS 'Clé étrangère de la table TEST_ta_commune.';
COMMENT ON COLUMN g_geo.TEST_ta_identifiant_commune.fid_identifiant IS 'Clé étrangère de la table TEST_ta_code.';

-- 3. Création de la clé primaire
ALTER TABLE TEST_ta_identifiant_commune
ADD CONSTRAINT	TEST_ta_identifiant_commune_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 6. Création des clés étrangères
-- 6.1. Clé étrangère vers la table TEST_ta_commune
ALTER TABLE TEST_ta_identifiant_commune
ADD CONSTRAINT TEST_ta_identifiant_commune_fid_commune_FK 
FOREIGN KEY (fid_commune)
REFERENCES TEST_ta_commune(objectid);

-- 6.2. Clé étrangère vers la table TEST_ta_code
ALTER TABLE TEST_ta_identifiant_commune
ADD CONSTRAINT TEST_ta_identifiant_commune_fid_identifiant_FK 
FOREIGN KEY (fid_identifiant)
REFERENCES TEST_ta_code(objectid);

-- 4. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON g_geo.TEST_ta_identifiant_commune TO G_ADMIN_SIG;

-- 1. Création de la table TEST_ta_za_communes
CREATE TABLE TEST_ta_za_communes(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    fid_commune NUMBER(38,0),
    fid_zone_administrative NUMBER(38,0),
    debut_validite DATE,
    fin_validite DATE
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE g_geo.TEST_ta_za_communes IS 'Table de liaison testant l''insertion de la nouvelle BdTopo entre les tables TEST_ta_commune et ta_unite_territoriale';
COMMENT ON COLUMN g_geo.TEST_ta_za_communes.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN g_geo.TEST_ta_za_communes.fid_commune IS 'Clé étrangère de la table TEST_ta_commune.';
COMMENT ON COLUMN g_geo.TEST_ta_za_communes.fid_zone_administrative IS 'Clé étrangère de la table TA_ZONE_ADMINISTRATIVE.';
COMMENT ON COLUMN g_geo.TEST_ta_za_communes.debut_validite IS 'Début de validité de la zone supra-communale. Ce champ est mis à jour dés qu''une commune change.';
COMMENT ON COLUMN g_geo.TEST_ta_za_communes.fin_validite IS 'Fin de validité de la zone supra-communale. Ce champ est mis à jour dés qu''une commune change.';

-- 3. Création de la clé primaire
ALTER TABLE TEST_ta_za_communes 
ADD CONSTRAINT TEST_ta_za_communes_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
-- 4.1. Clé étrangère vers la table TEST_ta_commune
ALTER TABLE TEST_ta_za_communes
ADD CONSTRAINT TEST_ta_za_communes_fid_commune_FK
FOREIGN KEY (fid_commune)
REFERENCES TEST_ta_commune(objectid);

-- 4.2. Clé étrangère vers la table TA_ZONE_ADMINISTRATIVE
ALTER TABLE TEST_ta_za_communes
ADD CONSTRAINT TEST_ta_za_communes_fid_zone_administrative_FK
FOREIGN KEY (fid_zone_administrative)
REFERENCES ta_zone_administrative(objectid);

-- 7. Création des indexes sur les clés étrangères
CREATE INDEX TEST_ta_za_communes_fid_commune_IDX ON TEST_ta_za_communes(fid_commune)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEST_ta_za_communes_fid_zone_administrative_IDX ON TEST_ta_za_communes(fid_zone_administrative)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON g_geo.TEST_ta_za_communes TO G_ADMIN_SIG;
