-------------------------
-- DROIT_DES_SEQUENCES --
-------------------------

-- Gestion des droits des sequences

GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_POINT_INTEGRATION_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_LINEAIRE_INTEGRATION_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_POINT_PRODUCTION_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_LINEAIRE_PRODUCTION_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_OCSMEL_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_PTTOPO_INTEGRATION_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_OCSMEL_LINEAIRE_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_SURFACE_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_IC_LINEAIRE_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_SURFACE_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_POINT_INTEGRATION_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_POINT_PRODUCTION_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_LINEAIRE_INTEGRATION_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_LINEAIRE_PRODUCTION_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_OCSMEL_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_OCSMEL_LINEAIRE_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_IC_LINEAIRE_LOG_OBJECTID TO G_GESTIONGEO_RW;
GRANT SELECT ON G_GESTIONGEO.SEQ_TA_RTGE_ALTI_CONSULTATION_OBJECTID TO G_GESTIONGEO_RW;

/
