/*
La table TA_ORGANISME recense tous les organismes créateurs de données desquels proviennent les données source de la table ta_source.
*/

-- 1. Création de la table TA_ORGANISME
CREATE TABLE G_GEO.TA_ORGANISME(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    acronyme VARCHAR2(50),
    nom_organisme VARCHAR2(2000)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_GEO.TA_ORGANISME IS 'Table rassemblant tous les organismes créateurs des données source utilisées par la MEL.';
COMMENT ON COLUMN G_GEO.TA_ORGANISME.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN G_GEO.TA_ORGANISME.acronyme IS 'Sigle correspondant à l''organisme créateur de la donnée source';
COMMENT ON COLUMN G_GEO.TA_ORGANISME.nom_organisme IS 'Nom de l''organisme créateur des données sources utilisées par la MEL';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_ORGANISME 
ADD CONSTRAINT TA_ORGANISME_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GEO.TA_ORGANISME TO G_ADMIN_SIG;