
  CREATE OR REPLACE FORCE VIEW "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE" ("IDENTIFIANT", "NOM_OBJET", "TYPE_OBJET", "NOM_CHAMP", "REQUETE", 
	 CONSTRAINT "V_ERREURS_MTD_SPATIALE_MANQUANTE_PK" PRIMARY KEY ("IDENTIFIANT") DISABLE) AS 
  SELECT
    ROWNUM AS IDENTIFIANT,
    a.TABLE_NAME AS NOM_OBJET,
    b.object_type AS TYPE_OBJET,
    a.column_name AS NOM_CHAMP,
    'INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME,COLUMN_NAME, DIMINFO, SRID)VALUES(''' || a.TABLE_NAME || ''',''' || a.column_name || ''',SDO_DIM_ARRAY(SDO_DIM_ELEMENT(''X'', 594000, 964000, 0.005),SDO_DIM_ELEMENT(''Y'', 6987000, 7165000, 0.005)), 2154);' AS REQUETE
FROM
    USER_TAB_COLUMNS a
    INNER JOIN USER_OBJECTS b ON b.object_name = a.table_name
WHERE
    a.data_type = 'SDO_GEOMETRY'
    AND a.TABLE_NAME NOT IN(SELECT TABLE_NAME FROM USER_SDO_GEOM_METADATA);

   COMMENT ON COLUMN "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE"."IDENTIFIANT" IS 'Clé primaire de la vue.';
   COMMENT ON COLUMN "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE"."NOM_OBJET" IS 'Nom de l''objet disposant d''un champ géométrique mais pas de métadonnées spatiales.';
   COMMENT ON COLUMN "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE"."TYPE_OBJET" IS 'Type de l''objet ayant un champ géométrique mais pas de métadonnées spatiales.';
   COMMENT ON COLUMN "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE"."NOM_CHAMP" IS 'Nom du champ géométrique.';
   COMMENT ON COLUMN "G_BASE_VOIE"."V_ERREURS_MTD_SPATIALE_MANQUANTE"."REQUETE" IS 'Requête d''insertion des métadonnées spatiales. Précision : la Minimum Bounding Box utilisée a été calculée à partir de la MEL95.';