/*
La table TA_COMMUNE regroupe tous les éléments de base du référentiel administratif, c'est-à-dire par exemple toutes les communes françaises et toutes les municipalités belges.
*/

-- 1. Création de la table TA_COMMUNE
CREATE TABLE G_GEO.TA_COMMUNE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    geom SDO_GEOMETRY,
    fid_lib_type_commune NUMBER(38,0),
    fid_nom NUMBER(38,0),
    fid_metadonnee NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_GEO.TA_COMMUNE IS 'Table rassemblant tous les éléments de base du référentiel administratif tels que les communes françaises.';
COMMENT ON COLUMN G_GEO.TA_COMMUNE.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN G_GEO.TA_COMMUNE.geom IS 'Géométrie de chaque commune ou équivalent international.';
COMMENT ON COLUMN G_GEO.TA_COMMUNE.fid_lib_type_commune IS 'Clé étrangère permettant de connaître le statut de la commune ou équivalent international - ta_libelle.';
COMMENT ON COLUMN G_GEO.TA_COMMUNE.fid_nom IS 'Clé étrangère de la table TA_NOM permettant de connaître le nom de chaque commune ou équivalent international.';
COMMENT ON COLUMN G_GEO.TA_COMMUNE.fid_metadonnee IS 'Clé étrangère permettant de retrouver la source à partir de laquelle la donnée est issue - ta_source.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_COMMUNE 
ADD CONSTRAINT TA_COMMUNE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_COMMUNE',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TA_COMMUNE_SIDX
ON G_GEO.TA_COMMUNE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 6. Création des clés étrangères
ALTER TABLE G_GEO.TA_COMMUNE
ADD CONSTRAINT TA_COMMUNE_fid_source_FK 
FOREIGN KEY (fid_source)
REFERENCES G_GEO.ta_source(objectid);

ALTER TABLE G_GEO.TA_COMMUNE
ADD CONSTRAINT TA_COMMUNE_fid_lib_type_commune_FK
FOREIGN KEY (fid_lib_type_commune_type_commune)
REFERENCES G_GEO.ta_libelle(objectid);

ALTER TABLE G_GEO.TA_COMMUNE
ADD CONSTRAINT TA_COMMUNE_fid_nom_FK
FOREIGN KEY (fid_nom)
REFERENCES G_GEO.ta_nom(objectid);

ALTER TABLE G_GEO.TA_COMMUNE
ADD CONSTRAINT TA_COMMUNE_fid_metadonnee_FK
FOREIGN KEY (fid_metadonnee)
REFERENCES G_GEO.ta_metadonnee(objectid);

-- 7. Création des index sur les clés étrangères
CREATE INDEX TA_COMMUNE_fid_source_IDX ON G_GEO.TA_COMMUNE(fid_source)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_COMMUNE_fid_lib_type_commune_IDX ON G_GEO.TA_COMMUNE(fid_lib_type_commune)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_COMMUNE_fid_nom_IDX ON G_GEO.TA_COMMUNE(fid_nom)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_COMMUNE_fid_metadonnee_IDX ON G_GEO.TA_COMMUNE(fid_metadonnee)
    TABLESPACE G_ADT_INDX;


-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GEO.TA_COMMUNE TO G_ADMIN_SIG;