/*
Creation de la table G_GEO.TA_BPE_GEOM qui recense les géométries que peuvent prendre les equipements de la Base Permanente des Equipements.
*/
-- 1. Création de la table
CREATE TABLE G_GEO.TA_BPE_GEOM(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    geom SDO_GEOMETRY
	);

-- 2. Création des commentaires
COMMENT ON TABLE G_GEO.TA_BPE_GEOM IS 'Table regroupant les positions que peuvent prendre les équipements de la Base Permanente des Equipements';
COMMENT ON COLUMN G_GEO.TA_BPE_GEOM.objectid IS 'Clé primaire de la table G_GEO.TA_BPE_GEOM.';
COMMENT ON COLUMN G_GEO.TA_BPE_GEOM.geom IS 'Position géographique que peuvent prendre les équipements.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_BPE_GEOM
ADD CONSTRAINT TA_BPE_GEOM_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_BPE_GEOM',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TA_BPE_GEOM_SIDX
ON G_GEO.TA_BPE_GEOM(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');
