
--1 CREATION TABLE TA_PAYS
CREATE TABLE "G_REFERENTIEL"."TA_PAYS" 
(	"OBJECTID" NUMBER(38,0), 
"NOM_PAYS" VARCHAR2(200 BYTE), 
"GEOM" "SDO_GEOMETRY", 
"FID_SOURCE" NUMBER(38,0), 
"FID_LIB_TYPE_PAYS" NUMBER(38,0);

--2 CREATION DES COMMENTAIRE
COMMENT ON COLUMN "G_REFERENTIEL"."TA_PAYS"."OBJECTID" IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN "G_REFERENTIEL"."TA_PAYS"."NOM_PAYS" IS 'Nom de chaque pays.';
COMMENT ON COLUMN "G_REFERENTIEL"."TA_PAYS"."GEOM" IS 'Colonne contenant la geometrie des pays. EPSG 3035';
COMMENT ON COLUMN "G_REFERENTIEL"."TA_PAYS"."FID_SOURCE" IS 'Clé étrangère du champ objectid de la table ta_source.';
COMMENT ON COLUMN "G_REFERENTIEL"."TA_PAYS"."FID_LIB_TYPE_PAYS" IS 'Clé étrangère du champ objectid de la table ta_libelle.';
COMMENT ON TABLE "G_REFERENTIEL"."TA_PAYS"  IS 'Table contenant les pays limitrophe au nord la France';


--3 CREATION DE LA CLEF PRIMAIRE
ALTER TABLE 
  TA_PAYS
ADD CONSTRAINT 
  TA_PAYS_PK 
PRIMARY KEY("OBJECTID")
USING INDEX
TABLESPACE "INDX_GEO";

--4 CREATION DE LA SEQUENCE D'AUTO-INCREMENTATION DE LA CLE PRIMAIRE
CREATE SEQUENCE SEQ_TA_PAYS
START WITH 1 INCREMENT BY 1;


--5 Création du déclencheur d'auto-incrémentation de la clé primaire
CREATE OR REPLACE TRIGGER BEF_TA_PAYS
BEFORE INSERT ON TA_PAYS
FOR EACH ROW

BEGIN
  :new.objectid := SEQ_TA_PAYS.nextval;
END;

-- 6 CREATION METADONNEES SPATIALES
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'test_TA_PAYS',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', -7143480, 16936923, 0.005),SDO_DIM_ELEMENT('Y', -9160794, 15428321, 0.005)), 
    3035
);

--7 CREATION INDEX SPATIAL SUR LE CHAMP GEOM
CREATE INDEX TA_PAYS_SIDX
ON TA_PAYS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=INDX_GEO, work_tablespace=DATA_TEMP');

--8 CREATION DES CLES ETRANGERES
ALTER TABLE TA_PAYS
ADD CONSTRAINT TA_PAYS_FID_SOURCE_FK 
FOREIGN KEY (FID_SOURCE)
REFERENCES TA_SOURCE(objectid);

ALTER TABLE TA_PAYS
ADD CONSTRAINT TA_PAYS_FID_LIBELLE_FK
FOREIGN KEY (fid_lib_type_pays)
REFERENCES ta_libelle(objectid);


-- 9. Création des index sur les clés étrangères
CREATE INDEX TA_PAYS_fid_source_IDX ON TA_PAYS(FID_SOURCE)
    TABLESPACE INDX_GEO;

CREATE INDEX TA_PAYS_fid_lib_IDX ON TA_PAYS(FID_LIB_)
    TABLESPACE INDX_GEO;
