/*
La table TA_FAMILLE rassemble toutes les familles de libellés.
*/
-- 1. Création de la table
CREATE TABLE G_GEO.TA_FAMILLE(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
	valeur VARCHAR2(255)
);

-- 2. Création des commentaires
COMMENT ON TABLE G_GEO.TA_FAMILLE IS 'Table contenant les familles de libellés.';
COMMENT ON COLUMN G_GEO.TA_FAMILLE.objectid IS 'Identifiant de chaque famille de libellés.';
COMMENT ON COLUMN G_GEO.TA_FAMILLE.valeur IS 'Valeur de chaque famille de libellés.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_FAMILLE
ADD CONSTRAINT TA_FAMILLE_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GEO.TA_FAMILLE TO G_ADMIN_SIG;