/*
Création de la table G_GEO.TA_BPE qui recense les équipements de la base permanente des equipements.
*/
-- 1. Création de la table
CREATE TABLE G_GEO.TA_BPE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    fid_metadonnee NUMBER(38,0)
    );

-- 2. Création des commentaires
COMMENT ON TABLE G_GEO.TA_BPE IS 'Table regroupant les equipements de la Base Permanente des Equipements.';
COMMENT ON COLUMN G_GEO.TA_BPE.objectid IS 'Clé primaire de la table G_GEO.TA_BPE.';
COMMENT ON COLUMN G_GEO.TA_BPE.fid_metadonnee IS 'Clé étrangère vers la table G_GEO.TA_METADONNEE pour connaitre la source de la données.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_BPE
ADD CONSTRAINT TA_BPE_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création de la clé étrangère vers la table ta_metadonnée
ALTER TABLE G_GEO.TA_BPE
ADD CONSTRAINT  TA_BPE_FID_METADONNE_FK
FOREIGN KEY ("FID_METADONNEE")
REFERENCES  G_GEO.TA_METADONNEE ("OBJECTID");


-- 6. Création des index sur les cléfs étrangères.
CREATE INDEX TA_BPE_FID_METADONNE_IDX ON G_GEO.TA_BPE(fid_metadonnee)
TABLESPACE G_ADT_INDX;