
--1 CREATION TABLE TA_PAYS
CREATE TABLE TA_PAYS(
  OBJECTID NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
  NOM_PAYS VARCHAR2 (255), 
  GEOM MDSYS.SDO_GEOMETRY, 
  FID_LIB_TYPE_PAYS NUMBER(38,0),
  FID_SOURCE NUMBER(38,0); 


--2 AJOUT DES COMMENTAIRES
COMMENT ON COLUMN "G_GEO"."TA_PAYS"."OBJECTID" IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN "G_GEO"."TA_PAYS"."NOM_PAYS" IS 'Nom de chaque pays.';
COMMENT ON COLUMN "G_GEO"."TA_PAYS"."GEOM" IS 'Colonne contenant la geometrie des pays. EPSG 3035';
COMMENT ON COLUMN "G_GEO"."TA_PAYS"."FID_SOURCE" IS 'Clé étrangère du champ objectid de la table ta_source.';
COMMENT ON COLUMN "G_GEO"."TA_PAYS"."FID_LIB_TYPE_PAYS" IS 'Clé étrangère du champ objectid de la table ta_libelle.';
COMMENT ON TABLE "G_GEO"."TA_PAYS"  IS 'Table contenant les pays limitrophe au nord la France';


--3 CREATION DE LA CLEF PRIMAIRE
ALTER TABLE 
  TA_PAYS
ADD CONSTRAINT 
  TA_PAYS_PK 
PRIMARY KEY("OBJECTID")
USING INDEX
TABLESPACE "G_ADT_INDX";

-- 4 CREATION METADONNEES SPATIALES EPSG 3035 pour pouvoir inclure tous les pays du monde.
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_PAYS',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', -7143480, 16936923, 0.005),SDO_DIM_ELEMENT('Y', -9160794, 15428321, 0.005)), 
    3035
);

--7 CREATION INDEX SPATIAL SUR LE CHAMP GEOM
CREATE INDEX TA_PAYS_SIDX
ON TA_PAYS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_DATA, work_tablespace=DATA_TEMP');

--8 CREATION DES CLES ETRANGERES
ALTER TABLE TA_PAYS
ADD
CONSTRAINT "TA_PAYS_FID_SOURCE_FK"
FOREIGN KEY (FID_SOURCE)
REFERENCES TA_SOURCE(objectid);

ALTER TABLE TA_PAYS
ADD
CONSTRAINT "TA_PAYS_FID_LIBELLE_FK"
FOREIGN KEY (fid_lib_type_pays)
REFERENCES ta_libelle(objectid);


-- 9. Création des index sur les clés étrangères
CREATE INDEX TA_PAYS_fid_source_IDX ON TA_PAYS(FID_SOURCE)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_PAYS_fid_lib_IDX ON TA_PAYS(FID_LIB_)
    TABLESPACE G_ADT_INDX;
