/*
Table recensant les dates d'acquisition, de millésime et du nom de l'obtenteur de chaque donnée source extérieure à la MEL.
*/

-- 1. Création de la table ta_source
CREATE TABLE G_GEO.TA_DATE_ACQUISITION(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    date_acquisition DATE,
    millesime DATE,
    nom_obtenteur VARCHAR2(200)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_GEO.TA_DATE_ACQUISITION IS 'Table recensant les dates d''acquisition, de millésime et du nom de l''obtenteur de chaque donnée source extérieure à la MEL.';
COMMENT ON COLUMN G_GEO.TA_DATE_ACQUISITION.objectid IS 'Identifiant de chaque objet de la table.';
COMMENT ON COLUMN G_GEO.TA_DATE_ACQUISITION.date_acquisition IS 'Date d''importation de la donnée dans la table - DD/MM/AAAA.';
COMMENT ON COLUMN G_GEO.TA_DATE_ACQUISITION.millesime IS 'Date de création de la donnée - MM/AAAA.';
COMMENT ON COLUMN G_GEO.TA_DATE_ACQUISITION.nom_obtenteur IS 'Nom de la personne ayant inséré la donnée source dans la base.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_DATE_ACQUISITION 
ADD CONSTRAINT TA_DATE_ACQUISITION_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 5. Création du déclencheur d'enregistrement de la date d'insertion de la donnée et du nom de la personne ayant fait cet import, dans la table TA_DATE_ACQUISITION.

CREATE OR REPLACE TRIGGER G_GEO.TA_DATE_ACQUISITION
BEFORE INSERT ON G_GEO.TA_DATE_ACQUISITION
FOR EACH ROW
DECLARE
	username VARCHAR2(200)
BEGIN
	SELECT 
		sys_context('USERENV','OS_USER') 
		INTO username 
	FROM 
		DUAL;
	IF INSERTING THEN
		G_GEO.TA_DATE_ACQUISITION.date_acquisition := sysdate;
		G_GEO.TA_DATE_ACQUISITION.nom_obtenteur := username; 
	END IF;
END;
-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_GEO.TA_DATE_ACQUISITION TO G_ADMIN_SIG;