/*
Creation de la table G_GEO.TA_IRIS_GEOM qui recense les zones IRIS.
*/
-- 1. Création de la table
CREATE TABLE G_GEO.TA_IRIS_GEOM(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
	GEOM SDO_GEOMETRY
	);

-- 2. Création des commentaires des colonnes
COMMENT ON TABLE G_GEO.TA_IRIS_GEOM IS 'Table regroupant les zones IRIS';
COMMENT ON COLUMN G_GEO.TA_IRIS_GEOM.objectid IS 'Clé primaire de la table TA_BPE.';
COMMENT ON COLUMN G_GEO.TA_IRIS_GEOM.geom IS 'Géométrie de la zone IRIS.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_IRIS_GEOM
ADD CONSTRAINT TA_IRIS_GEOM_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_IRIS_GEOM',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TA_IRIS_GEOM_SIDX
ON G_GEO.TA_IRIS_GEOM(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');