/*
Création de la table G_GEO.TA_IRIS qui recense les zones IRIS
*/
-- 1. Création de la table
CREATE TABLE G_GEO.TA_IRIS(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
	fid_code NUMBER(38,0),
	fid_nom NUMBER(38,0),
	fid_lib_type NUMBER(38,0),
	fid_metadonnee NUMBER(38,0),
	fid_iris_geom NUMBER(38,0)
	);

-- 2. Création des commentaires des colonnes
COMMENT ON TABLE G_GEO.ta_iris IS 'Table regroupant les zones IRIS';
COMMENT ON COLUMN G_GEO.ta_iris.objectid IS 'Clé primaire de la table TA_BPE.';
COMMENT ON COLUMN G_GEO.ta_iris.fid_code IS 'Clé étrangère vers la table TA_CODE pour connaitre le code de la zone IRIS.';
COMMENT ON COLUMN G_GEO.ta_iris.fid_nom IS 'Clé étrangère vers la table TA_NOM pour connaitre le nom de la zone IRIS.';
COMMENT ON COLUMN G_GEO.ta_iris.fid_lib_type IS 'Clé étrangère vers la table TA_LIBELLE pour connaitre le type de zone IRIS.';
COMMENT ON COLUMN G_GEO.ta_iris.fid_metadonnee IS 'Clé étrangère vers la table TA_METADONNE pour connaitre la source et le millesime de la zone IRIS.';
COMMENT ON COLUMN G_GEO.ta_iris.fid_iris_geom IS 'Clé étrangère vers la table G_GEO.TA_IRIS_GEOM pour connaitre la géométrie de la zone IRIS.';

-- 3. Création de la clé primaire
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères

-- 4.1. vers la table G_GEO.TA_CODE
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_FID_CODE_FK 
FOREIGN KEY ("FID_CODE")
REFERENCES G_GEO.TA_CODE("OBJECTID");

-- 4.2. vers la table G_GEO.TA_NOM
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_FID_NOM_FK
FOREIGN KEY ("FID_NOM")
REFERENCES G_GEO.TA_NOM("OBJECTID");

-- 4.3. vers la table G_GEO.TA_LIBELLE
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_FID_LIB_TYPE_FK
FOREIGN KEY ("FID_LIB_TYPE")
REFERENCES G_GEO.TA_LIBELLE("OBJECTID");

-- 4.4. vers la table G_GEO.TA_METADONNE
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_FID_METADONNEE_FK
FOREIGN KEY ("FID_METADONNEE")
REFERENCES G_GEO.TA_METADONNEE("OBJECTID");

-- 4.5. vers la table G_GEO.TA_IRIS_GEOM
ALTER TABLE G_GEO.TA_IRIS
ADD CONSTRAINT TA_IRIS_FID_IRIS_GEOM_FK
FOREIGN KEY ("FID_IRIS_GEOM")
REFERENCES G_GEO.TA_IRIS_GEOM("OBJECTID");


-- 5. Création des index sur les cléfs étrangères.
CREATE INDEX TA_IRIS_FID_CODE_IDX ON G_GEO.TA_IRIS(fid_code)
TABLESPACE G_ADT_INDX;

CREATE INDEX TA_IRIS_FID_NOM_IDX ON G_GEO.TA_IRIS(fid_nom)
TABLESPACE G_ADT_INDX;

CREATE INDEX TA_IRIS_FID_LIB_TYPE_IDX ON G_GEO.TA_IRIS(fid_lib_type)
TABLESPACE G_ADT_INDX;

CREATE INDEX TA_IRIS_FID_METADONNEE_IDX ON G_GEO.TA_IRIS(fid_metadonnee)
TABLESPACE G_ADT_INDX;

CREATE INDEX TA_IRIS_FID_IRIS_GEOM_IDX ON G_GEO.TA_IRIS(fid_iris_geom)
TABLESPACE G_ADT_INDX;