/*
Suppression de la structure du schéma G_GEO (tables, déclencheurs, vues, indexes, métadonnées spatiales)
*/

-- 1. Suppression des tables pivots
DROP TABLE G_GEO.TA_FAMILLE_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IDENTIFIANT_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IDENTIFIANT_ZONE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_METADONNEE_RELATION_ORGANISME CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_METADONNEE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ZA_COMMUNES CASCADE CONSTRAINTS;

-- 2. Supression des tables contenants des clés étrangères
DROP TABLE G_GEO.TA_CODE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ZONE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE CASCADE CONSTRAINTS;

-- 3. Suppression des tables ne contenant aucune clé étrangère
DROP TABLE G_GEO.TA_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_NOM CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE_LONG CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ORGANISME CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_SOURCE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_DATE_ACQUISITION CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ECHELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_PROVENANCE CASCADE CONSTRAINTS;

-- 4. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_COMMUNE';

DROP TABLE ta_famille_libelle CASCADE CONSTRAINTS;

DROP TABLE ta_famille CASCADE CONSTRAINTS;

DROP TABLE ta_libelle CASCADE CONSTRAINTS;

DROP TABLE ta_code CASCADE CONSTRAINTS;

DROP TABLE ta_metadonnee CASCADE CONSTRAINTS;

DROP TABLE ta_organisme CASCADE CONSTRAINTS;

DROP TABLE ta_date_acquisition CASCADE CONSTRAINTS;

DROP TABLE ta_source CASCADE CONSTRAINTS;

DROP TABLE ta_provenance CASCADE CONSTRAINTS;

DROP TABLE ta_echelle CASCADE CONSTRAINTS;

DROP TABLE ta_identifiant_commune CASCADE CONSTRAINTS;

DROP TABLE ta_commune CASCADE CONSTRAINTS;
DROP TABLE USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_COMMUNE';

DROP TABLE ta_za_communes CASCADE CONSTRAINTS;

DROP TABLE ta_identifiant_zone_admin CASCADE CONSTRAINTS;

DROP TABLE ta_zone_administrative CASCADE CONSTRAINTS;

DROP TABLE ta_nom CASCADE CONSTRAINTS;

DROP TABLE ta_libelle_court CASCADE CONSTRAINTS;

DROP TABLE ta_correspondance_libelle CASCADE CONSTRAINTS;

DROP TABLE ta_bpe CASCADE CONSTRAINTS;
DROP TABLE USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_BPE';

DROP TABLE ta_bpe_relation_libelle CASCADE CONSTRAINTS;

DROP TABLE ta_bpe_caracteristique_nombre CASCADE CONSTRAINTS;

DROP TABLE ta_bpe_caracteristique CASCADE CONSTRAINTS;
