/*
Suppression de la structure du schéma G_GEO (tables, déclencheurs, vues, indexes, métadonnées spatiales)
*/

DROP TABLE ta_famille_libelle CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_FAMILLE_LIBELLE';

DROP TABLE ta_famille CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_FAMILLE';

DROP TABLE ta_libelle CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_LIBELLE';

DROP TABLE ta_code CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_CODE';

DROP TABLE ta_metadonnee CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_METADONNEE';

DROP TABLE ta_organisme CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_ORGANISME';

DROP TABLE ta_date_acquisition CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_DATE_ACQUISITION';

DROP TABLE ta_source CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_SOURCE';

DROP TABLE ta_provenance CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_PROVENANCE';

DROP TABLE ta_echelle CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_ECHELLE';

DROP TABLE ta_identifiant_commune CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_IDENTIFIANT_COMMUNE';

DROP TABLE ta_commune CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_COMMUNE';

DROP TABLE ta_za_communes CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_ZA_COMMUNES';

DROP TABLE ta_identifiant_zone_admin CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_IDENTIFIANT_ZONE_ADMIN';

DROP TABLE ta_zone_administrative CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_ZONE_ADMINISTRATIVE';

DROP TABLE ta_nom CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_NOM';