/*
Suppression de la structure du schéma G_GEO (tables, déclencheurs, vues, indexes, métadonnées spatiales)
*/

-- 1. Suppression des tables pivots
DROP TABLE G_GEO.TA_FAMILLE_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE_RELATION CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE_CORRESPONDANCE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IDENTIFIANT_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IDENTIFIANT_ZONE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_METADONNEE_RELATION_ORGANISME CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_METADONNEE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ZA_COMMUNES CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE_RELATION_GEOM CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE_CARACTERISTIQUE_QUANTITATIVE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE_CARACTERISTIQUE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE_RELATION_CODE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_GG_POINT_VIGILANCE_PERMIS_CONSTRUIRE CASCADE CONSTRAINTS;

-- 2. Supression des tables contenants des clés étrangères
DROP TABLE G_GEO.TA_CODE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ZONE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IRIS CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_GG_POINT_VIGILANCE_AUDIT CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_GG_POINT_VIGILANCE CASCADE CONSTRAINTS;

-- 3. Suppression des tables ne contenant aucune clé étrangère
DROP TABLE G_GEO.TA_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_NOM CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE_LONG CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_LIBELLE_COURT CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ORGANISME CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_SOURCE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_DATE_ACQUISITION CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_ECHELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_PROVENANCE CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_BPE_GEOM CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_IRIS_GEOM CASCADE CONSTRAINTS;
DROP TABLE G_GEO.TA_GG_PERMIS_CONSTRUIRE CASCADE CONSTRAINTS;

-- 4. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_COMMUNE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_BPE_GEOM';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_IRIS_GEOM';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_GG_POINT_VIGILANCE';
COMMIT;