/*
Code permettant de vider le schéma G_GESTIONGEO de ses objets (code DDL)
*/
-- 1. TABLES FINALES
-- Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_GG_GEO';
COMMIT;
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'V_GG_POINT';
COMMIT;
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'V_GG_DOSSIER_GEO';
COMMIT;

-- Suppression des tables
DROP TABLE G_GESTIONGEO.TA_GG_GEO CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_DOSSIER CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_DOS_NUM CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_FME_MESURE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_DOMAINE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_CLASSE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_URL_FILE CASCADE CONSTRAINTS;


-- Suppression des Vues
DROP VIEW G_GESTIONGEO.V_GG_POINT;
DROP VIEW G_GESTIONGEO.V_GG_DOSSIER_GEO;

-- Suppression des séquences d'incrémentation
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_GEO_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_DOSSIER_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_DOS_NUM_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_FAMILLE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_URL_FILE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_CLASSE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_DOMAINE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_FME_MESURE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID;
DROP SEQUENCE G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID;