/*
Code permettant de vider le schéma G_GESTIONGEO de ses objets (code DDL)
*/
-- 1. TABLES FINALES
-- Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_GG_GEO';
COMMIT;
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'V_GG_POINT';
COMMIT;
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'V_GG_DOSSIER_GEO';
COMMIT;

-- Suppression des tables
DROP TABLE G_GESTIONGEO.TA_GG_GEO CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_DOSSIER CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_DOS_NUM CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_ETAT CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TA_GG_URL_FILE CASCADE CONSTRAINTS;

-- Suppression des Vues
DROP VIEW G_GESTIONGEO.V_GG_POINT;
DROP VIEW G_GESTIONGEO.V_GG_DOSSIER_GEO;