-- Creation du trigger B_IXX_TA_RTGE_LINEAIRE_LOG_PK d'incrematation de clé primaire de la table TA_RTGE_LINEAIRE_PRODUCTION_LOG
CREATE OR REPLACE TRIGGER B_IXX_TA_RTGE_LINEAIRE_PRODUCTION_LOG_PK
BEFORE INSERT ON TA_RTGE_LINEAIRE_PRODUCTION_LOG FOR EACH ROW
BEGIN
    :new.OBJECTID := SEQ_TA_RTGE_LINEAIRE_PRODUCTION_LOG_OBJECTID.nextval;
END;

/
