--------------------------------------------
-- CREATION_B_IUD_TA_RTGE_LINEAIRE_SOMMET --
--------------------------------------------

CREATE OR REPLACE TRIGGER G_GESTIONGEO.B_IUD_TA_RTGE_LINEAIRE_SOMMET
BEFORE INSERT OR UPDATE OR DELETE ON G_GESTIONGEO.TA_RTGE_LINEAIRE
FOR EACH ROW
DECLARE
BEGIN

    IF INSERTING THEN
    	MERGE INTO G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET a
    	USING
    		(
			SELECT
			    a.objectid AS IDENTIFIANT_OBJET,
			    a.FID_NUMERO_DOSSIER AS FID_NUMERO_DOSSIER,
			    a.FID_IDENTIFIANT_TYPE AS FID_IDENTIFIANT_TYPE,
			    b.LIBELLE_COURT AS LIBELLE_COURT_TYPE,
			    b.LIBELLE_LONG AS LIBELLE_TYPE,
			    a.DECALAGE_DROITE AS DECALAGE_DROITE,
			    a.DECALAGE_GAUCHE AS DECALAGE_GAUCHE,
			    a.FID_PNOM_CREATION AS FID_PNOM_CREATION,
			    a.DATE_CREATION AS DATE_CREATION,
			    a.FID_PNOM_MODIFICATION AS FID_PNOM_MODIFICATION,
			    a.DATE_MODIFICATION AS DATE_MODIFICATION,
			    CAST(t.z AS NUMBER(9,2)) AS COORD_Z,
			    SDO_GEOMETRY(2001, 2154,
				    SDO_POINT_TYPE(t.X,t.Y,NULL),
				    NULL, NULL) AS GEOM
			FROM
			    G_GESTIONGEO.TA_RTGE_LINEAIRE a
			INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.objectid,
			TABLE
			    (SDO_UTIL.GETVERTICES(a.GEOM)) t
			WHERE
				 a.OBJECTID = :new.objectid
			)b
		ON (a.IDENTIFIANT_OBJET = b.IDENTIFIANT_OBJET
			AND a.FID_NUMERO_DOSSIER = b.FID_NUMERO_DOSSIER
			AND a.FID_IDENTIFIANT_TYPE = b.FID_IDENTIFIANT_TYPE
			AND a.LIBELLE_COURT_TYPE = b.LIBELLE_COURT_TYPE
			AND a.LIBELLE_TYPE = b.LIBELLE_TYPE
			AND a.DECALAGE_DROITE = b.DECALAGE_DROITE
			AND a.DECALAGE_GAUCHE = b.DECALAGE_GAUCHE
			AND a.FID_PNOM_CREATION = b.FID_PNOM_CREATION
			AND a.DATE_CREATION = b.DATE_CREATION
			AND a.FID_PNOM_MODIFICATION = b.FID_PNOM_MODIFICATION
			AND a.DATE_MODIFICATION = b.DATE_MODIFICATION
			AND a.COORD_Z = b.COORD_Z)
		WHEN NOT MATCHED THEN 
		INSERT (a.IDENTIFIANT_OBJET, a.FID_NUMERO_DOSSIER, a.FID_IDENTIFIANT_TYPE, a.LIBELLE_COURT_TYPE, a.LIBELLE_TYPE, a.DECALAGE_DROITE, a.DECALAGE_GAUCHE, a.FID_PNOM_CREATION, a.DATE_CREATION, a.FID_PNOM_MODIFICATION, a.DATE_MODIFICATION, a.COORD_Z, a.GEOM)
		VALUES (b.IDENTIFIANT_OBJET, b.FID_NUMERO_DOSSIER, b.FID_IDENTIFIANT_TYPE, b.LIBELLE_COURT_TYPE, b.LIBELLE_TYPE, b.DECALAGE_DROITE, b.DECALAGE_GAUCHE, b.FID_PNOM_CREATION, b.DATE_CREATION, b.FID_PNOM_MODIFICATION, b.DATE_MODIFICATION, b.COORD_Z, b.GEOM)
		;

    ELSE
        IF UPDATING THEN
        	DELETE FROM G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET WHERE IDENTIFIANT_OBJET = :old.objectid;

    	MERGE INTO G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET a
    	USING
    		(
			SELECT
			    a.objectid AS IDENTIFIANT_OBJET,
			    a.FID_NUMERO_DOSSIER AS FID_NUMERO_DOSSIER,
			    a.FID_IDENTIFIANT_TYPE AS FID_IDENTIFIANT_TYPE,
			    b.LIBELLE_COURT AS LIBELLE_COURT_TYPE,
			    b.LIBELLE_LONG AS LIBELLE_TYPE,
			    a.DECALAGE_DROITE AS DECALAGE_DROITE,
			    a.DECALAGE_GAUCHE AS DECALAGE_GAUCHE,
			    a.FID_PNOM_CREATION AS FID_PNOM_CREATION,
			    a.DATE_CREATION AS DATE_CREATION,
			    a.FID_PNOM_MODIFICATION AS FID_PNOM_MODIFICATION,
			    a.DATE_MODIFICATION AS DATE_MODIFICATION,
			    CAST(t.z AS NUMBER(9,2)) AS COORD_Z,
			    SDO_GEOMETRY(2001, 2154,
				    SDO_POINT_TYPE(t.X,t.Y,NULL),
				    NULL, NULL) AS GEOM
			FROM
			    G_GESTIONGEO.TA_RTGE_LINEAIRE a
			INNER JOIN G_GESTIONGEO.TA_GG_CLASSE b ON a.FID_IDENTIFIANT_TYPE = b.objectid,
			TABLE
			    (SDO_UTIL.GETVERTICES(a.GEOM)) t
			WHERE
				 a.OBJECTID = :new.objectid
			)b
		ON (a.IDENTIFIANT_OBJET = b.IDENTIFIANT_OBJET
			AND a.FID_NUMERO_DOSSIER = b.FID_NUMERO_DOSSIER
			AND a.FID_IDENTIFIANT_TYPE = b.FID_IDENTIFIANT_TYPE
			AND a.LIBELLE_COURT_TYPE = b.LIBELLE_COURT_TYPE
			AND a.LIBELLE_TYPE = b.LIBELLE_TYPE
			AND a.DECALAGE_DROITE = b.DECALAGE_DROITE
			AND a.DECALAGE_GAUCHE = b.DECALAGE_GAUCHE
			AND a.FID_PNOM_CREATION = b.FID_PNOM_CREATION
			AND a.DATE_CREATION = b.DATE_CREATION
			AND a.FID_PNOM_MODIFICATION = b.FID_PNOM_MODIFICATION
			AND a.DATE_MODIFICATION = b.DATE_MODIFICATION
			AND a.COORD_Z = b.COORD_Z)
		WHEN NOT MATCHED THEN 
		INSERT (a.IDENTIFIANT_OBJET, a.FID_NUMERO_DOSSIER, a.FID_IDENTIFIANT_TYPE, a.LIBELLE_COURT_TYPE, a.LIBELLE_TYPE, a.DECALAGE_DROITE, a.DECALAGE_GAUCHE, a.FID_PNOM_CREATION, a.DATE_CREATION, a.FID_PNOM_MODIFICATION, a.DATE_MODIFICATION, a.COORD_Z, a.GEOM)
		VALUES (b.IDENTIFIANT_OBJET, b.FID_NUMERO_DOSSIER, b.FID_IDENTIFIANT_TYPE, b.LIBELLE_COURT_TYPE, b.LIBELLE_TYPE, b.DECALAGE_DROITE, b.DECALAGE_GAUCHE, b.FID_PNOM_CREATION, b.DATE_CREATION, b.FID_PNOM_MODIFICATION, b.DATE_MODIFICATION, b.COORD_Z, b.GEOM)
		;

        END IF;
    END IF;


    IF DELETING THEN
    
        DELETE FROM G_GESTIONGEO.TA_RTGE_LINEAIRE_SOMMET WHERE IDENTIFIANT_OBJET = :old.objectid;
    
	END IF;

    EXCEPTION
        WHEN OTHERS THEN
            mail.sendmail('rjault@lillemetropole.fr',SQLERRM,'ERREUR TRIGGER - G_GESTIONGEO.B_IUD_TA_RTGE_LINEAIRE_SOMMET','rjault@lillemetropole.fr');
END;

/
