---------------------------------------------------
-- CREATION_A_IUD_TA_RTGE_POINT_PRODUCTION_LOG_2 --
---------------------------------------------------

/*
Trigger de sauvegarde des modifictions effectuees sur la table G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION dans la table G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG
*/
CREATE OR REPLACE TRIGGER G_GESTIONGEO.A_IUD_TA_RTGE_POINT_PRODUCTION_LOG
AFTER INSERT OR UPDATE OR DELETE ON G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION
FOR EACH ROW
DECLARE
V_OBJECTID NUMBER(38,0);
USERNUMBER NUMBER(38,0);
NUMBER_INSERTION NUMBER(38,0);
NUMBER_MODIFICATION NUMBER(38,0);
NUMBER_SUPPRESSION NUMBER(38,0);


BEGIN
-- selection du numero de l''agent dans la variable USERNUMBER
SELECT
	COALESCE(a.OBJECTID,99996) INTO USERNUMBER 
FROM 
	G_GESTIONGEO.TA_GG_AGENT a
	RIGHT JOIN (
				SELECT
					SYS_CONTEXT('USERENV','OS_USER') AS NOM 
				FROM 
					DUAL
				)b
				ON a.pnom = b.nom
;

-- selection de l'objectid du libelle insertion dans la variable NUMBER_INSERTION
SELECT 
	a.OBJECTID INTO NUMBER_INSERTION 
FROM 
	G_GESTIONGEO.TA_GG_LIBELLE a
	INNER JOIN G_GESTIONGEO.TA_GG_LIBELLE_LONG b ON b.OBJECTID = a.FID_LIBELLE_LONG
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE_LIBELLE c ON c.FID_LIBELLE = a.OBJECTID
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE d ON d.OBJECTID = c.FID_FAMILLE
WHERE
	TRIM(LOWER(b.valeur)) = TRIM(LOWER('insertion'))
	AND
	TRIM(LOWER(d.libelle)) = TRIM(LOWER('type d''action'));

-- selection de l'objectid du libelle modification dans la variable NUMBER_MODIFICATION
SELECT 
	a.OBJECTID INTO NUMBER_MODIFICATION 
FROM 
	G_GESTIONGEO.TA_GG_LIBELLE a
	INNER JOIN G_GESTIONGEO.TA_GG_LIBELLE_LONG b ON b.OBJECTID = a.FID_LIBELLE_LONG
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE_LIBELLE c ON c.FID_LIBELLE = a.OBJECTID
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE d ON d.OBJECTID = c.FID_FAMILLE
WHERE
	TRIM(LOWER(b.valeur)) = TRIM(LOWER('modification'))
	AND
	TRIM(LOWER(d.libelle)) = TRIM(LOWER('type d''action'));

-- selection de l'objectid du libelle modification dans la variable NUMBER_SUPPRESSION
SELECT 
	a.OBJECTID INTO NUMBER_SUPPRESSION 
FROM 
	G_GESTIONGEO.TA_GG_LIBELLE a
	INNER JOIN G_GESTIONGEO.TA_GG_LIBELLE_LONG b ON b.OBJECTID = a.FID_LIBELLE_LONG
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE_LIBELLE c ON c.FID_LIBELLE = a.OBJECTID
	INNER JOIN G_GESTIONGEO.TA_GG_FAMILLE d ON d.OBJECTID = c.FID_FAMILLE
WHERE
	TRIM(LOWER(b.valeur)) = TRIM(LOWER('suppression'))
	AND
	TRIM(LOWER(d.libelle)) = TRIM(LOWER('type d''action'));




-- TRIGGER
	IF INSERTING THEN

        INSERT INTO G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG(GEOM, IDENTIFIANT_OBJET, FID_NUMERO_DOSSIER, FID_IDENTIFIANT_TYPE, TEXTE, LONGUEUR, LARGEUR, ORIENTATION, HAUTEUR, INCLINAISON, FID_PNOM_ACTION, DATE_ACTION, FID_TYPE_ACTION, FID_IDENTIFIANT_OBJET_INTEGRATION)
            VALUES(
	            	:new.GEOM,
					:new.objectid,
					:new.FID_NUMERO_DOSSIER,
					:new.FID_IDENTIFIANT_TYPE,
					:new.TEXTE,
					:new.LONGUEUR,
					:new.LARGEUR,
					:new.ORIENTATION,
					:new.HAUTEUR,
					:new.INCLINAISON,
					USERNUMBER,
					SYSDATE,
					NUMBER_INSERTION,
					:new.FID_IDENTIFIANT_OBJET_INTEGRATION
				);

    ELSE

    IF UPDATING THEN -- En cas de modification on insère les valeurs de la table TA_RTGE_POINT_LOG, le numéro d'agent correspondant à l'utilisateur, la date de modification et le type de action.
        
        INSERT INTO G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG(GEOM, IDENTIFIANT_OBJET, FID_NUMERO_DOSSIER, FID_IDENTIFIANT_TYPE, TEXTE, LONGUEUR, LARGEUR, ORIENTATION, HAUTEUR, INCLINAISON, FID_PNOM_ACTION, DATE_ACTION, FID_TYPE_ACTION, FID_IDENTIFIANT_OBJET_INTEGRATION)
            VALUES(
	            	:old.GEOM,
					:old.objectid,
					:old.FID_NUMERO_DOSSIER,
					:old.FID_IDENTIFIANT_TYPE,
					:old.TEXTE,
					:old.LONGUEUR,
					:old.LARGEUR,
					:old.ORIENTATION,
					:old.HAUTEUR,
					:old.INCLINAISON,
					USERNUMBER,
					SYSDATE,
					NUMBER_MODIFICATION,
					:old.FID_IDENTIFIANT_OBJET_INTEGRATION
				);

    END IF;
    	END IF;

    IF DELETING THEN -- En cas de suppression on insère les valeurs de la table TA_RTGE_POINT_LOG, le numéro d'agent correspondant à l'utilisateur, la date de suppression et le type de action.
            
            INSERT INTO G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG(GEOM, IDENTIFIANT_OBJET, FID_NUMERO_DOSSIER, FID_IDENTIFIANT_TYPE, TEXTE, LONGUEUR, LARGEUR, ORIENTATION, HAUTEUR, INCLINAISON, FID_PNOM_ACTION, DATE_ACTION, FID_TYPE_ACTION, FID_IDENTIFIANT_OBJET_INTEGRATION)
            	VALUES(
	            	:old.GEOM,
					:old.objectid,
					:old.FID_NUMERO_DOSSIER,
					:old.FID_IDENTIFIANT_TYPE,
					:old.TEXTE,
					:old.LONGUEUR,
					:old.LARGEUR,
					:old.ORIENTATION,
					:old.HAUTEUR,
					:old.INCLINAISON,
					USERNUMBER,
					SYSDATE,
					NUMBER_SUPPRESSION,
					:old.FID_IDENTIFIANT_OBJET_INTEGRATION
				);
    END IF;

    EXCEPTION
        WHEN OTHERS THEN
            mail.sendmail('rjault@lillemetropole.fr',SQLERRM,'ERREUR TRIGGER - G_GESTIONGEO.A_IUD_TA_RTGE_POINT_PRODUCTION_LOG','rjault@lillemetropole.fr');
END;

/
