-- Creation du trigger d'incrementaion B_IXX_TA_IC_LINEAIRE_LOG_PK de clé primaire de la table TA_IC_LINEAIRE_LOG
CREATE OR REPLACE TRIGGER B_IXX_TA_IC_LINEAIRE_LOG_PK
BEFORE INSERT ON TA_IC_LINEAIRE_LOG FOR EACH ROW
BEGIN
    :new.OBJECTID := SEQ_TA_IC_LINEAIRE_LOG.nextval;
END;

/
