/*
Désactivation de toutes les contraintes, index, triggers
*/

-- Désactivation des triggers
ALTER TRIGGER A_IUD_TA_GG_DOSSIER_LOG DISABLE;
ALTER TRIGGER A_IUD_TA_GG_GEO_LOG DISABLE;
ALTER TRIGGER A_IXX_TA_GG_GEO DISABLE;
ALTER TRIGGER B_UXX_TA_GG_DOSSIER DISABLE;

-- Désactivation des contraintes et suppression des index
ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER DISABLE CONSTRAINT TA_GG_DOSSIER_FID_PERIMETRE_FK;
ALTER TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE DISABLE CONSTRAINT TA_GG_FME_FILTRE_SUR_LIGNE_FID_CLASSE_FK;
DROP INDEX TA_GG_GEO_SIDX;
DROP INDEX TA_GG_GEO_SURFACE_IDX;
DROP INDEX TA_GG_GEO_CODE_INSEE_IDX;
DROP INDEX TA_GG_DOSSIER_FID_ETAT_AVANCEMENT_IDX;
DROP INDEX TA_GG_DOSSIER_FID_FAMILLE_IDX;
DROP INDEX TA_GG_DOSSIER_FID_PERIMETRE_IDX;
DROP INDEX TA_GG_DOSSIER_FID_PNOM_DATE_CREATION_IDX;
DROP INDEX TA_GG_DOSSIER_FID_PNOM_DATE_MODIFICATION_IDX;
DROP INDEX TA_GG_DOSSIER_MAITRE_OUVRAGE_IDX;
DROP INDEX TA_GG_DOSSIER_RESPONSABLE_LEVE_IDX;
DROP INDEX TA_GG_DOSSIER_ENTREPRISE_TRAVAUX_IDX;
DROP INDEX TA_GG_REPERTOIRE_REPERTOIRE_IDX;
DROP INDEX TA_GG_REPERTOIRE_PROTOCOLE_IDX;
DROP INDEX TA_GG_DOS_NUM_DOS_NUM_IDX;
DROP INDEX TA_GG_DOS_NUM_FID_DOSSIER_IDX;

/

