CREATE TABLE "GEO"."TA_GG_DOSSIER" (
	"ID_DOS" NUMBER NOT NULL ENABLE,
	"SRC_ID" NUMBER NOT NULL ENABLE,
	"ETAT_ID" NUMBER NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"FAM_ID" NUMBER DEFAULT 1,
	"DOS_DC" DATE NOT NULL ENABLE,
	"DOS_PRECISION" VARCHAR2(100 BYTE),
	"DOS_DMAJ" DATE,
	"DOS_RQ" VARCHAR2(2048 BYTE),
	"DOS_DT_FIN" DATE,
	"DOS_PRIORITE" NUMBER(1,0) NOT NULL ENABLE,
	"DOS_IDPERE" NUMBER,
	"DOS_DT_DEB_TR" DATE,
	"DOS_DT_FIN_TR" DATE,
	"DOS_DT_CMD_SAI" DATE,
	"DOS_INSEE" NUMBER(5,0),
	"DOS_VOIE" NUMBER(8,0),
	"DOS_MAO" VARCHAR2(200 BYTE),
	"DOS_ENTR" VARCHAR2(200 BYTE),
	"DOS_URL_FILE" VARCHAR2(200 BYTE),
	"ORDER_ID" NUMBER(10,0),
	"DOS_NUM" NUMBER,
	"DOS_NUM_SHORT" NUMBER(4,0),
	"DOS_OLD_ID" VARCHAR2(8 BYTE),
	"DOS_DT_DEB_LEVE" DATE,
	"DOS_DT_FIN_LEVE" DATE,
	"DOS_DT_PREV" DATE,
	 CONSTRAINT "PK_TA_GG_DOSSIER" PRIMARY KEY ("ID_DOS")
		TABLESPACE "INDX_GEO"  ENABLE,
 	CONSTRAINT "EU_TA_GG_DOSSIER" UNIQUE ("DOS_NUM")
		TABLESPACE "INDX_GEO"  ENABLE,
	CONSTRAINT "FK_TA_GG_DO_ETAT_GEST_TA_GG_ET" FOREIGN KEY ("ETAT_ID")	REFERENCES "GEO"."TA_GG_ETAT" ("ETAT_ID") ENABLE,
	CONSTRAINT "FK_TA_GG_DO_FAMILLE_TA_GG_FA" FOREIGN KEY ("FAM_ID") REFERENCES "GEO"."TA_GG_FAMILLE" ("FAM_ID") ENABLE,
	CONSTRAINT "FK_TA_GG_DO_SRC_GESTI_TA_GG_SO" FOREIGN KEY ("SRC_ID") REFERENCES "GEO"."TA_GG_SOURCE" ("SRC_ID") ENABLE
 )
TABLESPACE "DATA_GEO" ;

COMMENT ON TABLE "GEO"."TA_GG_DOSSIER"  IS 'Table principale. Chaque dossier correspond à un numéro de chantier pour le plan topo et IC';

CREATE INDEX "GEO"."ETAT_GESTION_FK" ON "GEO"."TA_GG_DOSSIER" ("ETAT_ID") TABLESPACE "INDX_GEO" ;

CREATE INDEX "GEO"."FAMILLE_FK" ON "GEO"."TA_GG_DOSSIER" ("FAM_ID") TABLESPACE "INDX_GEO" ;

CREATE INDEX "GEO"."PROFIL_FK" ON "GEO"."TA_GG_DOSSIER" ("USER_ID") TABLESPACE "INDX_GEO" ;

CREATE INDEX "GEO"."SRC_GESTION_FK" ON "GEO"."TA_GG_DOSSIER" ("SRC_ID") TABLESPACE "INDX_GEO" ;

CREATE OR REPLACE TRIGGER "GEO"."TA_DOSSIER_SHORTNUM"
		AFTER INSERT
		ON TA_GG_DOSSIER
		FOR EACH ROW
	DECLARE
		num_short number;
		num_long number;
		insee number;
	BEGIN
		insee := :OLD.DOS_INSEE;

select nvl(max(dos_num_short),0)+1 into num_short from ta_gg_dossier where dos_dc <= add_months(trunc(sysdate, 'YEAR'), 12)-1/24/60/60 and dos_dc >= trunc(sysdate, 'YEAR') AND dos_insee = insee;

-- UPDATE TA_GG_DOSSIER SET DOS_NUM_SHORT=num_short WHERE ID_DOS = :NEW.ID_DOS;

END TA_DOSSIER_SHORTNUM;
/
ALTER TRIGGER "GEO"."TA_DOSSIER_SHORTNUM" DISABLE;

CREATE OR REPLACE TRIGGER "GEO"."TA_GG_DOSSIER"
BEFORE INSERT ON "GEO"."TA_GG_DOSSIER"
FOR EACH ROW
BEGIN
	select TA_GG_DOSSIER_SEQ.nextval into :new.ID_DOS from dual;
END;
/
ALTER TRIGGER "GEO"."TA_GG_DOSSIER" DISABLE;
