SET SERVEROUTPUT ON
DECLARE
    v_id NUMBER(38,0);
BEGIN

	SAVEPOINT MAJ_SEQUENCE;
	--Modification de l'id de départ de la clé primaire de TA_GG_DOMAINE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOMAINE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOMAINE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOMAINE_OBJECTID START WITH ' || v_id || ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOMAINE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOMAINE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_DOSSIER
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOSSIER a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOSSIER_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOSSIER_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOSSIER_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOSSIER_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_GEO
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_GEO a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_GEO_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_GEO_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_GEO_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_GEO_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_DOS_NUM
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOS_NUM a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOS_NUM_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOS_NUM_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOS_NUM_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOS_NUM_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_ETAT_AVANCEMENT
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FAMILLE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FAMILLE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FAMILLE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FAMILLE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FAMILLE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FAMILLE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FICHIER 
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FICHIER a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FICHIER_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FICHIER_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FICHIER_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FICHIER_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_CLASSE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_CLASSE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_CLASSE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_CLASSE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_CLASSE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_CLASSE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FME_DECALAGE_ABSCISSE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FME_DECALAGE_ABSCISSE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_DECALAGE_ABSCISSE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FME_MESURE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FME_MESURE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FME_MESURE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FME_MESURE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_MESURE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_MESURE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FME_FILTRE_SUR_LIGNE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID TO G_GESTIONGEO_RW';

	-- Réactivation des triggers
	EXECUTE IMMEDIATE 'ALTER TRIGGER A_IUD_TA_GG_DOSSIER_LOG ENABLE';
	EXECUTE IMMEDIATE 'ALTER TRIGGER A_IUD_TA_GG_GEO_LOG ENABLE';
	EXECUTE IMMEDIATE 'ALTER TRIGGER A_IXX_TA_GG_GEO ENABLE';
	EXECUTE IMMEDIATE 'ALTER TRIGGER B_UXX_TA_GG_DOSSIER ENABLE';

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('L''erreur ' || SQLCODE || 'est survenue. Un rollback a été effectué : ' || SQLERRM(SQLCODE));
        ROLLBACK TO MAJ_SEQUENCE;
END;