SET SERVEROUTPUT ON
DECLARE
    v_id NUMBER(38,0);
BEGIN

	SAVEPOINT MAJ_SEQUENCE;
	--Modification de l'id de départ de la clé primaire de TA_GG_DOMAINE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOMAINE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOMAINE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOMAINE_OBJECTID START WITH ' || v_id || ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOMAINE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOMAINE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_DOSSIER
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOSSIER a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOSSIER_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOSSIER_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOSSIER_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOSSIER_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_GEO
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_GEO a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_GEO_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_GEO_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_GEO_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_GEO_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_DOS_NUM
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_DOS_NUM a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_DOS_NUM_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_DOS_NUM_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOS_NUM_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_DOS_NUM_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_ETAT_AVANCEMENT
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_ETAT_AVANCEMENT_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FAMILLE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FAMILLE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FAMILLE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FAMILLE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FAMILLE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FAMILLE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FICHIER 
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FICHIER a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FICHIER_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FICHIER_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FICHIER_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FICHIER_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_CLASSE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_CLASSE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_CLASSE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_CLASSE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_CLASSE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_CLASSE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FME_MESURE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FME_MESURE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FME_MESURE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FME_MESURE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_MESURE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_MESURE_OBJECTID TO G_GESTIONGEO_RW';

	-- Modification de l'id de départ de la clé primaire de TA_GG_FME_FILTRE_SUR_LIGNE
	SELECT
	    MAX(a.OBJECTID)+1
	    INTO v_id
	FROM
	    G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE a;

	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID START WITH ' ||v_id|| ' INCREMENT BY 1';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID TO G_GESTIONGEO_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_GESTIONGEO.SEQ_TA_GG_FME_FILTRE_SUR_LIGNE_OBJECTID TO G_GESTIONGEO_RW';

	-- Réactivation des triggers
	--EXECUTE IMMEDIATE 'ALTER TRIGGER A_IUD_TA_GG_DOSSIER_LOG ENABLE';
	--EXECUTE IMMEDIATE 'ALTER TRIGGER A_IUD_TA_GG_GEO_LOG ENABLE';
	EXECUTE IMMEDIATE 'ALTER TRIGGER A_IXX_TA_GG_GEO ENABLE';
	EXECUTE IMMEDIATE 'ALTER TRIGGER B_UXX_TA_GG_DOSSIER ENABLE';

	-- 16. Réactivation des triggers, clés étrangères, contraintes, index et suppression des champs temporaires
	-- 16.1. Contrainte de clé étrangère de TA_GG_DOSSIER
	EXECUTE IMMEDIATE 'ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER ENABLE CONSTRAINT TA_GG_DOSSIER_FID_PERIMETRE_FK';
	EXECUTE IMMEDIATE 'ALTER TABLE G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE ENABLE CONSTRAINT TA_GG_FME_FILTRE_SUR_LIGNE_FID_CLASSE_FK';

	-- 16.5. Recréation des index de TA_GG_DOS_NUM
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_DOS_NUM_DOS_NUM_IDX" ON G_GESTIONGEO.TA_GG_DOS_NUM ("DOS_NUM") TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_DOS_NUM_FID_DOSSIER_IDX" ON G_GESTIONGEO.TA_GG_DOS_NUM("FID_DOSSIER")TABLESPACE G_ADT_INDX';

	-- 16.6. Recréation des index de TA_GG_GEO
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_GEO_SIDX ON G_GESTIONGEO.TA_GG_GEO(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS(''sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP'')';
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_GEO_SURFACE_IDX" ON G_GESTIONGEO.TA_GG_GEO ("SURFACE") TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_GEO_CODE_INSEE_IDX" ON G_GESTIONGEO.TA_GG_GEO ("CODE_INSEE") TABLESPACE G_ADT_INDX';

	-- 16.7. Recréation des index de TA_GG_DOSSIER
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_FID_ETAT_AVANCEMENT_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("FID_ETAT_AVANCEMENT")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_FID_FAMILLE_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("FID_FAMILLE")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_FID_PERIMETRE_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("FID_PERIMETRE")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_FID_PNOM_DATE_CREATION_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("FID_PNOM_CREATION")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_FID_PNOM_DATE_MODIFICATION_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("FID_PNOM_MODIFICATION")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_MAITRE_OUVRAGE_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("MAITRE_OUVRAGE")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_RESPONSABLE_LEVE_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("RESPONSABLE_LEVE")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_DOSSIER_ENTREPRISE_TRAVAUX_IDX ON G_GESTIONGEO.TA_GG_DOSSIER("ENTREPRISE_TRAVAUX")TABLESPACE G_ADT_INDX';

	-- 16.8. Recréation des index de TA_GG_REPERTOIRE
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_REPERTOIRE_REPERTOIRE_IDX" ON G_GESTIONGEO.TA_GG_REPERTOIRE ("REPERTOIRE")TABLESPACE G_ADT_INDX';
	EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_REPERTOIRE_PROTOCOLE_IDX" ON G_GESTIONGEO.TA_GG_REPERTOIRE ("PROTOCOLE")TABLESPACE G_ADT_INDX';

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('L''erreur ' || SQLCODE || 'est survenue. Un rollback a été effectué : ' || SQLERRM(SQLCODE));
        ROLLBACK TO MAJ_SEQUENCE;
END;