SET SERVEROUTPUT ON
DECLARE
	v_id NUMBER(38,0);
BEGIN
/*
Code permettant d'insérer les données gestiongeo des tables temporaires dans les tables finales suite aux corrections des données.

SOMMAIRE
1. Désactivation des triggers, clés étrangères, contraintes et index ;
2. Remplissage de la table TA_GG_AGENT ;
3. Remplissage de la table TA_GG_FAMILLE ;
4. Remplissage de la table TA_GG_ETAT ;
5. Remplissage de la table TA_GG_GEO ;
6. Remplissage de la table TA_GG_DOSSIER ;
7. Remplissage de la table TA_GG_GEO ;
	7.1. Modification de l'id de départ de ID_DOS de TA_GG_DOSSIER ;
	7.2. Modification de l'id de départ de ID_GEOM de TA_GG_GEO ;
8. Réactivation des triggers, clés étrangères, contraintes et index ;
	8.1. Contrainte de clé étrangère de TA_GG_GEO ;
	8.2. Réactivation du trigger B_IUX_TA_GG_DOSSIER ;
	8.3. Recréation des index de TA_GG_AGENT ;
	8.4. Recréation des index de TA_GG_FAMILLE ;
	8.5. Recréation des index de TA_GG_GEO ;
	8.6. Recréation des index de TA_GG_URL_FILE ;
*/

SAVEPOINT POINT_SAUVEGARDE_REMPLISSAGE;

--1. Désactivation des triggers, clés étrangères et index
/* Prérequis :
- Désactivation du trigger B_IUX_TA_GG_DOSSIER ;
- Désactivation de la clé étrangère TA_GG_GEO_ID_DOS_FK ;
- Désactivation des index pour accélérer l'insertion des données
*/

EXECUTE IMMEDIATE 'ALTER TABLE G_GESTIONGEO.TA_GG_DOSSIER DISABLE CONSTRAINT TA_GG_DOSSIER_FID_PERIMETRE_FK';
EXECUTE IMMEDIATE 'ALTER TRIGGER A_IXX_TA_GG_GEO DISABLE';
EXECUTE IMMEDIATE 'ALTER TRIGGER B_UXX_TA_GG_DOSSIER DISABLE';
EXECUTE IMMEDIATE 'DROP INDEX TA_GG_FAMILLE_VALIDITE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_GG_GEO_SIDX';

-- 2. Remplissage de la table TA_GG_AGENT
-- Insertion des pnoms des agents utilisant gestiongeo
/*INSERT INTO G_GESTIONGEO.TA_GG_AGENT(OBJECTID, PNOM, VALIDITE)
SELECT
	SRC_ID, 
	TRIM(SRC_LIBEL), 
	SRC_VAL
FROM
	G_GESTIONGEO.TEMP_TA_GG_AGENT;

-- Insertion des pnoms génériques nécessaires pour des cas bien particuliers
MERGE INTO G_GESTIONGEO.TA_GG_AGENT a
USING(
	SELECT
		88888 AS OBJECTID,
		'plusieurs gestionnaires' AS PNOM,
		1 AS VALIDITE
	FROM
		DUAL
	UNION ALL
	SELECT
		77777 AS OBJECTID,
		'pas encore de gestionnaire' AS PNOM,
		1 AS VALIDITE
	FROM
		DUAL
	UNION ALL
	SELECT
		99999 AS OBJECTID,
		'migration données' AS PNOM,
		1 AS VALIDITE
	FROM
		DUAL
	UNION ALL
	SELECT
		6068 AS OBJECTID,
		'rjault' AS PNOM,
		1 AS VALIDITE
	FROM
		DUAL
	UNION ALL
	SELECT
		5741 AS OBJECTID,
		'bjacq' AS PNOM,
		1 AS VALIDITE
	FROM
		DUAL
)t
ON(a.objectid = t.objectid AND a.pnom = t.pnom)
WHEN NOT MATCHED THEN
	INSERT(a.objectid, a.pnom, a.validite)
	VALUES(t.objectid, t.pnom, t.validite);
*/
-- 3. Remplissage de la table TA_GG_FAMILLE
INSERT INTO G_GESTIONGEO.TA_GG_FAMILLE(OBJECTID, LIBELLE, VALIDITE, LIBELLE_ABREGE)
SELECT
	FAM_ID, 
	FAM_LIB, 
	FAM_VAL,
	FAM_LIB_SMALL
FROM
	G_GESTIONGEO.TEMP_TA_GG_FAMILLE;

-- 4. Remplissage de la table TA_GG_ETAT
INSERT INTO G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT(OBJECTID, LIBELLE_LONG, ETAT_AFF, LIBELLE_COURT, LIBELLE_ABREGE)
SELECT 
	ETAT_ID, 
	ETAT_LIB, 
	ETAT_AFF, 
	ETAT_LIB_SMALL, 
	ETAT_SMALL
FROM
	G_GESTIONGEO.TEMP_TA_GG_ETAT;

-- 5. Remplissage de la table TA_GG_GEO
INSERT INTO G_GESTIONGEO.TA_GG_GEO(OBJECTID, GEOM)
SELECT
	ID_GEOM,  
	ORA_GEOMETRY
FROM
	G_GESTIONGEO.TEMP_TA_GG_GEO;

-- 6. Insertion des DOS_NUM dans TA_GG_DOS_NUM
INSERT INTO G_GESTIONGEO.TA_GG_DOS_NUM(dos_num, fid_dossier)
SELECT dos_num, id_dos
FROM
    G_GESTIONGEO.TEMP_TA_GG_DOSSIER
WHERE
    dos_num IS NOT NULL;

-- 7. Remplissage de la table TA_GG_DOSSIER
INSERT INTO G_GESTIONGEO.TA_GG_DOSSIER(OBJECTID, FID_PNOM_CREATION, FID_ETAT_AVANCEMENT, FID_PNOM_MODIFICATION, FID_FAMILLE, DATE_SAISIE, DOS_PRECISION, DATE_MODIFICATION, REMARQUE, DATE_CLOTURE, DOS_IDPERE, DATE_DEBUT_TRAVAUX, DATE_FIN_TRAVAUX, DATE_COMMANDE_DOSSIER, DOS_VOIE, MAITRE_OUVRAGE, RESPONSABLE_LEVE, DOS_OLD_ID, DATE_DEBUT_LEVE, DATE_FIN_LEVE, DOS_DT_PREV)
SELECT
	a.id_dos, 
	a.src_id, 
	a.etat_id, 
	a.user_id, 
	a.fam_id, 
	a.dos_dc, 
	a.dos_precision, 
	a.dos_dmaj, 
	a.dos_rq, 
	a.dos_dt_fin,
	a.dos_idpere, 
	a.dos_dt_deb_tr, 
	a.dos_dt_fin_tr, 
	a.dos_dt_cmd_sai, 
	a.dos_voie, 
	a.dos_mao, 
	a.dos_entr, 
	a.dos_old_id, 
	a.dos_dt_deb_leve, 
	a.dos_dt_fin_leve, 
	a.dos_dt_prev
FROM
	G_GESTIONGEO.TEMP_TA_GG_DOSSIER a;

-- 8. Mise à jour de la FK FID_PERIMETRE permettant d'associer un dossier à son périmètre
MERGE INTO G_GESTIONGEO.TA_GG_DOSSIER a
USING(
    SELECT
        id_geom,
        id_dos
    FROM
        G_GESTIONGEO.TEMP_TA_GG_GEO
)t
ON (a.objectid = t.id_dos)
WHEN MATCHED THEN
    UPDATE SET a.fid_perimetre = t.id_geom;

-- 9. Redéfinition du START WITH des champs de type IDENTITY BY DEFAULT
-- 9.1. Modification de l'id de départ de ID_DOS de TA_GG_DOSSIER
SELECT
	MAX(a.OBJECTID)+1
	INTO v_id
FROM
	G_GESTIONGEO.TA_GG_DOSSIER a;

EXECUTE IMMEDIATE 'ALTER TABLE TA_GG_DOSSIER MODIFY OBJECTID GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_id  || ' INCREMENT BY 1)';

-- 9.2. Modification de l'id de départ de ID_GEOM de TA_GG_GEO
SELECT
	MAX(a.OBJECTID)+1
	INTO v_id
FROM
	G_GESTIONGEO.TA_GG_GEO a;

EXECUTE IMMEDIATE 'ALTER TABLE TA_GG_GEO MODIFY OBJECTID GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_id || ' INCREMENT BY 1)';

COMMIT;

-- 10. Réactivation des triggers, clés étrangères, contraintes, index et suppression des champs temporaires
-- 10.1. Contrainte de clé étrangère de TA_GG_DOSSIER
EXECUTE IMMEDIATE 'ALTER TABLE G_GESTIONGEO.TA_GG_DOSSER ENABLE CONSTRAINT TA_GG_DOSSIER_FID_PERIMETRE_FK';

-- 10.2. Réactivation du trigger B_UXX_TA_GG_DOSSIER
EXECUTE IMMEDIATE 'ALTER TRIGGER B_UXX_TA_GG_DOSSIER ENABLE';

-- 10.3. Réactivation du trigger A_IXX_TA_GG_DOSSIER
EXECUTE IMMEDIATE 'ALTER TRIGGER A_IXX_TA_GG_GEO ENABLE';

-- 10.4. Recréation des index de TA_GG_FAMILLE
EXECUTE IMMEDIATE 'CREATE INDEX G_GESTIONGEO."TA_GG_FAMILLE_VALIDITE_IDX" ON G_GESTIONGEO.TA_GG_FAMILLE ("VALIDITE") TABLESPACE G_ADT_INDX';

-- 10.5. Recréation des index de TA_GG_GEO
EXECUTE IMMEDIATE 'CREATE INDEX TA_GG_GEO_SIDX ON G_GESTIONGEO.TA_GG_GEO(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS(''sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP'')';

-- En cas d'erreur une exception est levée et un rollback effectué, empêchant ainsi toute insertion de se faire et de retourner à l'état des tables précédent l'insertion.
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('L''erreur ' || SQLCODE || 'est survenue. Un rollback a été effectué : ' || SQLERRM(SQLCODE));
        ROLLBACK TO POINT_SAUVEGARDE_REMPLISSAGE;
END;