/*
Vérification du bon déroulé de l'export des données dans les tables de production de GESTIONGEO.
*/

-- Comparaison du nombre d'entités dans les tables d'import et les tables finales
SELECT
    'TA_GG_DOSSIER' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_DOSSIER
GROUP BY
    'TA_GG_DOSSIER'
UNION ALL
SELECT
    'TEMP_TA_GG_DOSSIER' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TEMP_TA_GG_DOSSIER
GROUP BY
    'TEMP_TA_GG_DOSSIER'
UNION ALL
SELECT
    'TEMP_TA_GG_ETAT' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TEMP_TA_GG_ETAT
GROUP BY
    'TEMP_TA_GG_ETAT'
UNION ALL
SELECT
    'TA_GG_ETAT_AVANCEMENT' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT
GROUP BY
    'TA_GG_ETAT_AVANCEMENT'
UNION ALL
SELECT
    'TA_GG_FAMILLE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_FAMILLE
GROUP BY
    'TA_GG_FAMILLE'
UNION ALL
SELECT
    'TEMP_TA_GG_FAMILLE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TEMP_TA_GG_FAMILLE
GROUP BY
    'TEMP_TA_GG_FAMILLE'
UNION ALL
SELECT
    'TA_GG_GEO' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_GEO
GROUP BY
    'TA_GG_GEO'
UNION ALL
SELECT
    'TEMP_TA_GG_GEO' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TEMP_TA_GG_GEO
GROUP BY
    'TEMP_TA_GG_GEO';
/*
Résultats attendus :
- 5 entités de plus dans TA_GG_AGENT que dans TEMP_GG_AGENT ;
- Même nombre d'entités dans les autres tables ;
*/
-- Vérification que chaque périmètre est associé à un et un seul dossier
SELECT
    objectid
FROM
    G_GESTIONGEO.TA_GG_DOSSIER
GROUP BY
    objectid
HAVING
    COUNT(fid_perimetre) > 1;
-- Résultat attendu : aucune ligne

-- Vérification de la validité des géométries de TA_GG_GEO  
SELECT
    SUBSTR(SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(a.geom, 0.005), 0, 5) AS ERREUR,
    COUNT(a.objectid) AS Nombre
FROM
    G_GESTIONGEO.TA_GG_GEO a
WHERE
    SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(a.geom, 0.005)<>'TRUE'
GROUP BY
    SUBSTR(SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(a.geom, 0.005), 0, 5);
-- Résultat attendu : aucune ligne

-- Sélection du nombre d'entités par table
SELECT
    'TA_GG_DOSSIER' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_DOSSIER
GROUP BY
    'TA_GG_DOSSIER'
UNION ALL
SELECT
    'TA_GG_ETAT_AVANCEMENT' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_ETAT_AVANCEMENT
GROUP BY
    'TA_GG_ETAT_AVANCEMENT'
UNION ALL
SELECT
    'TA_GG_FAMILLE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_FAMILLE
GROUP BY
    'TA_GG_FAMILLE'
UNION ALL
SELECT
    'TA_GG_GEO' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_GEO
GROUP BY
    'TA_GG_GEO'
UNION ALL
SELECT
    'TA_GG_CLASSE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_CLASSE
GROUP BY
    'TA_GG_CLASSE'
UNION ALL
SELECT
    'TA_GG_DOMAINE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_DOMAINE
GROUP BY
    'TA_GG_DOMAINE'
UNION ALL
SELECT
    'TA_GG_RELATION_CLASSE_DOMAINE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_RELATION_CLASSE_DOMAINE
GROUP BY
    'TA_GG_RELATION_CLASSE_DOMAINE'
UNION ALL
SELECT
    'TA_GG_REPERTOIRE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_REPERTOIRE
GROUP BY
    'TA_GG_REPERTOIRE'
UNION ALL
SELECT
    'TA_GG_FICHIER' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_FICHIER
GROUP BY
    'TA_GG_FICHIER'
UNION ALL
SELECT
    'TA_GG_FME_MESURE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_FME_MESURE
GROUP BY
    'TA_GG_FME_MESURE'
UNION ALL
SELECT
    'TA_GG_FME_FILTRE_SUR_LIGNE' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_FME_FILTRE_SUR_LIGNE
GROUP BY
    'TA_GG_FME_FILTRE_SUR_LIGNE'
UNION ALL
SELECT
    'TA_GG_AGENT' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_AGENT
GROUP BY
    'TA_GG_AGENT'
UNION ALL
SELECT
    'TA_GG_DOS_NUM' AS NomTable,
    COUNT(*) AS NbrEntites
FROM
    G_GESTIONGEO.TA_GG_DOS_NUM
GROUP BY
    'TA_GG_DOS_NUM';