-- Création des tables TA_SECTION_CADASTRALE_GEOM et TA_SECTION_CADASTRALE sur le schéma G_DGFIP.

-- 1. Création de la table TA_SECTION_CADASTRALE_GEOM

-- 1.1. La table TA_SECTION_CADASTRALE_GEOM sert à acceuillir les informations provenant des données tarif de la RVLLP suivant le secteur et le local professionnel
CREATE TABLE G_DGFIP.TA_SECTION_CADASTRALE_GEOM(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
	geom SDO_GEOM
);


-- 1.2. Création des commentaires
COMMENT ON TABLE G_DGFIP.TA_SECTION_CADASTRALE_GEOM IS 'La table TA_SECTION_CADASTRALE_GEOM regroupe la géométrie des sections cadastrales.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE_GEOM.OBJECTID IS 'Clé étrangère vers la table TA_SECTION_CADASTRALE_GEOM.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE_GEOM.GEOM IS 'Géométrie des sections cadastrales.';


-- 1.3. Création de la clé primaire
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE_GEOM
ADD CONSTRAINT ta_section_cadastrale_geom_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 1.4 Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_SECTION_CADASTRALE_GEOM',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);


-- 1.5 Création de l'index spatial sur le champ geom
CREATE INDEX TA_SECTION_CADASTRALE_GEOM_SIDX
ON G_DGFIP.TA_SECTION_CADASTRALE_GEOM(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX


-- 2. Création de la table TA_SECTION_CADASTRALE

-- 2.1. La table TA_SECTION_CADASTRALE sert à acceuillir les informations provenant des données tarif de la RVLLP suivant le secteur et le local professionnel

CREATE TABLE G_DGFIP.TA_SECTION_CADASTRALE(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
	fid_code NUMBER(38,0),
	fid_section NUMBER(38,0),
	fid_prefixe NUMBER(38,0),
	fid_metadonnee NUMBER(38,0),
	fid_geom NUMBER(38,0)
	);

-- 2.2 Création des commentaires des colonnes

COMMENT ON TABLE G_DGFIP.TA_SECTION_CADASTRALE IS 'Table regroupant les sections cadastrales.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.objectid IS 'Clé primaire de la table TA_SECTION_CADASTRALE.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.fid_code IS 'Clé étrangère vers la table TA_CODE pour connaitre le code insee de la section cadastrale.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.fid_section IS 'Clé étrangère vers la table TA_CODE pour connaitre la section de la section cadastrale.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.fid_prefixe IS 'Clé étrangère vers la table TA_CODE pour connaitre le prefixe de la section cadastrale.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.fid_metadonnee IS 'Clé étrangère vers la table TA_METADONNE pour connaitre la source et le millesime de la section cadastrale.';
COMMENT ON COLUMN G_DGFIP.TA_SECTION_CADASTRALE.fid_geom IS 'Clé étrangère vers la table TA_SECTION_CADASTRALE_GEOM pour connaitre la géométrie de la section cadastrale.';

-- 2.3 Création de la clé primaire
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT TA_SECTION_CADASTRALE_PK 
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE "G_ADT_INDX";


-- 2.4 Création des clés étrangères

-- 2.4.1 vers la table G_GEO.TA_CODE
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT "TA_SECTION_CADASTRALE_FID_CODE_FK" 
FOREIGN KEY ("FID_CODE")
REFERENCES G_GEO."TA_CODE"("OBJECTID");

-- 2.4.2 vers la table G_GEO.TA_CODE
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT "TA_SECTION_CADASTRALE_FID_SECTION_FK" 
FOREIGN KEY ("FID_SECTION")
REFERENCES G_GEO."TA_CODE"("OBJECTID");

-- 2.4.3 vers la table G_GEO.TA_CODE
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT "TA_SECTION_CADASTRALE_FID_PREFIXE_FK" 
FOREIGN KEY ("FID_PREFIXE")
REFERENCES G_GEO."TA_CODE"("OBJECTID");

-- 2.4.4 vers la table G_GEO.TA_METADONNE
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT "TA_SECTION_CADASTRALE_FID_METADONNE_FK" 
FOREIGN KEY ("FID_METADONNEE")
REFERENCES G_GEO."TA_METADONNEE"("OBJECTID");

-- 2.4.5 vers la table G_GEO.TA_SECTION_CADASTRALE_GEOM
ALTER TABLE G_DGFIP.TA_SECTION_CADASTRALE
ADD CONSTRAINT "TA_SECTION_CADASTRALE_FID_GEOM_FK" 
FOREIGN KEY ("FID_GEOM")
REFERENCES G_GEO."TA_SECTION_CADASTRALE_GEOM"("OBJECTID");


-- 2.5 Création des index sur les cléfs étrangères.
CREATE INDEX ta_section_cadastrale_fid_code_IDX ON G_DGFIP.TA_SECTION_CADASTRALE(fid_code)
TABLESPACE G_ADT_INDX;

CREATE INDEX ta_section_cadastrale_fid_section_IDX ON G_DGFIP.TA_SECTION_CADASTRALE(fid_nom)
TABLESPACE G_ADT_INDX;

CREATE INDEX ta_section_cadastrale_fid_prefixe_IDX ON G_DGFIP.TA_SECTION_CADASTRALE(fid_lib_type)
TABLESPACE G_ADT_INDX;

CREATE INDEX ta_section_cadastrale_fid_metadonnee_IDX ON G_DGFIP.TA_SECTION_CADASTRALE(fid_metadonnee)
TABLESPACE G_ADT_INDX;

CREATE INDEX ta_section_cadastrales_fid_geom_IDX ON G_DGFIP.TA_SECTION_CADASTRALE(fid_iris_geom)
TABLESPACE G_ADT_INDX;