--------------------------------------
-- SUPPRESSION_INDEXES_GEOMETRIQUES --
--------------------------------------

-- Code pour supprimer les indexes afin de remplir plus rapidement les tables avec 


-- TA_PTTOPO_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_PTTOPO_INTEGRATION_SIDX;

DROP INDEX TA_PTTOPO_INTEGRATION_FID_NUMERO_DOSSIER_IDX;

-- TA_PTTOPO_INTEGRATION_LOG
DROP INDEX TA_PTTOPO_INTEGRATION_LOG_SIDX;
DROP INDEX TA_PTTOPO_INTEGRATION_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_GG_RECUPERATION_Z_ETAPE_4
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_4_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO_SIDX;


-- TA_RTGE_POINT_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_SIDX;

DROP INDEX TA_RTGE_POINT_INTEGRATION_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_INTEGRATION_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_POINT_INTEGRATION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_LOG_SIDX;

DROP INDEX TA_RTGE_POINT_INTEGRATION_LOG_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_INTEGRATION_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_POINT_PRODUCTION
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_SIDX;

DROP INDEX TA_RTGE_POINT_PRODUCTION_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_PRODUCTION_FID_NUMERO_DOSSIER_IDX;
DROP INDEX TA_RTGE_POINT_PRODUCTION_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX;

-- TA_RTGE_POINT_PRODUCTION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG_SIDX;

DROP INDEX TA_RTGE_POINT_PRODUCTION_LOG_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_PRODUCTION_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_LINEAIRE_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_SIDX;

DROP INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_INTEGRATION_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_LINEAIRE_INTEGRATION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_LOG_SIDX;

DROP INDEX TA_RTGE_LINEAIRE_INTEGRATION_LOG_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_INTEGRATION_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_LINEAIRE_PRODUCTION
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION_SIDX;

DROP INDEX TA_RTGE_LINEAIRE_PRODUCTION_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_PRODUCTION_FID_NUMERO_DOSSIER_IDX;
DROP INDEX TA_RTGE_LINEAIRE_PRODUCTION_FID_IDENTIFIANT_OBJET_INTEGRATION_IDX;

-- TA_RTGE_LINEAIRE_PRODUCTION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION_LOG_SIDX;

DROP INDEX TA_RTGE_LINEAIRE_PRODUCTION_LOG_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_PRODUCTION_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_RTGE_LINEAIRE_CONSULTATION
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_SIDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_LINEAIRE_CONSULTATION_LIBELLE_TYPE_IDX;

-- TA_IC_LINEAIRE
DROP INDEX G_GESTIONGEO.TA_IC_LINEAIRE_SIDX;

DROP INDEX TA_IC_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_IC_LINEAIRE_FID_NUMERO_DOSSIER_IDX;

-- TA_IC_LINEAIRE_LOG
DROP INDEX G_GESTIONGEO.TA_IC_LINEAIRE_LOG_SIDX;

DROP INDEX TA_IC_LINEAIRE_LOG_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_IC_LINEAIRE_LOG_FID_NUMERO_DOSSIER_IDX;

-- TA_OCSMEL
DROP INDEX G_GESTIONGEO.TA_OCSMEL_SIDX;

DROP INDEX TA_OCSMEL_FID_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_OCSMEL_CREATION_IDX;
DROP INDEX TA_OCSMEL_MODIFICATION_IDX;

-- TA_OCSMEL_LOG
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LOG_SIDX;

DROP INDEX TA_OCSMEL_LOG_FID_IDENTIFIANT_TYPE_IDX;


-- TA_OCSMEL_LINEAIRE
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LINEAIRE_SIDX;

DROP INDEX TA_OCSMEL_LINEAIRE_FID_IDENTIFIANT_TYPE_IDX;

--TA_OCSMEL_LINEAIRE_LOG
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LINEAIRE_LOG_SIDX;

DROP INDEX TA_OCSMEL_LINEAIRE_LOG_FID_IDENTIFIANT_TYPE_IDX;

-- TA_RTGE_POINT_CONSULTATION
DROP INDEX TA_RTGE_POINT_CONSULTATION_SIDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_POINT_CONSULTATION_LIBELLE_TYPE_IDX;

-- TA_RTGE_ALTI_CONSULTATION
DROP INDEX TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_TYPE_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_CODE_TYPE_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_LIBELLE_TYPE_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_FID_IDENTIFIANT_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_IDENTIFIANT_OBJET_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_FID_IDENTIFIANT_IDENTIFIANT_OBJET_IDX;
DROP INDEX TA_RTGE_ALTI_CONSULTATION_OBJECTID_FID_IDENTIFIANT_IDENTIFIANT_OBJET_IDX;

/
