-- Fichier de suppression des indexes
-- Code pour supprimer les indexes afin de remplir plus rapidement les tables avec 


-- TA_PTTOPO_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_PTTOPO_INTEGRATION_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_4
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_4_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO_SIDX;


-- TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO
DROP INDEX G_GESTIONGEO.TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO_SIDX;


-- TA_RTGE_POINT_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_SIDX;


-- TA_RTGE_POINT_INTEGRATION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_INTEGRATION_LOG_SIDX;


-- TA_RTGE_POINT_PRODUCTION
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_SIDX;


-- TA_RTGE_POINT_PRODUCTION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_POINT_PRODUCTION_LOG_SIDX;

-- TA_RTGE_LINEAIRE_INTEGRATION
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_SIDX;


-- TA_RTGE_LINEAIRE_INTEGRATION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_INTEGRATION_LOG_SIDX;


-- TA_RTGE_LINEAIRE_PRODUCTION
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION_SIDX;


-- TA_RTGE_LINEAIRE_PRODUCTION_LOG
DROP INDEX G_GESTIONGEO.TA_RTGE_LINEAIRE_PRODUCTION_LOG_SIDX;


-- TA_IC_LINEAIRE
DROP INDEX G_GESTIONGEO.TA_IC_LINEAIRE_SIDX;


-- TA_IC_LINEAIRE_LOG
DROP INDEX G_GESTIONGEO.TA_IC_LINEAIRE_LOG_SIDX;


-- TA_OCSMEL
DROP INDEX G_GESTIONGEO.TA_OCSMEL_SIDX;


-- TA_OCSMEL_LOG
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LOG_SIDX;


-- TA_OCSMEL_LINEAIRE
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LINEAIRE_SIDX;


--TA_OCSMEL_LINEAIRE_LOG
DROP INDEX G_GESTIONGEO.TA_OCSMEL_LINEAIRE_LOG_SIDX;

/
