
CREATE TABLE "GEO"."TA_CLASSE" (
	"CLA_INU" NUMBER(8,0) NOT NULL ENABLE,
	"DOM_INU" NUMBER(8,0),
	"CLA_CODE" CHAR(3 BYTE) NOT NULL ENABLE,
	"CLA_LI" VARCHAR2(50 BYTE),
	"MI_STYLE" VARCHAR2(254 BYTE),
	"CLA_STATION" VARCHAR2(12 BYTE),
	"CLA_DIM" NUMBER(5,0),
	CONSTRAINT "PK_TA_CLASSE" PRIMARY KEY ("CLA_INU")
		TABLESPACE "INDX_GEO"  ENABLE,
	CONSTRAINT "FK_CLASSE_DOM" FOREIGN KEY ("DOM_INU")
  	REFERENCES "GEO"."TA_DOM" ("DOM_INU") ENABLE
 )
TABLESPACE "DATA_GEO" ;

COMMENT ON COLUMN "GEO"."TA_CLASSE"."CLA_INU" IS 'Identifiant interne de la classe';
COMMENT ON COLUMN "GEO"."TA_CLASSE"."DOM_INU" IS 'Reference au domaine d''appartenance';
COMMENT ON COLUMN "GEO"."TA_CLASSE"."CLA_CODE" IS 'Nom court de la classe';
COMMENT ON COLUMN "GEO"."TA_CLASSE"."CLA_LI" IS 'Libelle de la classe';
COMMENT ON COLUMN "GEO"."TA_CLASSE"."CLA_STATION" IS 'Code station terrain';
COMMENT ON COLUMN "GEO"."TA_CLASSE"."CLA_DIM" IS 'Taille de l''objet par défaut';
COMMENT ON TABLE "GEO"."TA_CLASSE"  IS 'Liste des differentes classes d''objets geographiques';

CREATE INDEX "GEO"."GET_CLA_CODE_IDX" ON "GEO"."TA_CLASSE" ("CLA_INU", "GEO"."GET_CLA_CODE"("CLA_INU"))
	TABLESPACE "INDX_GEO";

CREATE INDEX "GEO"."GET_CLA_LI_IDX" ON "GEO"."TA_CLASSE" ("CLA_INU", "GEO"."GET_CLA_LI"("CLA_INU"))
	TABLESPACE "INDX_GEO";

CREATE INDEX "GEO"."TA_CLASSE_CLA_CODE_IDX" ON "GEO"."TA_CLASSE" ("CLA_CODE")
	TABLESPACE "INDX_GEO";
