CREATE TABLE "GEO"."TA_GG_POINT" (
	"ID_GEOM" NUMBER NOT NULL ENABLE,
	"ID_DOS" NUMBER NOT NULL ENABLE,
	"CLASSE_DICT" VARCHAR2(1 BYTE),
	"GEOM" "MDSYS"."SDO_GEOMETRY" ,
	CONSTRAINT "TA_GG_POINT_PK" PRIMARY KEY ("ID_GEOM")
		TABLESPACE "INDX_GEO"  ENABLE
 )
TABLESPACE "DATA_GEO" ;

CREATE INDEX "GEO"."TA_GG_POINT_SIDX" ON "GEO"."TA_GG_POINT" ("GEOM")
	INDEXTYPE IS "MDSYS"."SPATIAL_INDEX"  PARAMETERS (' LAYER_GTYPE = COLLECTION WORK_TABLESPACE=DATA_TEMP TABLESPACE=ISPA_GEO');
