CREATE TABLE "GEO"."TA_GG_SOURCE" (
	"SRC_ID" NUMBER NOT NULL ENABLE,
	"SRC_LIBEL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SRC_VAL" NUMBER(*,0) NOT NULL ENABLE,
CONSTRAINT "PK_TA_GG_SOURCE" PRIMARY KEY ("SRC_ID")
 )
TABLESPACE "DATA_GEO" ;
