CREATE TABLE "GEO"."TA_GG_DOC" (
	"DOC_ID" NUMBER NOT NULL ENABLE,
	"ID_DOS" NUMBER,
	"FOR_ID" NUMBER NOT NULL ENABLE,
	"DOC_NM" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DOC_REP" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	CONSTRAINT "PK_TA_GG_DOC" PRIMARY KEY ("DOC_ID")
		USING TABLESPACE "INDX_GEO"  ENABLE,
	CONSTRAINT "FK_TA_GG_DO_RELATION__TA_GG_FO" FOREIGN KEY ("FOR_ID")
		REFERENCES "GEO"."TA_GG_FORMAT" ("FOR_ID") ENABLE
)
TABLESPACE "DATA_GEO" ;

COMMENT ON TABLE "GEO"."TA_GG_DOC"  IS 'Documentation numérique accompagnant le dossier. Cette table est vide est-ce normal ?';

CREATE INDEX "GEO"."GED_FK" ON "GEO"."TA_GG_DOC" ("ID_DOS") TABLESPACE "INDX_GEO" ;

CREATE INDEX "GEO"."RELATION_8_FK" ON "GEO"."TA_GG_DOC" ("FOR_ID") TABLESPACE "INDX_GEO" ;
