-- Suppresion des tables temporaires ayant servi au remplissage des tables finales.

-- Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_TA_GG_GEO';
COMMIT;

-- Suppression des tables
DROP TABLE G_GESTIONGEO.TEMP_TA_GG_GEO CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TEMP_TA_GG_DOSSIER CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TEMP_TA_GG_AGENT CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TEMP_TA_GG_ETAT CASCADE CONSTRAINTS;
DROP TABLE G_GESTIONGEO.TEMP_TA_GG_FAMILLE CASCADE CONSTRAINTS;