/*
Suppression des elements
*/

-- 1. Suppression des tables.
-- 1.1. Table du schema
DROP TABLE TA_RTGE_POINT_INTEGRATION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_POINT_INTEGRATION_LOG CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_POINT_PRODUCTION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_POINT_PRODUCTION_LOG CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_LINEAIRE_INTEGRATION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_LINEAIRE_INTEGRATION_LOG CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_LINEAIRE_PRODUCTION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_LINEAIRE_PRODUCTION_LOG CASCADE CONSTRAINTS;
DROP TABLE TA_PTTOPO_INTEGRATION CASCADE CONSTRAINTS;
DROP TABLE TA_PTTOPO_INTEGRATION_LOG;
DROP TABLE TA_OCSMEL CASCADE CONSTRAINTS;
DROP TABLE TA_OCSMEL_LOG CASCADE CONSTRAINTS;
DROP TABLE TA_OCSMEL_LINEAIRE;
DROP TABLE TA_OCSMEL_LINEAIRE_LOG;
DROP TABLE TA_RTGE_SURFACE;
DROP TABLE TA_IC_LINEAIRE;
DROP TABLE TA_IC_LINEAIRE_LOG;
DROP TABLE TA_RTGE_POINT_CONSULTATION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_LINEAIRE_CONSULTATION CASCADE CONSTRAINTS;
DROP TABLE TA_RTGE_ALTI_CONSULTATION CASCADE CONSTRAINTS;


-- Table utilisée dans le calcul des de la largeurs des MUF
DROP TABLE TA_RTGE_MUF_END_POINT;
DROP TABLE TA_RTGE_MUF_END_POINT_PTTOPO;
DROP TABLE TA_RTGE_MUF_POINT;
DROP TABLE TA_RTGE_MUF_POINT_PTTOPO;
DROP TABLE TA_RTGE_MUF_START_POINT;
DROP TABLE TA_RTGE_MUF_START_POINT_PTTOPO;
DROP TABLE TA_RTGE_MUF_STATUT;


-- 1.4. Suppression des tables temporaires
DROP TABLE TEMP_TA_POINT_TOPO_GPS CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_POINT_TOPO_F CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_POINT_TOPO_F_LOG CASCADE CONSTRAINTS;
DROP TABLE TEMP_PTTOPO CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_LIG_TOPO_GPS CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_LIG_TOPO_F CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_LIG_TOPO_F_LOG CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_SUR_TOPO_G CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_SUR_TOPO_G_LOG CASCADE CONSTRAINTS;
DROP TABLE TEMP_TA_LIG_TOPO_GPS_GEO_ON_VALIDE_1;
DROP TABLE TEMP_TA_LIG_TOPO_GPS_BACKUP;
DROP TABLE TEMP_TA_LIG_TOPO_G;
DROP TABLE TEMP_TA_LIG_TOPO_G_LOG;
DROP TABLE TEMP_TA_LIG_TOPO_IC;


-- 1.3. Table liées à l'éxécution de la procédure MISE_A_JOUR_Z_TA_LIG_TOPO_GPS
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_1 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_2 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_3 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_4 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_5 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_6 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_7 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_8 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_9 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_10 CASCADE CONSTRAINTS;
DROP TABLE TA_GG_RECUPERATION_Z_ETAPE_11 CASCADE CONSTRAINTS;


-- 2. Suppression des metadonnees.
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_INTEGRATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_INTEGRATION_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_PRODUCTION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_PRODUCTION_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_INTEGRATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_INTEGRATION_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_PRODUCTION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_PRODUCTION_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_PTTOPO_INTEGRATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_PTTOPO_INTEGRATION_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_OCSMEL';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_OCSMEL_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_OCSMEL_LINEAIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_OCSMEL_LINEAIRE_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_SURFACE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_IC_LINEAIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_IC_LINEAIRE_LOG';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_GG_RECUPERATION_Z_ETAPE_5_MUF_TOPO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_GG_RECUPERATION_Z_ETAPE_5_MUF_SANS_TOPO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_GG_RECUPERATION_Z_ETAPE_5';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_GG_RECUPERATION_Z_ETAPE_4';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_OCSMEL_LINEAIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_MUF_START_POINT';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_MUF_POINT';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_MUF_END_POINT';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_INTEGRATION_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_LINEAIRE_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_POINT_CONSULTATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_LINEAIRE_CONSULTATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_RTGE_ALTI_CONSULTATION';

-- 3. Suppression triggers.
-- 3.1. trigger de log.
DROP TRIGGER B_XUD_TA_RTGE_LINEAIRE_INTEGRATION_LOG;
DROP TRIGGER B_XUD_TA_RTGE_LINEAIRE_PRODUCTION_LOG;
DROP TRIGGER B_XUD_TA_RTGE_POINT_PRODUCTION_LOG;
DROP TRIGGER B_XUD_TA_RTGE_POINT_INTEGRATION_LOG;
DROP TRIGGER B_XUD_TA_OCSMEL_LOG;


-- 3.2. trigger de migration des donnees.
DROP TRIGGER B_XUX_TA_RTGE_LINEAIRE_MIGRATION;
DROP TRIGGER B_XUX_TA_RTGE_POINT_MIGRATION;


-- 3.3. trigger de mise à jour.
DROP TRIGGER B_IUX_TA_RTGE_LINEAIRE;
DROP TRIGGER B_IUX_TA_RTGE_POINT;
DROP TRIGGER B_IUX_TA_RTGE_LINEAIRE_INTEGRATION;
DROP TRIGGER B_IUX_TA_OCSMEL;
DROP TRIGGER B_IUX_TA_RTGE_POINT_INTEGRATION;


-- 3.4. trigger de clé primaire log
DROP TRIGGER B_IUX_TA_RTGE_POINT_INTEGRATION;
DROP TRIGGER B_IXX_TA_RTGE_POINT_INTEGRATION_LOG_PK;
DROP TRIGGER A_IUD_TA_RTGE_POINT_INTEGRATION_LOG;
DROP TRIGGER B_IUX_TA_RTGE_POINT_PRODUCTION_MIGRATION;
DROP TRIGGER B_IUX_TA_RTGE_POINT_PRODUCTION;
DROP TRIGGER B_IXX_TA_RTGE_POINT_PRODUCTION_LOG_PK;
DROP TRIGGER A_IUD_TA_RTGE_POINT_PRODUCTION_LOG_2;
DROP TRIGGER B_IUX_TA_RTGE_LINEAIRE_INTEGRATION;
DROP TRIGGER A_IUD_TA_RTGE_LINEAIRE_INTEGRATION_LOG;
DROP TRIGGER B_IXX_TA_RTGE_LINEAIRE_INTEGRATION_LOG_PK;
DROP TRIGGER B_IUX_TA_RTGE_LINEAIRE_PRODUCTION_MIGRATION;
DROP TRIGGER B_IUX_TA_RTGE_LINEAIRE_PRODUCTION;
DROP TRIGGER B_IXX_TA_RTGE_LINEAIRE_PRODUCTION_LOG_PK;
DROP TRIGGER A_IUD_TA_RTGE_LINEAIRE_PRODUCTION_LOG_2;
DROP TRIGGER B_IXX_TA_PTTOPO_INTEGRATION_PK;
DROP TRIGGER B_IXX_TA_OCSMEL_LINEAIRE_PK;
DROP TRIGGER B_IXX_TA_OCSMEL_LINEAIRE_LOG_PK;
DROP TRIGGER B_IUX_TA_OCSMEL;
DROP TRIGGER B_IXX_TA_OCSMEL_LOG_PK;
DROP TRIGGER A_IUD_TA_OCSMEL_LOG_2;
DROP TRIGGER B_IUX_TA_IC_LINEAIRE;
DROP TRIGGER A_IUD_TA_IC_LINEAIRE_LOG;
DROP TRIGGER B_IXX_TA_IC_LINEAIRE_LOG_PK;


-- 4. Suppression des procedures.
DROP PROCEDURE MISE_A_JOUR_Z_TA_RTGE_LINEAIRE_INTEGRATION;
DROP PROCEDURE MISE_A_JOUR_Z_TA_RTGE_SURFACE;
DROP PROCEDURE MISE_A_JOUR_Z_TA_RTGE_SURFACE_MUF;
DROP PROCEDURE MISE_A_JOUR_LARGEUR_MUF;


-- 5. Suppression des sequences
DROP SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_INTEGRATION_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_INTEGRATION_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_POINT_PRODUCTION_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_PRODUCTION_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_POINT_PRODUCTION_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_PRODUCTION_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_OCSMEL_OBJECTID;
DROP SEQUENCE SEQ_TA_OCSMEL_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_PTTOPO_INTEGRATION_OBJECTID;
DROP SEQUENCE TA_PTTOPO_INTEGRATION_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_OCSMEL_LINEAIRE_OBJECTID;
DROP SEQUENCE SEQ_TA_OCSMEL_LINEAIRE_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_SURFACE_OBJECTID;
DROP SEQUENCE SEQ_TA_IC_LINEAIRE_OBJECTID;
DROP SEQUENCE SEQ_TA_IC_LINEAIRE_LOG_OBJECTID;
DROP SEQUENCE SEQ_TA_RTGE_ALTI_CONSULTATION_OBJECTID;

-- 6. Suppression des vues
DROP VIEW V_RTGE_POINT;
DROP VIEW V_RTGE_LINEAIRE_SOMMET;
DROP VIEW V_RTGE_LINEAIRE;
DROP VIEW V_RTGE_ELEMENT_SOMMET_ALTITUDE;
DROP VIEW V_RTGE_ELEMENT_INTEGRATION_SOMMET_ALTITUDE;
DROP VIEW V_RTGE_ELEMENT_LINEAIRE_SOMMET_ALTITUDE;
DROP VIEW V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE;

-- 7. Suppression des metadonnees des vue.
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_POINT';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_LINEAIRE_SOMMET';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_LINEAIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_INTEGRATION_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_LINEAIRE_SOMMET_ALTITUDE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_RTGE_ELEMENT_PRODUCTION_SOMMET_ALTITUDE';

/
