-- MISE A JOUR DES METADONNEE
-- TA_SOURCE
MERGE INTO G_GEO.TA_SOURCE a
USING
    (
        SELECT
            163	AS OBJECTID,
            'OCS2D' AS NOM_SOURCE,
            'Le référentiel OCS2D est une base de données diachronique d''occupation du sol en 2 dimensions sur les départements du Nord et du PAS-de-Calais. Pour chaque portion de territoire interprété, il décrit de façon précise le couvert du sol et l''usage du sol.' AS DESCRIPTION
        FROM
            DUAL
    )b
ON (a.objectid = b.objectid
AND a.NOM_SOURCE = b.NOM_SOURCE
AND a.description = b.description)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.NOM_SOURCE, a.description)
VALUES(b.objectid,b.NOM_SOURCE, b.description)
;

-- TA_DATE_ACQUISITION
MERGE INTO G_GEO.TA_DATE_ACQUISITION a
USING
    (
	SELECT
		683 AS OBJECTID,
	    TO_DATE('18/12/21') AS DATE_ACQUISITION,
	    TO_DATE('01/01/20') AS MILLESIME,
	    'rjault' AS NOM_OBTENTEUR
	FROM
	    DUAL
	UNION
	SELECT
		663 AS OBJECTID,
	    TO_DATE('18/12/21') AS DATE_ACQUISITION,
	    TO_DATE('01/01/05')  AS MILLESIME,
	    'rjault' AS NOM_OBTENTEUR
	FROM
	    DUAL
	UNION
	SELECT
		686 AS OBJECTID,
	    TO_DATE('18/12/21') AS DATE_ACQUISITION,
	    TO_DATE(' 01/01/15')  AS MILLESIME,
	    'rjault' AS NOM_OBTENTEUR
	FROM
	    DUAL
    )b
ON (a.objectid = b.objectid
AND a.DATE_ACQUISITION = b.DATE_ACQUISITION
AND a.MILLESIME = b.MILLESIME
AND a.NOM_OBTENTEUR = b.NOM_OBTENTEUR)
WHEN NOT MATCHED THEN
INSERT(a.objectid,a.DATE_ACQUISITION, a.MILLESIME, a.NOM_OBTENTEUR)
VALUES(b.objectid,b.DATE_ACQUISITION,b.MILLESIME, b.NOM_OBTENTEUR)
;


-- TA_PROVENANCE
MERGE INTO G_GEO.TA_PROVENANCE a
USING
    (
	SELECT
		365	AS OBJECTID,
		'https://cloud.sirs-fr.com/index.php/s/MGSLBai7pweRXLJ' AS URL,
		'Donnée OCS2D finale corrigée par CLS. Téléchargée depuis le serveur CLS, disponible également sur le serveur infogeo, donnée externe, CLS sous le nom OCS2d_mel_Multidate_2005_2015_2020' AS METHODE_ACQUISITION
	FROM
		DUAL
    )b
ON (a.objectid = b.objectid
AND a.URL = b.URL
AND a.METHODE_ACQUISITION = b.METHODE_ACQUISITION)
WHEN NOT MATCHED THEN
INSERT(a.objectid,a.URL, a.METHODE_ACQUISITION)
VALUES(b.objectid,b.URL,b.METHODE_ACQUISITION)
;


-- TA_ORGANISME
MERGE INTO G_GEO.TA_ORGANISME a
USING
    (
	SELECT
		162	objectid,
		'CLS' as acronyme,
		'Collecte Localisation Satellites' as nom_organisme
	FROM
		DUAL
    )b
ON (a.objectid = b.objectid
AND a.acronyme = b.acronyme
AND a.nom_organisme = b.nom_organisme)
WHEN NOT MATCHED THEN
INSERT(a.objectid,a.acronyme, a.nom_organisme)
VALUES(b.objectid,b.acronyme,b.nom_organisme)
;

-- TA_ECHELLE
MERGE INTO G_GEO.TA_ECHELLE a
USING
    (
	SELECT
		3 as objectid,
		5000 as valeur
	FROM
		DUAL
    )b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.valeur)
VALUES(b.objectid,b.valeur)
;


-- TA_METADONNEE
MERGE INTO G_GEO.TA_METADONNEE a
USING
    (
	SELECT
		704 as objectid,
		163 as fid_source,
		663 as fid_acquisition,
		365 as fid_provenance
	FROM
		DUAL
	UNION
	SELECT
		705 as objectid,
		163 as fid_source,
		686 as fid_acquisition,
		365 as fid_provenance
	FROM
		DUAL
	UNION
	SELECT
		707 as objectid,
		163 as fid_source,
		683 as fid_acquisition,
		365 as fid_provenance
	FROM
		DUAL
    )b
ON (a.objectid = b.objectid
AND a.fid_source = b.fid_source
AND a.fid_acquisition = b.fid_acquisition
AND a.fid_provenance = b.fid_provenance)
WHEN NOT MATCHED THEN
INSERT(a.objectid,a.fid_source, a.fid_acquisition, a.fid_provenance)
VALUES(b.objectid,b.fid_source,b.fid_acquisition, b.fid_provenance)
;


-- TA_RELATION_ECHELLE
MERGE INTO G_GEO.TA_METADONNEE_RELATION_ECHELLE a
USING
    (
	SELECT
		704 AS FID_METADONNEE,
		3 AS FID_ECHELLE
	FROM
		DUAL
	UNION
	SELECT
		705 AS FID_METADONNEE,
		3 AS FID_ECHELLE
	FROM
		DUAL
	UNION
	SELECT
		707 AS FID_METADONNEE,
		3 AS FID_ECHELLE
	FROM
		DUAL
    )b
ON (a.FID_METADONNEE = b.FID_METADONNEE
AND a.FID_ECHELLE = b.FID_ECHELLE)
WHEN NOT MATCHED THEN
INSERT(a.FID_METADONNEE, a.FID_ECHELLE)
VALUES(b.FID_METADONNEE,b.FID_ECHELLE)
;


-- TA_RELATION_ECHELLE
MERGE INTO G_GEO.TA_METADONNEE_RELATION_ORGANISME a
USING
    (
	SELECT
		704 AS FID_METADONNEE,
		162 AS FID_ORGANISME
	FROM
		DUAL
	UNION
	SELECT
		705 AS FID_METADONNEE,
		162 AS FID_ORGANISME
	FROM
		DUAL
	UNION
	SELECT
		707 AS FID_METADONNEE,
		162 AS FID_ORGANISME
	FROM
		DUAL
    )b
ON (a.FID_METADONNEE = b.FID_METADONNEE
AND a.FID_ORGANISME = b.FID_ORGANISME)
WHEN NOT MATCHED THEN
INSERT(a.FID_METADONNEE, a.FID_ORGANISME)
VALUES(b.FID_METADONNEE,b.FID_ORGANISME)
;

-- TA_FAMILLE
MERGE INTO G_GEO.TA_FAMILLE a
USING
    (
        SELECT
            211	AS OBJECTID,
            'USAGE DU SOL' AS VALEUR
        FROM
            DUAL
        UNION
        SELECT
            210	AS OBJECTID,
            'COUVERT DU SOL' AS VALEUR
        FROM
            DUAL
    )b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.valeur)
VALUES(b.objectid,b.valeur)
;


-- TA_LIBELLE
-- couvert
MERGE INTO G_GEO.TA_LIBELLE_LONG a
USING
	(
	SELECT 608 AS OBJECTID, 'Autres formations herbacées' AS VALEUR FROM DUAL UNION
	SELECT 611 AS OBJECTID, 'Boisements humides' AS VALEUR FROM DUAL UNION
	SELECT 612 AS OBJECTID, 'COUVERT DU SOL' AS VALEUR FROM DUAL UNION
	SELECT 620 AS OBJECTID, 'Conifères' AS VALEUR FROM DUAL UNION
	SELECT 621 AS OBJECTID, 'Conifères sur dunes' AS VALEUR FROM DUAL UNION
	SELECT 622 AS OBJECTID, 'Cours d''eau' AS VALEUR FROM DUAL UNION
	SELECT 625 AS OBJECTID, 'Dunes' AS VALEUR FROM DUAL UNION
	SELECT 628 AS OBJECTID, 'Eaux continentales' AS VALEUR FROM DUAL UNION
	SELECT 629 AS OBJECTID, 'Eaux maritimes' AS VALEUR FROM DUAL UNION
	SELECT 635 AS OBJECTID, 'Estuaires' AS VALEUR FROM DUAL UNION
	SELECT 640 AS OBJECTID, 'Feuillus' AS VALEUR FROM DUAL UNION
	SELECT 641 AS OBJECTID, 'Feuillus sur dunes' AS VALEUR FROM DUAL UNION
	SELECT 643 AS OBJECTID, 'Formations arborescentes' AS VALEUR FROM DUAL UNION
	SELECT 644 AS OBJECTID, 'Formations arbustives et sous-arbrisseaux' AS VALEUR FROM DUAL UNION
	SELECT 645 AS OBJECTID, 'Formations herbacées humides ' AS VALEUR FROM DUAL UNION
	SELECT 646 AS OBJECTID, 'Formations herbacées humides continentales' AS VALEUR FROM DUAL UNION
	SELECT 647 AS OBJECTID, 'Formations herbacées humides maritimes' AS VALEUR FROM DUAL UNION
	SELECT 648 AS OBJECTID, 'Formations herbacées ou basses' AS VALEUR FROM DUAL UNION
	SELECT 649 AS OBJECTID, 'Formations herbacées sur dunes' AS VALEUR FROM DUAL UNION
	SELECT 650 AS OBJECTID, 'Fourrés et broussailles' AS VALEUR FROM DUAL UNION
	SELECT 651 AS OBJECTID, 'Fourrés humides' AS VALEUR FROM DUAL UNION
	SELECT 665 AS OBJECTID, 'Landes' AS VALEUR FROM DUAL UNION
	SELECT 666 AS OBJECTID, 'Landes humides' AS VALEUR FROM DUAL UNION
	SELECT 667 AS OBJECTID, 'Landes sèches' AS VALEUR FROM DUAL UNION
	SELECT 669 AS OBJECTID, 'Mer' AS VALEUR FROM DUAL UNION
	SELECT 672 AS OBJECTID, 'Pelouses naturelles' AS VALEUR FROM DUAL UNION
	SELECT 673 AS OBJECTID, 'Peuplements mixtes' AS VALEUR FROM DUAL UNION
	SELECT 674 AS OBJECTID, 'Peuplements mixtes ou indéterminés' AS VALEUR FROM DUAL UNION
	SELECT 675 AS OBJECTID, 'Peuplements mixtes sur dunes' AS VALEUR FROM DUAL UNION
	SELECT 677 AS OBJECTID, 'Pierres, rochers, falaises' AS VALEUR FROM DUAL UNION
	SELECT 678 AS OBJECTID, 'Plans d''eau' AS VALEUR FROM DUAL UNION
	SELECT 680 AS OBJECTID, 'Prairies' AS VALEUR FROM DUAL UNION
	SELECT 682 AS OBJECTID, 'Prairies humides' AS VALEUR FROM DUAL UNION
	SELECT 683 AS OBJECTID, 'Prairies mésophiles' AS VALEUR FROM DUAL UNION
	SELECT 689 AS OBJECTID, 'Sable, dunes, limons' AS VALEUR FROM DUAL UNION
	SELECT 690 AS OBJECTID, 'Sable, estran' AS VALEUR FROM DUAL UNION
	SELECT 693 AS OBJECTID, 'Sols nus' AS VALEUR FROM DUAL UNION
	SELECT 694 AS OBJECTID, 'Surfaces bâties' AS VALEUR FROM DUAL UNION
	SELECT 695 AS OBJECTID, 'Surfaces composées d''autres matériaux' AS VALEUR FROM DUAL UNION
	SELECT 696 AS OBJECTID, 'Surfaces en eau' AS VALEUR FROM DUAL UNION
	SELECT 697 AS OBJECTID, 'Surfaces imperméables' AS VALEUR FROM DUAL UNION
	SELECT 698 AS OBJECTID, 'Surfaces non bâties ' AS VALEUR FROM DUAL UNION
	SELECT 699 AS OBJECTID, 'Surfaces perméables' AS VALEUR FROM DUAL UNION
	SELECT 700 AS OBJECTID, 'Surfaces revêtues ou stabilisées' AS VALEUR FROM DUAL UNION
	SELECT 701 AS OBJECTID, 'Surfaces à matériaux minéraux - pierre - terre ' AS VALEUR FROM DUAL UNION
	SELECT 703 AS OBJECTID, 'Terres arables' AS VALEUR FROM DUAL UNION
	SELECT 711 AS OBJECTID, 'Vergers et petits fruits' AS VALEUR FROM DUAL UNION
	SELECT 712 AS OBJECTID, 'Végétations arbustives sur dunes' AS VALEUR FROM DUAL
	)b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT (a.objectid,a.valeur)
VALUES (b.objectid,b.valeur)
;


-- usage
MERGE INTO G_GEO.TA_LIBELLE_LONG a
USING
	(
	SELECT 600 AS OBJECTID, 'A vocation sylvicole ou usage indéterminé' AS VALEUR FROM DUAL UNION
	SELECT 601 AS OBJECTID, 'Activités d''extraction' AS VALEUR FROM DUAL UNION
	SELECT 602 AS OBJECTID, 'Activités économiques secondaires et tertiaires' AS VALEUR FROM DUAL UNION
	SELECT 603 AS OBJECTID, 'Agriculture' AS VALEUR FROM DUAL UNION
	SELECT 604 AS OBJECTID, 'Aquaculture, pisciculture' AS VALEUR FROM DUAL UNION
	SELECT 605 AS OBJECTID, 'Autoconsommation' AS VALEUR FROM DUAL UNION
	SELECT 607 AS OBJECTID, 'Autres emprises collectives' AS VALEUR FROM DUAL UNION
	SELECT 609 AS OBJECTID, 'Aérien' AS VALEUR FROM DUAL UNION
	SELECT 610 AS OBJECTID, 'Bandes enherbées' AS VALEUR FROM DUAL UNION
	SELECT 613 AS OBJECTID, 'Campings' AS VALEUR FROM DUAL UNION
	SELECT 614 AS OBJECTID, 'Carrières, mines' AS VALEUR FROM DUAL UNION
	SELECT 615 AS OBJECTID, 'Chantiers' AS VALEUR FROM DUAL UNION
	SELECT 616 AS OBJECTID, 'Cimetières et lieux de culte' AS VALEUR FROM DUAL UNION
	SELECT 617 AS OBJECTID, 'Collectifs' AS VALEUR FROM DUAL UNION
	SELECT 618 AS OBJECTID, 'Complexes culturels et de loisirs' AS VALEUR FROM DUAL UNION
	SELECT 619 AS OBJECTID, 'Complexes sportifs et terrains de sports' AS VALEUR FROM DUAL UNION
	SELECT 623 AS OBJECTID, 'Cultures annuelles' AS VALEUR FROM DUAL UNION
	SELECT 624 AS OBJECTID, 'Cultures permanentes' AS VALEUR FROM DUAL UNION
	SELECT 626 AS OBJECTID, 'Déchetteries et décharges publiques' AS VALEUR FROM DUAL UNION
	SELECT 627 AS OBJECTID, 'Délaissés urbains' AS VALEUR FROM DUAL UNION
	SELECT 630 AS OBJECTID, 'Emprises hospitalières' AS VALEUR FROM DUAL UNION
	SELECT 631 AS OBJECTID, 'Emprises scolaires / universitaires' AS VALEUR FROM DUAL UNION
	SELECT 632 AS OBJECTID, 'Ensembles collectifs' AS VALEUR FROM DUAL UNION
	SELECT 633 AS OBJECTID, 'Espaces agricoles non exploités' AS VALEUR FROM DUAL UNION
	SELECT 634 AS OBJECTID, 'Espaces associés aux réseaux de transport' AS VALEUR FROM DUAL UNION
	SELECT 636 AS OBJECTID, 'Extraction de matériaux en mutation' AS VALEUR FROM DUAL UNION
	SELECT 637 AS OBJECTID, 'Ferré' AS VALEUR FROM DUAL UNION
	SELECT 638 AS OBJECTID, 'Ferré principal' AS VALEUR FROM DUAL UNION
	SELECT 639 AS OBJECTID, 'Ferré secondaire' AS VALEUR FROM DUAL UNION
	SELECT 642 AS OBJECTID, 'Fluvial et maritime' AS VALEUR FROM DUAL UNION
	SELECT 652 AS OBJECTID, 'Friches d''activités économiques' AS VALEUR FROM DUAL UNION
	SELECT 653 AS OBJECTID, 'Golfs' AS VALEUR FROM DUAL UNION
	SELECT 654 AS OBJECTID, 'Grands ensembles collectifs' AS VALEUR FROM DUAL UNION
	SELECT 655 AS OBJECTID, 'Habitat' AS VALEUR FROM DUAL UNION
	SELECT 656 AS OBJECTID, 'Habitat continu faiblement compact' AS VALEUR FROM DUAL UNION
	SELECT 657 AS OBJECTID, 'Habitat continu fortement compact' AS VALEUR FROM DUAL UNION
	SELECT 658 AS OBJECTID, 'Habitat continu moyennement compact' AS VALEUR FROM DUAL UNION
	SELECT 659 AS OBJECTID, 'Habitat discontinu faiblement compact' AS VALEUR FROM DUAL UNION
	SELECT 660 AS OBJECTID, 'Habitat discontinu fortement compact' AS VALEUR FROM DUAL UNION
	SELECT 661 AS OBJECTID, 'Habitat discontinu moyennement compact' AS VALEUR FROM DUAL UNION
	SELECT 662 AS OBJECTID, 'Habitat isolé' AS VALEUR FROM DUAL UNION
	SELECT 663 AS OBJECTID, 'Horticulture' AS VALEUR FROM DUAL UNION
	SELECT 664 AS OBJECTID, 'Infrastructures agricoles' AS VALEUR FROM DUAL UNION
	SELECT 668 AS OBJECTID, 'Loisirs et services culturels' AS VALEUR FROM DUAL UNION
	SELECT 670 AS OBJECTID, 'Parcs et Espaces verts paysagers' AS VALEUR FROM DUAL UNION
	SELECT 671 AS OBJECTID, 'Parkings et places' AS VALEUR FROM DUAL UNION
	SELECT 676 AS OBJECTID, 'Peupleraies' AS VALEUR FROM DUAL UNION
	SELECT 679 AS OBJECTID, 'Plantations récentes' AS VALEUR FROM DUAL UNION
	SELECT 681 AS OBJECTID, 'Prairies ' AS VALEUR FROM DUAL UNION
	SELECT 684 AS OBJECTID, 'Production primaire' AS VALEUR FROM DUAL UNION
	SELECT 685 AS OBJECTID, 'Routier' AS VALEUR FROM DUAL UNION
	SELECT 686 AS OBJECTID, 'Routier principal' AS VALEUR FROM DUAL UNION
	SELECT 687 AS OBJECTID, 'Routier secondaire' AS VALEUR FROM DUAL UNION
	SELECT 688 AS OBJECTID, 'Réseaux de transports, logistiques et infrastructures' AS VALEUR FROM DUAL UNION
	SELECT 691 AS OBJECTID, 'Services et usages collectifs' AS VALEUR FROM DUAL UNION
	SELECT 692 AS OBJECTID, 'Services publics, administratifs et collectifs' AS VALEUR FROM DUAL UNION
	SELECT 702 AS OBJECTID, 'Sylviculture' AS VALEUR FROM DUAL UNION
	SELECT 705 AS OBJECTID, 'Terrils en exploitation' AS VALEUR FROM DUAL UNION
	SELECT 706 AS OBJECTID, 'Tissu urbain continu' AS VALEUR FROM DUAL UNION
	SELECT 707 AS OBJECTID, 'Tissu urbain discontinu' AS VALEUR FROM DUAL UNION
	SELECT 708 AS OBJECTID, 'USAGE DU SOL' AS VALEUR FROM DUAL UNION
	SELECT 709 AS OBJECTID, 'Usages indéterminés' AS VALEUR FROM DUAL UNION
	SELECT 710 AS OBJECTID, 'Usages temporaires' AS VALEUR FROM DUAL UNION
	SELECT 713 AS OBJECTID, 'Zones commerciales' AS VALEUR FROM DUAL UNION
	SELECT 714 AS OBJECTID, 'Zones de coupes' AS VALEUR FROM DUAL UNION
	SELECT 715 AS OBJECTID, 'Zones de stockage gaz et hydrocarbures' AS VALEUR FROM DUAL UNION
	SELECT 716 AS OBJECTID, 'Zones délaissées' AS VALEUR FROM DUAL UNION
	SELECT 717 AS OBJECTID, 'Zones en mutation' AS VALEUR FROM DUAL UNION
	SELECT 718 AS OBJECTID, 'Zones industrielles et d''activités économiques' AS VALEUR FROM DUAL
	)b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT (a.objectid,a.valeur)
VALUES (b.objectid,b.valeur)
;


--TA_FAMILLE_LIBELLE
MERGE INTO G_GEO.TA_FAMILLE_LIBELLE a
USING
	(
	SELECT 210 AS FID_FAMILLE, '608' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '611' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '612' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '620' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '621' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '622' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '625' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '628' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '629' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '635' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '640' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '641' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '643' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '644' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '645' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '646' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '647' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '648' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '649' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '650' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '651' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '665' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '666' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '667' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '669' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '672' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '673' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '674' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '675' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '677' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '678' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '680' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '682' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '683' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '689' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '690' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '693' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '694' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '695' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '696' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '697' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '698' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '699' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '700' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '701' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '703' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '711' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 210 AS FID_FAMILLE, '712' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '600' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '601' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '602' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '603' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '604' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '605' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '607' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '609' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '610' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '613' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '614' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '615' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '616' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '617' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '618' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '619' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '623' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '624' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '626' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '627' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '630' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '631' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '632' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '633' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '634' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '636' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '637' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '638' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '639' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '642' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '652' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '653' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '654' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '655' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '656' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '657' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '658' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '659' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '660' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '661' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '662' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '663' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '664' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '668' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '670' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '671' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '676' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '679' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '681' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '684' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '685' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '686' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '687' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '688' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '691' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '692' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '702' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '705' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '706' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '707' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '708' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '709' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '710' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '713' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '714' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '715' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '716' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '717' AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 211 AS FID_FAMILLE, '718' AS FID_LIBELLE_LONG FROM DUAL
	)b
ON (a.fid_famille = b.fid_famille
AND a.fid_libelle_long = b.fid_libelle_long)
WHEN NOT MATCHED THEN
INSERT (a.fid_famille,a.fid_libelle_long)
VALUES (b.fid_famille,b.fid_libelle_long)
;


-- TA_LIBELLE
MERGE INTO G_GEO.TA_LIBELLE a
USING
	(
	SELECT 1042 AS OBJECTID, 690 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1085 AS OBJECTID, 647 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 994 AS OBJECTID, 689 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1008 AS OBJECTID, 699 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1036 AS OBJECTID, 649 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1030 AS OBJECTID, 672 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 996 AS OBJECTID, 697 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1032 AS OBJECTID, 711 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1050 AS OBJECTID, 621 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1062 AS OBJECTID, 701 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1043 AS OBJECTID, 667 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1082 AS OBJECTID, 674 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1041 AS OBJECTID, 678 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 989 AS OBJECTID, 640 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 985 AS OBJECTID, 648 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1067 AS OBJECTID, 620 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 976 AS OBJECTID, 693 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1027 AS OBJECTID, 703 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1049 AS OBJECTID, 641 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1070 AS OBJECTID, 666 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1086 AS OBJECTID, 695 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 980 AS OBJECTID, 643 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1024 AS OBJECTID, 608 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1063 AS OBJECTID, 669 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 997 AS OBJECTID, 650 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1010 AS OBJECTID, 677 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1034 AS OBJECTID, 677 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1072 AS OBJECTID, 682 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1001 AS OBJECTID, 665 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1071 AS OBJECTID, 651 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 972 AS OBJECTID, 612 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1014 AS OBJECTID, 673 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1004 AS OBJECTID, 629 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1046 AS OBJECTID, 694 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1077 AS OBJECTID, 698 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1060 AS OBJECTID, 646 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1035 AS OBJECTID, 608 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 983 AS OBJECTID, 644 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1095 AS OBJECTID, 712 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1052 AS OBJECTID, 650 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1065 AS OBJECTID, 640 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1021 AS OBJECTID, 645 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 978 AS OBJECTID, 696 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 993 AS OBJECTID, 628 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1039 AS OBJECTID, 635 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1068 AS OBJECTID, 622 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 975 AS OBJECTID, 700 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 990 AS OBJECTID, 680 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1022 AS OBJECTID, 649 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1089 AS OBJECTID, 611 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1051 AS OBJECTID, 683 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1007 AS OBJECTID, 672 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1064 AS OBJECTID, 625 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1019 AS OBJECTID, 711 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1013 AS OBJECTID, 703 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1054 AS OBJECTID, 675 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1002 AS OBJECTID, 620 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1047 AS OBJECTID, 614 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1092 AS OBJECTID, 616 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1059 AS OBJECTID, 660 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1097 AS OBJECTID, 613 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1105 AS OBJECTID, 607 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 979 AS OBJECTID, 691 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 984 AS OBJECTID, 710 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1079 AS OBJECTID, 705 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1084 AS OBJECTID, 715 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1073 AS OBJECTID, 610 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1075 AS OBJECTID, 687 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1094 AS OBJECTID, 656 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1018 AS OBJECTID, 642 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1099 AS OBJECTID, 671 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1061 AS OBJECTID, 718 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1102 AS OBJECTID, 618 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 988 AS OBJECTID, 685 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1069 AS OBJECTID, 676 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1101 AS OBJECTID, 624 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 973 AS OBJECTID, 708 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 974 AS OBJECTID, 684 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1040 AS OBJECTID, 681 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 987 AS OBJECTID, 709 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1104 AS OBJECTID, 605 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1023 AS OBJECTID, 634 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1090 AS OBJECTID, 623 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1088 AS OBJECTID, 653 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1003 AS OBJECTID, 702 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1006 AS OBJECTID, 716 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1031 AS OBJECTID, 709 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1056 AS OBJECTID, 652 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1028 AS OBJECTID, 713 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1074 AS OBJECTID, 639 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1096 AS OBJECTID, 659 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 991 AS OBJECTID, 603 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1012 AS OBJECTID, 609 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1078 AS OBJECTID, 630 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 995 AS OBJECTID, 706 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 999 AS OBJECTID, 718 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 982 AS OBJECTID, 655 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1000 AS OBJECTID, 637 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1100 AS OBJECTID, 600 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1038 AS OBJECTID, 615 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1020 AS OBJECTID, 604 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1026 AS OBJECTID, 662 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1057 AS OBJECTID, 657 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1058 AS OBJECTID, 631 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1080 AS OBJECTID, 658 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1093 AS OBJECTID, 633 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1055 AS OBJECTID, 670 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1016 AS OBJECTID, 601 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1081 AS OBJECTID, 636 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1048 AS OBJECTID, 686 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1066 AS OBJECTID, 617 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1015 AS OBJECTID, 632 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1053 AS OBJECTID, 654 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1091 AS OBJECTID, 679 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1098 AS OBJECTID, 663 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1029 AS OBJECTID, 642 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 986 AS OBJECTID, 709 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 977 AS OBJECTID, 602 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1076 AS OBJECTID, 627 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1033 AS OBJECTID, 604 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1103 AS OBJECTID, 626 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1106 AS OBJECTID, 664 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1009 AS OBJECTID, 707 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1017 AS OBJECTID, 662 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1011 AS OBJECTID, 668 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1037 AS OBJECTID, 634 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1005 AS OBJECTID, 713 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1025 AS OBJECTID, 609 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1044 AS OBJECTID, 714 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 992 AS OBJECTID, 717 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 998 AS OBJECTID, 692 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1045 AS OBJECTID, 638 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1083 AS OBJECTID, 661 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 1087 AS OBJECTID, 619 AS FID_LIBELLE_LONG FROM DUAL UNION
	SELECT 981 AS OBJECTID, 688 AS FID_LIBELLE_LONG FROM DUAL
	)b
ON (a.fid_famille = b.fid_famille
AND a.fid_libelle_long = b.fid_libelle_long)
WHEN NOT MATCHED THEN
INSERT (a.fid_famille,a.fid_libelle_long)
VALUES (b.fid_famille,b.fid_libelle_long)
;


-- TA_LIBELLE_RELATION
MERGE INTO G_GEO.TA_LIBELLE_RELATION a
USING
	(
	SELECT 975 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 976 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 978 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 980 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 983 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 985 AS fid_libelle_fils, 972 AS fid_libelle_parent FROM DUAL UNION
	SELECT 989 AS fid_libelle_fils, 980 AS fid_libelle_parent FROM DUAL UNION
	SELECT 990 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 993 AS fid_libelle_fils, 978 AS fid_libelle_parent FROM DUAL UNION
	SELECT 994 AS fid_libelle_fils, 976 AS fid_libelle_parent FROM DUAL UNION
	SELECT 996 AS fid_libelle_fils, 975 AS fid_libelle_parent FROM DUAL UNION
	SELECT 997 AS fid_libelle_fils, 983 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1001 AS fid_libelle_fils, 983 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1002 AS fid_libelle_fils, 980 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1004 AS fid_libelle_fils, 978 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1007 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1008 AS fid_libelle_fils, 975 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1010 AS fid_libelle_fils, 976 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1013 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1014 AS fid_libelle_fils, 980 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1019 AS fid_libelle_fils, 980 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1021 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1022 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1024 AS fid_libelle_fils, 985 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1027 AS fid_libelle_fils, 1013 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1030 AS fid_libelle_fils, 1007 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1032 AS fid_libelle_fils, 1019 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1034 AS fid_libelle_fils, 1010 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1035 AS fid_libelle_fils, 1024 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1036 AS fid_libelle_fils, 1022 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1039 AS fid_libelle_fils, 1004 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1041 AS fid_libelle_fils, 993 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1042 AS fid_libelle_fils, 994 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1043 AS fid_libelle_fils, 1001 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1046 AS fid_libelle_fils, 996 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1049 AS fid_libelle_fils, 989 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1050 AS fid_libelle_fils, 1002 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1051 AS fid_libelle_fils, 990 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1052 AS fid_libelle_fils, 997 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1054 AS fid_libelle_fils, 1014 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1060 AS fid_libelle_fils, 1021 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1062 AS fid_libelle_fils, 1008 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1063 AS fid_libelle_fils, 1004 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1064 AS fid_libelle_fils, 994 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1065 AS fid_libelle_fils, 989 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1067 AS fid_libelle_fils, 1002 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1068 AS fid_libelle_fils, 993 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1070 AS fid_libelle_fils, 1001 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1071 AS fid_libelle_fils, 997 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1072 AS fid_libelle_fils, 990 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1077 AS fid_libelle_fils, 996 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1082 AS fid_libelle_fils, 1014 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1085 AS fid_libelle_fils, 1021 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1086 AS fid_libelle_fils, 1008 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1089 AS fid_libelle_fils, 989 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1095 AS fid_libelle_fils, 997 AS fid_libelle_parent FROM DUAL UNION
	SELECT 974 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 977 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 979 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 981 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 982 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 984 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 986 AS fid_libelle_fils, 973 AS fid_libelle_parent FROM DUAL UNION
	SELECT 987 AS fid_libelle_fils, 986 AS fid_libelle_parent FROM DUAL UNION
	SELECT 988 AS fid_libelle_fils, 981 AS fid_libelle_parent FROM DUAL UNION
	SELECT 991 AS fid_libelle_fils, 974 AS fid_libelle_parent FROM DUAL UNION
	SELECT 992 AS fid_libelle_fils, 984 AS fid_libelle_parent FROM DUAL UNION
	SELECT 995 AS fid_libelle_fils, 982 AS fid_libelle_parent FROM DUAL UNION
	SELECT 998 AS fid_libelle_fils, 979 AS fid_libelle_parent FROM DUAL UNION
	SELECT 999 AS fid_libelle_fils, 977 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1000 AS fid_libelle_fils, 981 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1003 AS fid_libelle_fils, 974 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1005 AS fid_libelle_fils, 977 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1006 AS fid_libelle_fils, 984 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1009 AS fid_libelle_fils, 982 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1011 AS fid_libelle_fils, 979 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1012 AS fid_libelle_fils, 981 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1015 AS fid_libelle_fils, 982 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1016 AS fid_libelle_fils, 974 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1017 AS fid_libelle_fils, 982 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1018 AS fid_libelle_fils, 981 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1020 AS fid_libelle_fils, 974 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1023 AS fid_libelle_fils, 981 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1025 AS fid_libelle_fils, 1012 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1026 AS fid_libelle_fils, 1017 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1028 AS fid_libelle_fils, 1005 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1029 AS fid_libelle_fils, 1018 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1031 AS fid_libelle_fils, 987 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1033 AS fid_libelle_fils, 1020 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1037 AS fid_libelle_fils, 1023 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1038 AS fid_libelle_fils, 992 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1040 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1044 AS fid_libelle_fils, 1003 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1045 AS fid_libelle_fils, 1000 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1047 AS fid_libelle_fils, 1016 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1048 AS fid_libelle_fils, 988 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1053 AS fid_libelle_fils, 1015 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1055 AS fid_libelle_fils, 1011 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1056 AS fid_libelle_fils, 1006 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1057 AS fid_libelle_fils, 995 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1058 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1059 AS fid_libelle_fils, 1009 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1061 AS fid_libelle_fils, 999 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1066 AS fid_libelle_fils, 1015 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1069 AS fid_libelle_fils, 1003 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1073 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1074 AS fid_libelle_fils, 1000 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1075 AS fid_libelle_fils, 988 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1076 AS fid_libelle_fils, 1006 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1078 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1079 AS fid_libelle_fils, 1016 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1080 AS fid_libelle_fils, 995 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1081 AS fid_libelle_fils, 992 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1083 AS fid_libelle_fils, 1009 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1084 AS fid_libelle_fils, 999 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1087 AS fid_libelle_fils, 1011 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1088 AS fid_libelle_fils, 1011 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1090 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1091 AS fid_libelle_fils, 1003 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1092 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1093 AS fid_libelle_fils, 1006 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1094 AS fid_libelle_fils, 995 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1096 AS fid_libelle_fils, 1009 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1097 AS fid_libelle_fils, 1011 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1098 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1099 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1100 AS fid_libelle_fils, 1003 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1101 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1102 AS fid_libelle_fils, 1011 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1103 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1104 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1105 AS fid_libelle_fils, 998 AS fid_libelle_parent FROM DUAL UNION
	SELECT 1106 AS fid_libelle_fils, 991 AS fid_libelle_parent FROM DUAL
	)b
ON (a.fid_libelle_fils = b.fid_libelle_fils
AND a.fid_libelle_parent = b.fid_libelle_parent)
WHEN NOT MATCHED THEN
INSERT (a.fid_libelle_fils,a.fid_libelle_parent)
VALUES (b.fid_libelle_fils,b.fid_libelle_parent)
;

-- MAJ TA_LIBELLE_COURT
ALTER TABLE G_GEO.TA_LIBELLE_COURT MODIFY OBJECTID NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY; 

-- TA_LIBELLE_COURT --10
MERGE INTO G_GEO.TA_LIBELLE_COURT a
USING
	(
	SELECT 10 AS OBJECTID, 1 AS VALEUR FROM DUAL UNION
	SELECT 21 AS OBJECTID, 2 AS VALEUR FROM DUAL UNION
	SELECT 30 AS OBJECTID, 3 AS VALEUR FROM DUAL UNION
	SELECT 39 AS OBJECTID, 4 AS VALEUR FROM DUAL UNION
	SELECT 44 AS OBJECTID, 5 AS VALEUR FROM DUAL UNION
	SELECT 45 AS OBJECTID, 6 AS VALEUR FROM DUAL UNION
	SELECT 46 AS OBJECTID, 7 AS VALEUR FROM DUAL UNION
	SELECT 493 AS OBJECTID, US AS VALEUR FROM DUAL UNION
	SELECT 494 AS OBJECTID, CS AS VALEUR FROM DUAL UNION
	SELECT 55 AS OBJECTID, 0 AS VALEUR FROM DUAL
	)b
ON (a.OBJECTID = b.OBJECTID
AND a.VALEUR = b.VALEUR)
WHEN NOT MATCHED THEN
INSERT (a.OBJECTID,a.VALEUR)
VALUES (b.OBJECTID,b.VALEUR)
;


-- TA_LIBELLE_CORRESPONDANCE --135
MERGE INTO G_GEO.TA_LIBELLE_CORRESPONDANCE a
USING
	(
	SELECT 1042 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1085 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 994 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1008 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1036 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1030 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 996 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1032 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1050 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1062 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1043 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1082 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1041 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 989 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 985 AS fid_libelle, 45 AS fid_libelle_court FROM DUAL UNION
	SELECT 1067 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 976 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1027 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1049 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1070 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1086 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 980 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1024 AS fid_libelle, 45 AS fid_libelle_court FROM DUAL UNION
	SELECT 1063 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 997 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1010 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1034 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1072 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1001 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1071 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 972 AS fid_libelle, 494 AS fid_libelle_court FROM DUAL UNION
	SELECT 1014 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1004 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1046 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1077 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1060 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1035 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 983 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 1095 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1052 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1065 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1021 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 978 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 993 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1039 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1068 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 975 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 990 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1022 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 1089 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1051 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1007 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1064 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1019 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1013 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1054 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1002 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1047 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1092 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1059 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1097 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1105 AS fid_libelle, 45 AS fid_libelle_court FROM DUAL UNION
	SELECT 979 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 984 AS fid_libelle, 45 AS fid_libelle_court FROM DUAL UNION
	SELECT 1079 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1084 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1073 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1075 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1094 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1018 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1099 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1061 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1102 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 988 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1069 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1101 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 973 AS fid_libelle, 493 AS fid_libelle_court FROM DUAL UNION
	SELECT 974 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1040 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 987 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1104 AS fid_libelle, 45 AS fid_libelle_court FROM DUAL UNION
	SELECT 1023 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 1090 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1088 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1003 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1006 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1031 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1056 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1028 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1074 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1096 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 991 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1012 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1078 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 995 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 999 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 982 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 1000 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1100 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1038 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1020 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1026 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1057 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1058 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1080 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1093 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1055 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1016 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1081 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1048 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1066 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1015 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1053 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1091 AS fid_libelle, 30 AS fid_libelle_court FROM DUAL UNION
	SELECT 1098 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1029 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 986 AS fid_libelle, 46 AS fid_libelle_court FROM DUAL UNION
	SELECT 977 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1076 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1033 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1103 AS fid_libelle, 44 AS fid_libelle_court FROM DUAL UNION
	SELECT 1106 AS fid_libelle, 46 AS fid_libelle_court FROM DUAL UNION
	SELECT 1009 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1017 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL UNION
	SELECT 1011 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1037 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1005 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1025 AS fid_libelle, 55 AS fid_libelle_court FROM DUAL UNION
	SELECT 1044 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 992 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 998 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1045 AS fid_libelle, 10 AS fid_libelle_court FROM DUAL UNION
	SELECT 1083 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 1087 AS fid_libelle, 21 AS fid_libelle_court FROM DUAL UNION
	SELECT 981 AS fid_libelle, 39 AS fid_libelle_court FROM DUAL
	)b
ON (a.fid_libelle = b.fid_libelle
AND a.fid_libelle_court = b.fid_libelle_court)
WHEN NOT MATCHED THEN
INSERT (a.fid_libelle,a.fid_libelle_court)
VALUES (b.fid_libelle,b.fid_libelle_court)
;

-- INDICE
-- FAMILLE
MERGE INTO G_GEO.TA_FAMILLE a
USING
    (
    SELECT
    	269 AS objectid, 
    	'Indice de confiance à la photo-interprétation OCS2D' AS VALEUR
    FROM 
    	DUAL
    )b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.valeur)
VALUES(b.objectid,b.valeur)
;

-- LIBELLE_LONG
MERGE INTO G_GEO.TA_LIBELLE_LONG a
USING
    (
	SELECT 820 AS objectid, 'validation terrain' AS VALEUR FROM DUAL UNION
	SELECT 821 AS objectid, 'photo-interprétation fiable' AS VALEUR FROM DUAL UNION
	SELECT 822 AS objectid, 'photo-interprétation problématique – pas de donnée exogène ou de terrain pour soutenir l’interprétation' AS VALEUR FROM DUAL UNION
	SELECT 823 AS objectid, 'données exogènes utilisées (précision de la référence biblio dans le champ source)' AS VALEUR FROM DUAL UNION
	SELECT 824 AS objectid, '« dire d’expert »  (connaissances personnelles locales)' AS VALEUR FROM DUAL
    )b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.valeur)
VALUES(b.objectid,b.valeur)
;

-- TA_FAMILLE_LIBELLE
MERGE INTO G_GEO.TA_FAMILLE_LIBELLE a
USING
    (
	SELECT 269 AS fid_famille, '820' AS fid_libelle_long FROM DUAL UNION
	SELECT 269 AS fid_famille, '821' AS fid_libelle_long FROM DUAL UNION
	SELECT 269 AS fid_famille, '822' AS fid_libelle_long FROM DUAL UNION
	SELECT 269 AS fid_famille, '823' AS fid_libelle_long FROM DUAL UNION
	SELECT 269 AS fid_famille, '824' AS fid_libelle_long FROM DUAL
    )b
ON (a.fid_famille = b.fid_famille
AND a.fid_libelle_long = b.fid_libelle_long)
WHEN NOT MATCHED THEN
INSERT(a.fid_famille, a.fid_libelle_long)
VALUES(b.fid_famille,b.fid_libelle_long)
;

-- TA_LIBELLE
MERGE INTO G_GEO.TA_LIBELLE a
USING
    (
	SELECT 1232 AS objectid, '823' AS fid_libelle_long FROM DUAL UNION
	SELECT 1233 AS objectid, '824' AS fid_libelle_long FROM DUAL UNION
	SELECT 1234 AS objectid, '820' AS fid_libelle_long FROM DUAL UNION
	SELECT 1235 AS objectid, '822' AS fid_libelle_long FROM DUAL UNION
	SELECT 1236 AS objectid, '821' AS fid_libelle_long FROM DUAL
    )b
ON (a.objectid = b.objectid
AND a.fid_libelle_long = b.fid_libelle_long)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.fid_libelle_long)
VALUES(b.objectid,b.fid_libelle_long)
;


-- TA_LIBELLE_COURT
MERGE INTO G_GEO.TA_LIBELLE_COURT a
USING
    (
	SELECT 10 AS objectid, '1' AS valeur FROM DUAL UNION
	SELECT 21 AS objectid, '2' AS valeur FROM DUAL UNION
	SELECT 30 AS objectid, '3' AS valeur FROM DUAL UNION
	SELECT 39 AS objectid, '4' AS valeur FROM DUAL UNION
	SELECT 44 AS objectid, '5' AS valeur FROM DUAL
    )b
ON (a.objectid = b.objectid
AND a.valeur = b.valeur)
WHEN NOT MATCHED THEN
INSERT(a.objectid, a.valeur)
VALUES(b.objectid,b.valeur)
;


-- TA_LIBELLE_CORRESPONDANCE
MERGE INTO G_GEO.TA_LIBELLE_CORRESPONDANCE a
USING
    (
	SELECT 1236 AS fid_libelle, '10' AS fid_libelle_court FROM DUAL UNION
	SELECT 1235 AS fid_libelle, '21' AS fid_libelle_court FROM DUAL UNION
	SELECT 1232 AS fid_libelle, '30' AS fid_libelle_court FROM DUAL UNION
	SELECT 1233 AS fid_libelle, '39' AS fid_libelle_court FROM DUAL UNION
	SELECT 1234 AS fid_libelle, '44' AS fid_libelle_court FROM DUAL
	)b
ON (a.fid_libelle = b.fid_libelle
AND a.fid_libelle_court = b.fid_libelle_court)
WHEN NOT MATCHED THEN
INSERT (a.fid_libelle,a.fid_libelle_court)
VALUES (b.fid_libelle,b.fid_libelle_court)
;

-- COMMENTAIRE OCS2D

