/*
Affectation des droits de lecture et de référence vers le schéma G_GEO pour les métadonnées et les Familles/Libellés.
*/

GRANT REFERENCES ON G_GEO.TA_METADONNEE TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_METADONNEE TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_SOURCE TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_PROVENANCE TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_DATE_ACQUISITION TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_METADONNEE_RELATION_ORGANISME TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_ORGANISME TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_METADONNEE_RELATION_ECHELLE TO G_OCS2D WITH GRANT OPTION;
GRANT SELECT ON G_GEO.TA_ECHELLE TO G_OCS2D WITH GRANT OPTION;

-- 1. SEQUENCE
-- 1.1. G_OCS2D_R
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_GEOM_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_MILLESIME_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_RELATION_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_COMMENTAIRE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_SOURCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_FAMILLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_LONG_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_FAMILLE_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_COURT_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_RELATION_COMMENTAIRE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_RELATION_SOURCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_CORRESPONDANCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_RELATION_OBJECTID TO G_OCS2D_RW;
GRANT SELECT ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_RELATION_NOMENCLATURE_OBJECTID TO G_OCS2D_RW;

-- 1.2. G_OCS2D_RW
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_GEOM_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_MILLESIME_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_RELATION_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_COMMENTAIRE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_SOURCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_FAMILLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_LONG_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_FAMILLE_LIBELLE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_COURT_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_RELATION_COMMENTAIRE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_RELATION_SOURCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_CORRESPONDANCE_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_RELATION_OBJECTID TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.SEQ_TA_OCS2D_LIBELLE_RELATION_NOMENCLATURE_OBJECTID TO G_OCS2D_RW;

-- 2. TABLE
-- 2.1. G_OCS2D_R
GRANT SELECT ON G_OCS2D.TA_OCS2D TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_RELATION_LIBELLE TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_GEOM TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_RELATION_GEOM TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_MILLESIME TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_COMMENTAIRE TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_RELATION_COMMENTAIRE TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_SOURCE TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_RELATION_SOURCE TO G_OCS2D_R;
GRANT SELECT ON G_OCS2D.TA_OCS2D_FAMILLE TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE_LONG TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_FAMILLE_LIBELLE TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE_COURT TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE_CORRESPONDANCE TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE_RELATION TO G_OCS2D
GRANT SELECT ON G_OCS2D.TA_OCS2D_LIBELLE_RELATION_NOMENCLATURE TO G_OCS2D

-- 2.2. G_OCS2D_RW
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_RELATION_LIBELLE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_GEOM TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_RELATION_GEOM TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_MILLESIME TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_COMMENTAIRE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_RELATION_COMMENTAIRE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_SOURCE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_RELATION_SOURCE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_FAMILLE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE_LONG TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_FAMILLE_LIBELLE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE_COURT TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE_CORRESPONDANCE TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE_RELATION TO G_OCS2D_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_LIBELLE_RELATION_NOMENCLATURE TO G_OCS2D_RW;