-- 1. Creation des tables de restitution des données OCS2D suivant la nomenclature 4 postes.

-- 1.1. Creation de la table TA_OCS2D_4_POSTES_2005_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_4_POSTES_2005_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL,
	poste_libelle VARCHAR2(255 BYTE) NOT NULL,
	perimetre NUMBER(38,2) NOT NULL,
	surface_m2 NUMBER(38,2) NOT NULL,
	surface_ha NUMBER(38,2) NOT NULL,
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT
ADD CONSTRAINT TA_OCS2D_4_POSTES_2005_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_4_POSTES_2005_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_4_POSTES_2005_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_4_POSTES_2005_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_4_POSTES_2005_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"  IS 'Table proposant les données OCS2D au format 4 postes en 2005.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."POSTE" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2005_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_4_POSTES_2005_SCOT TO G_OCS2D_RW;


-- 1.2. Creation de la table TA_OCS2D_4_POSTES_2015_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_4_POSTES_2015_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL, 
	poste_libelle VARCHAR2(255 BYTE) NOT NULL, 
	perimetre NUMBER(38,2) NOT NULL, 
	surface_m2 NUMBER(38,2) NOT NULL, 
	surface_ha NUMBER(38,2) NOT NULL,
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT
ADD CONSTRAINT TA_OCS2D_4_POSTES_2015_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_4_POSTES_2015_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_4_POSTES_2015_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_4_POSTES_2015_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_4_POSTES_2015_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"  IS 'Table proposant les données OCS2D au format 4 postes en 2015.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."POSTE" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2015_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_4_POSTES_2015_SCOT TO G_OCS2D_RW;


-- 1.3. Creation de la table TA_OCS2D_4_POSTES_2020_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_4_POSTES_2020_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL, 
	poste_libelle VARCHAR2(255 BYTE) NOT NULL, 
	perimetre NUMBER(38,2) NOT NULL, 
	surface_m2 NUMBER(38,2) NOT NULL, 
	surface_ha NUMBER(38,2) NOT NULL,
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT
ADD CONSTRAINT TA_OCS2D_4_POSTES_2020_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_4_POSTES_2020_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_4_POSTES_2020_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_4_POSTES_2020_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_4_POSTES_2020_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"  IS 'Table proposant les données OCS2D au format 4 postes en 2020.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."POSTE" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_4_POSTES_2020_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_4_POSTES_2020_SCOT TO G_OCS2D_RW;


-- 2. Creation des tables de restitution des données OCS2D suivant la nomenclature 21 postes.

-- 2.1. Creation de la table TA_OCS2D_21_POSTES_2005_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_21_POSTES_2005_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL, 
	poste_libelle VARCHAR2(255 BYTE) NOT NULL, 
	perimetre NUMBER(38,2) NOT NULL, 
	surface_m2 NUMBER(38,2) NOT NULL, 
	surface_ha NUMBER(38,2) NOT NULL,
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT
ADD CONSTRAINT TA_OCS2D_21_POSTES_2005_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_21_POSTES_2005_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_21_POSTES_2005_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_21_POSTES_2005_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_21_POSTES_2005_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"  IS 'Table proposant les données OCS2D au format 21 postes en 2005.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."POSTE" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2005_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_21_POSTES_2005_SCOT TO G_OCS2D_RW;


-- 2.2. Creation de la table TA_OCS2D_21_POSTES_2015_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_21_POSTES_2015_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL,
	poste_libelle VARCHAR2(255 BYTE) NOT NULL,
	perimetre NUMBER(38,2) NOT NULL,
	surface_m2 NUMBER(38,2) NOT NULL,
	surface_ha NUMBER(38,2) NOT NULL,
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT
ADD CONSTRAINT TA_OCS2D_21_POSTES_2015_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_21_POSTES_2015_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_21_POSTES_2015_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_21_POSTES_2015_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_21_POSTES_2015_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"  IS 'Table proposant les données OCS2D au format 21 postes en 2015.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."POSTE" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2015_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_21_POSTES_2015_SCOT TO G_OCS2D_RW;


-- 2.3. Creation de la table TA_OCS2D_21_POSTES_2020_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT" (
	identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_21_POSTES_2020_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
	poste NUMBER NOT NULL, 
	poste_libelle VARCHAR2(255 BYTE) NOT NULL, 
	perimetre NUMBER(38,2) NOT NULL, 
	surface_m2 NUMBER(38,2) NOT NULL, 
	surface_ha NUMBER(38,2) NOT NULL, 
	metadonnee VARCHAR2(200 BYTE) NOT NULL,
	geom SDO_GEOMETRY NOT NULL
	);

-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT
ADD CONSTRAINT TA_OCS2D_21_POSTES_2020_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";

-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_21_POSTES_2020_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_21_POSTES_2020_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres
CREATE INDEX TA_OCS2D_21_POSTES_2020_SCOT_POSTES_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT(poste)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_OCS2D_21_POSTES_2020_SCOT_POSTES_LIBELLE_IDX ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT(poste_libelle)
    TABLESPACE G_ADT_INDX;
    
-- Création des commentaires
COMMENT ON TABLE "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"  IS 'Table proposant les données OCS2D au format 21 postes en 2020.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."POSTE" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."POSTE_LIBELLE" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."IDENTIFIANT" IS 'Clé primaire de la table.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_21_POSTES_2020_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_21_POSTES_2020_SCOT TO G_OCS2D_RW;


-- 3. Creation des tables de restitution des données OCS2D millesime.

-- 3.1 Creation de la table TA_OCS2D_2005_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_2005_SCOT" (
		identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_2005_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
		cs_niveau_1 NUMBER(1) NOT NULL,
		libcs_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_2 NUMBER(1) NOT NULL,
		libcs_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_3 NUMBER(1) NOT NULL,
		libcs VARCHAR2(255 BYTE) NOT NULL,
		cs VARCHAR2(7 BYTE) NOT NULL,
		us_niveau_1 NUMBER(1) NOT NULL,
		libus_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_2 NUMBER(1) NOT NULL,
		libus_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_3 NUMBER(1) NOT NULL,
		libus VARCHAR2(255 BYTE) NOT NULL,
		us VARCHAR2(7 BYTE) NOT NULL,
		"CODE_4_POSTES" NUMBER(1) NOT NULL,
		"LIBELLE_4_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		"CODE_21_POSTES" NUMBER(2) NOT NULL,
		"LIBELLE_21_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		indice NUMBER(1) NOT NULL,
		"SOURCE_DONNEE" VARCHAR2(255 BYTE),
		"COMMENTAIRE" VARCHAR2(255 BYTE),
        perimetre NUMBER(38,2) NOT NULL,
        surface_m2 NUMBER(38,2) NOT NULL,
        surface_ha NUMBER(38,2) NOT NULL,
		metadonnee VARCHAR2(200 BYTE) NOT NULL,
		geom SDO_GEOMETRY NOT NULL
	);


-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_2005_SCOT
ADD CONSTRAINT TA_OCS2D_2005_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";


-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_2005_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;


-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_2005_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_2005_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CS_NIVEAU_1_CS_NIVEAU_2_CS_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CS_NIVEAU_1","CS_NIVEAU_2","CS_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CS"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_LIBCS"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("LIBCS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_US_NIVEAU_1_US_NIVEAU_2_US_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("US_NIVEAU_1","US_NIVEAU_2","US_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_US"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_LIBUS"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("LIBUS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CS_US"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CS","US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_US_CS"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("US","CS") 
TABLESPACE G_ADT_INDX;
CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CODE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CODE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CODE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CODE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CODE_4_POSTES_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CODE_4_POSTES","LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_CODE_21_POSTES_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("CODE_21_POSTES","LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_INDICE"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("INDICE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_SOURCE"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("SOURCE_DONNEE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2005_SCOT_COMMENT"
ON "G_OCS2D"."TA_OCS2D_2005_SCOT" ("COMMENTAIRE") 
TABLESPACE G_ADT_INDX;


COMMENT ON TABLE G_OCS2D.TA_OCS2D_2005_SCOT IS 'La table TA_OCS2D_2005_SCOT présente les données OCS2D à l''échelle du SCOT en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.IDENTIFIANT IS 'Clé primaire de la vue materialisee.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.CS_NIVEAU_1 IS 'Code caractérisant le type de couvert du sol au niveau 1 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBCS_NIVEAU_1 IS 'Libelle caractérisant le type de couvert du sol au niveau 1 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.CS_NIVEAU_2 IS 'Code caractérisant le type de couvert du sol au niveau 2 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBCS_NIVEAU_2 IS 'Libelle caractérisant le type de couvert du sol au niveau 2 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.CS_NIVEAU_3 IS 'Code caractérisant le type de couvert du sol au niveau 3 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBCS IS 'Libelle caractérisant le type de couvert du sol au niveau 3 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.CS IS 'Code caractérisant le type de couvert du sol complet en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.US_NIVEAU_1 IS 'Code caractérisant l''usage du sol au niveau 1 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBUS_NIVEAU_1 IS 'Libelle caractérisant l''usage du sol au niveau 1 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.US_NIVEAU_2 IS 'Code caractérisant l''usage du sol au niveau 2 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBUS_NIVEAU_2 IS 'Libelle caractérisant l''usage du sol au niveau 2 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.US_NIVEAU_3 IS 'Code caractérisant l''usage du sol au niveau 3 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.LIBUS IS 'Libelle caractérisant l''usage du sol au niveau 3 en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.US IS 'Code caractérisant l''usage du sol complet en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT."CODE_4_POSTES" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT."LIBELLE_4_POSTES" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT."CODE_21_POSTES" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT."LIBELLE_21_POSTES" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2005';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.INDICE IS 'Indice de la qualite de la photo-interpretation de la zone OCS2D en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT.SOURCE_DONNEE IS 'Données sources utilisées pour la production de la donnée OCS2D en 2005.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2005_SCOT."COMMENTAIRE" IS 'Commentaire sur le polygone OCS2D en 2005.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2005_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2005_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2005_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2005_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2005_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affection des droits
GRANT SELECT ON G_OCS2D.TA_OCS2D_2005_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_2005_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_2005_SCOT TO G_OCS2D_RW;

-- 3.2 Table TA_OCS2D_2015_SCOT
CREATE TABLE "G_OCS2D"."TA_OCS2D_2015_SCOT" (
		identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_2015_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
		cs_niveau_1 NUMBER(1) NOT NULL,
		libcs_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_2 NUMBER(1) NOT NULL,
		libcs_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_3 NUMBER(1) NOT NULL,
		libcs VARCHAR2(255 BYTE) NOT NULL,
		cs VARCHAR2(7 BYTE) NOT NULL,
		us_niveau_1 NUMBER(1) NOT NULL,
		libus_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_2 NUMBER(1) NOT NULL,
		libus_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_3 NUMBER(1) NOT NULL,
		libus VARCHAR2(255 BYTE) NOT NULL,
		us VARCHAR2(7 BYTE) NOT NULL,
		"CODE_4_POSTES" NUMBER(1) NOT NULL,
		"LIBELLE_4_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		"CODE_21_POSTES" NUMBER(2) NOT NULL,
		"LIBELLE_21_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		evol05_15 NUMBER(10,0) NOT NULL,
		indice NUMBER(1) NOT NULL,
		"SOURCE_DONNEE" VARCHAR2(255 BYTE),
		"COMMENTAIRE" VARCHAR2(255 BYTE),
        perimetre NUMBER(38,2) NOT NULL,
        surface_m2 NUMBER(38,2) NOT NULL,
        surface_ha NUMBER(38,2) NOT NULL,
		metadonnee VARCHAR2(200 BYTE) NOT NULL,
		geom SDO_GEOMETRY NOT NULL
	);


-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_2015_SCOT
ADD CONSTRAINT TA_OCS2D_2015_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";


-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_2015_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;


-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_2015_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_2015_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CS_NIVEAU_1_CS_NIVEAU_2_CS_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CS_NIVEAU_1","CS_NIVEAU_2","CS_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CS"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_LIBCS"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("LIBCS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_US_NIVEAU_1_US_NIVEAU_2_US_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("US_NIVEAU_1","US_NIVEAU_2","US_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_US"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_LIBUS"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("LIBUS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CS_US"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CS","US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_US_CS"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("US","CS") 
TABLESPACE G_ADT_INDX;
CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CODE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CODE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CODE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CODE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CODE_4_POSTES_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CODE_4_POSTES","LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_CODE_21_POSTES_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("CODE_21_POSTES","LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_INDICE"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("INDICE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_SOURCE"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("SOURCE_DONNEE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2015_SCOT_COMMENT"
ON "G_OCS2D"."TA_OCS2D_2015_SCOT" ("COMMENTAIRE") 
TABLESPACE G_ADT_INDX;


COMMENT ON TABLE G_OCS2D.TA_OCS2D_2015_SCOT IS 'La table TA_OCS2D_2015_SCOT présente les données OCS2D à l''échelle du SCOT en 2015';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.IDENTIFIANT IS 'Clé primaire de la vue materialisee.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.CS_NIVEAU_1 IS 'Code caractérisant le type de couvert du sol au niveau 1 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBCS_NIVEAU_1 IS 'Libelle caractérisant le type de couvert du sol au niveau 1 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.CS_NIVEAU_2 IS 'Code caractérisant le type de couvert du sol au niveau 2 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBCS_NIVEAU_2 IS 'Libelle caractérisant le type de couvert du sol au niveau 2 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.CS_NIVEAU_3 IS 'Code caractérisant le type de couvert du sol au niveau 3 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBCS IS 'Libelle caractérisant le type de couvert du sol au niveau 3 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.CS IS 'Code caractérisant le type de couvert du sol complet en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.US_NIVEAU_1 IS 'Code caractérisant l''usage du sol au niveau 1 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBUS_NIVEAU_1 IS 'Libelle caractérisant l''usage du sol au niveau 1 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.US_NIVEAU_2 IS 'Code caractérisant l''usage du sol au niveau 2 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBUS_NIVEAU_2 IS 'Libelle caractérisant l''usage du sol au niveau 2 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.US_NIVEAU_3 IS 'Code caractérisant l''usage du sol au niveau 3 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.LIBUS IS 'Libelle caractérisant l''usage du sol au niveau 3 en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.US IS 'Code caractérisant l''usage du sol complet en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT."CODE_4_POSTES" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT."LIBELLE_4_POSTES" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT."CODE_21_POSTES" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT."LIBELLE_21_POSTES" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2015';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.INDICE IS 'Indice de la qualite de la photo-interpretation de la zone OCS2D en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.SOURCE_DONNEE IS 'Données sources utilisées pour la production de la donnée OCS2D en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT."COMMENTAIRE" IS 'Commentaire sur le polygone OCS2D en 2015.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2015_SCOT.EVOL05_15 IS 'Code qui caractérise une evolution en les millesime 2005 et 2015. 1 pas d''évolution des codes, 2 évolutions.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2015_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2015_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2015_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2015_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2015_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';

-- Affection des droits
GRANT SELECT ON G_OCS2D.TA_OCS2D_2015_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_2015_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_2015_SCOT TO G_OCS2D_RW;

-- 3. Table TA_OCS2D_2020_SCOT.
CREATE TABLE "G_OCS2D"."TA_OCS2D_2020_SCOT" (
		identifiant NUMBER(38,0) DEFAULT SEQ_TA_OCS2D_2020_SCOT_IDENTIFIANT.NEXTVAL NOT NULL,
		cs_niveau_1 NUMBER(1) NOT NULL,
		libcs_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_2 NUMBER(1) NOT NULL,
		libcs_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		cs_niveau_3 NUMBER(1) NOT NULL,
		libcs VARCHAR2(255 BYTE) NOT NULL,
		cs VARCHAR2(7 BYTE) NOT NULL,
		us_niveau_1 NUMBER(1) NOT NULL,
		libus_niveau_1 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_2 NUMBER(1) NOT NULL,
		libus_niveau_2 VARCHAR2(255 BYTE) NOT NULL,
		us_niveau_3 NUMBER(1) NOT NULL,
		libus VARCHAR2(255 BYTE) NOT NULL,
		us VARCHAR2(7 BYTE) NOT NULL,
		"CODE_4_POSTES" NUMBER(1) NOT NULL,
		"LIBELLE_4_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		"CODE_21_POSTES" NUMBER(2) NOT NULL,
		"LIBELLE_21_POSTES" VARCHAR2(255 BYTE) NOT NULL,
		evol15_20 NUMBER(10,0) NOT NULL,
		indice NUMBER(1) NOT NULL,
		"SOURCE_DONNEE" VARCHAR2(255 BYTE),
		"COMMENTAIRE" VARCHAR2(255 BYTE),
        perimetre NUMBER(38,2) NOT NULL,
        surface_m2 NUMBER(38,2) NOT NULL,
        surface_ha NUMBER(38,2) NOT NULL,
		metadonnee VARCHAR2(200 BYTE) NOT NULL,
		geom SDO_GEOMETRY NOT NULL
	);


-- Création de la contrainte de clé primaire
ALTER TABLE G_OCS2D.TA_OCS2D_2020_SCOT
ADD CONSTRAINT TA_OCS2D_2020_SCOT_PK
PRIMARY KEY("IDENTIFIANT")
USING INDEX TABLESPACE "G_ADT_INDX";


-- Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_OCS2D_2020_SCOT',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;


-- Création de l'index spatial sur le champ geom
CREATE INDEX TA_OCS2D_2020_SCOT_SIDX
ON G_OCS2D.TA_OCS2D_2020_SCOT(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- Création des index sur les clés étrangères et autres

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CS_NIVEAU_1_CS_NIVEAU_2_CS_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CS_NIVEAU_1","CS_NIVEAU_2","CS_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CS"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_LIBCS"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("LIBCS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_US_NIVEAU_1_US_NIVEAU_2_US_NIVEAU_3"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("US_NIVEAU_1","US_NIVEAU_2","US_NIVEAU_3") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_US"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_LIBUS"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("LIBUS") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CS_US"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CS","US") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_US_CS"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("US","CS") 
TABLESPACE G_ADT_INDX;
CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CODE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CODE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CODE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CODE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CODE_4_POSTES_LIBELLE_4_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CODE_4_POSTES","LIBELLE_4_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_CODE_21_POSTES_LIBELLE_21_POSTES"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("CODE_21_POSTES","LIBELLE_21_POSTES") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_INDICE"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("INDICE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_SOURCE"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("SOURCE_DONNEE") 
TABLESPACE G_ADT_INDX;

CREATE INDEX "G_OCS2D"."TA_OCS2D_2020_SCOT_COMMENT"
ON "G_OCS2D"."TA_OCS2D_2020_SCOT" ("COMMENTAIRE") 
TABLESPACE G_ADT_INDX;


COMMENT ON TABLE G_OCS2D.TA_OCS2D_2020_SCOT IS 'La table TA_OCS2D_2020_SCOT présente les données OCS2D à l''échelle du SCOT en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.IDENTIFIANT IS 'Clé primaire de la vue materialisee.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.CS_NIVEAU_1 IS 'Code caractérisant le type de couvert du sol au niveau 1 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBCS_NIVEAU_1 IS 'Libelle caractérisant le type de couvert du sol au niveau 1 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.CS_NIVEAU_2 IS 'Code caractérisant le type de couvert du sol au niveau 2 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBCS_NIVEAU_2 IS 'Libelle caractérisant le type de couvert du sol au niveau 2 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.CS_NIVEAU_3 IS 'Code caractérisant le type de couvert du sol au niveau 3 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBCS IS 'Libelle caractérisant le type de couvert du sol au niveau 3 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.CS IS 'Code caractérisant le type de couvert du sol complet en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.US_NIVEAU_1 IS 'Code caractérisant l''usage du sol au niveau 1 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBUS_NIVEAU_1 IS 'Libelle caractérisant l''usage du sol au niveau 1 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.US_NIVEAU_2 IS 'Code caractérisant l''usage du sol au niveau 2 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBUS_NIVEAU_2 IS 'Libelle caractérisant l''usage du sol au niveau 2 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.US_NIVEAU_3 IS 'Code caractérisant l''usage du sol au niveau 3 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.LIBUS IS 'Libelle caractérisant l''usage du sol au niveau 3 en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.US IS 'Code caractérisant l''usage du sol complet en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT."CODE_4_POSTES" IS 'Poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT."LIBELLE_4_POSTES" IS 'Libelle du poste de la nomenclature 4 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT."CODE_21_POSTES" IS 'Poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT."LIBELLE_21_POSTES" IS 'Libelle du poste de la nomenclature 21 postes à laquelle appartient la combinisaison CS/US du polygone en 2020';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.INDICE IS 'Indice de la qualite de la photo-interpretation de la zone OCS2D en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.SOURCE_DONNEE IS 'Données sources utilisées pour la production de la donnée OCS2D en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT."COMMENTAIRE" IS 'Commentaire sur le polygone OCS2D en 2020.';
COMMENT ON COLUMN G_OCS2D.TA_OCS2D_2020_SCOT.EVOL15_20 IS 'Code qui caractérise une evolution en les millesime 2015 et 2020. 1 pas d''évolution des codes, 2 évolutions.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2020_SCOT"."PERIMETRE" IS 'Perimetre du polygone';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2020_SCOT"."SURFACE_M2" IS 'Surface du polygone en metre carre';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2020_SCOT"."SURFACE_HA" IS 'Surface du polygone en hectare';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2020_SCOT"."METADONNEE" IS 'Information sur la couche.';
COMMENT ON COLUMN "G_OCS2D"."TA_OCS2D_2020_SCOT"."GEOM" IS 'Géométrie de chaque polygone - de type polygone.';


-- Affection des droits
GRANT SELECT ON G_OCS2D.TA_OCS2D_2020_SCOT TO G_ADMIN_SIG;
GRANT SELECT ON G_OCS2D.TA_OCS2D_2020_SCOT TO G_OCS2D_R;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_OCS2D.TA_OCS2D_2020_SCOT TO G_OCS2D_RW;