-- Creation de la structure pour les données OCS2D


-- 1. Création de la table TA_OCS2D_INDICE
-- 1.1. Table TA_OCS2D_INDICE pour acceuillir les indices que peuvent avoir les surfaces OCS2D
CREATE TABLE TA_OCS2D_INDICE(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
	valeur VARCHAR2(255)
);

-- 1.2. Création des commentaires
COMMENT ON TABLE TA_OCS2D_INDICE IS 'Table contenant les indices que peuvent avoir les surfaces OCS2D';
COMMENT ON COLUMN ta_ocs2d_indice.objectid IS 'Clé primaire de la table';
COMMENT ON COLUMN ta_ocs2d_indice.valeur IS 'Valeur de l''indice';

-- 1.3. Création de la clé primaire
ALTER TABLE 
	ta_ocs2d_indice
	ADD CONSTRAINT ta_ocs2d_indice_PK 
	PRIMARY KEY("OBJECTID")
	USING INDEX TABLESPACE "G_ADT_INDX";


-- 2. Création de la table TA_OCS2D_SOURCE
-- 2.1. Table TA_OCS2D_SOURCE pour acceuillir les sources que peuvent avoir les surfaces OCS2D
CREATE TABLE TA_OCS2D_SOURCE(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
	valeur VARCHAR2(255)
);

-- 2.2. Création des commentaires
COMMENT ON TABLE TA_OCS2D_SOURCE IS 'Table contenant les sources que peuvent avoir les surfaces OCS2D';
COMMENT ON COLUMN ta_ocs2d_source.objectid IS 'Clé primaire de la table';
COMMENT ON COLUMN ta_ocs2d_source.valeur IS 'Valeur de la source';

-- 2.3. Création de la clé primaire
ALTER TABLE 
	ta_ocs2d_source
	ADD CONSTRAINT ta_ocs2d_source_PK 
	PRIMARY KEY("OBJECTID")
	USING INDEX TABLESPACE "G_ADT_INDX";


-- 3. Création de la table TA_OCS2D_COMMENTAIRE
-- 3.1. Table TA_OCS2D_COMMENTAIRE pour acceuillir les commentaires que peuvent avoir les surfaces OCS2D
CREATE TABLE TA_OCS2D_COMMENTAIRE(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
	valeur VARCHAR2(255)
);

-- 3.2. Création des commentaires
COMMENT ON TABLE TA_OCS2D_COMMENTAIRE IS 'Table contenant les commentaires que peuvent avoir les surfaces OCS2D';
COMMENT ON COLUMN ta_ocs2d_commentaire.objectid IS 'Clé primaire de la table';
COMMENT ON COLUMN ta_ocs2d_commentaire.valeur IS 'Valeur de la source';

-- 3.3. Création de la clé primaire
ALTER TABLE 
	ta_ocs2d_commentaire
	ADD CONSTRAINT ta_ocs2d_commentaire_PK 
	PRIMARY KEY("OBJECTID")
	USING INDEX TABLESPACE "G_ADT_INDX";


-- 4. Création de la table TA_OCS2D_GEOM
-- 4.1. La table TA_OCSD_GEOM sert à acceuillir la géométrie des polygones OCS2D.
CREATE TABLE TA_OCS2D_GEOM(
	objectid NUMBER(38,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
	geom SDO_GEOMETRY
	);

-- 4.2. Création des commentaires des colonnes
COMMENT ON TABLE TA_OCS2D_GEOM IS 'Table regroupant les zones IRIS';
COMMENT ON COLUMN TA_OCS2D_GEOM.objectid IS 'Clé primaire de la table TA_OCS2D_GEOM.';
COMMENT ON COLUMN TA_OCS2D_GEOM.geom IS 'Géométrie des zones OCS2D.';

-- 4.3. Création de la clé primaire
ALTER TABLE 
	TA_OCS2D_GEOM
	ADD CONSTRAINT TA_OCS2D_GEOM_PK 
	PRIMARY KEY("OBJECTID")
	USING INDEX TABLESPACE "G_ADT_INDX";

-- 4.4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'ta_ocs2d_geom',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);

-- 4.5. Création de l'index spatial sur le champ geom
CREATE INDEX ta_ocs2d_geom_SIDX
ON ta_ocs2d_geom(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');


-- 5. Création de la table TA_OCS2D
-- 5.1. La table TA_OCS2D sert à acceuillir les informations provenant des données OCS2D
CREATE TABLE TA_OCS2D(
	objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
	fid_lib_cs NUMBER(38,0),
	fid_lib_us NUMBER(38,0),
	fid_ocs2d_indice NUMBER(38,0),
	fid_ocs2d_source NUMBER(38,0),
	fid_metadonnee NUMBER(38,0),
	fid_geom NUMBER(38,0)
);

-- 5.2. Création des commentaires
COMMENT ON TABLE TA_OCS2D IS 'Table contenant les informations provenant des données OCS2D';
COMMENT ON COLUMN ta_ocs2d.objectid IS 'Clé primaire de la table TA_OCS2D';
COMMENT ON COLUMN ta_ocs2d.fid_lib_cs IS 'Clé étrangère vers la table TA_LIBELLE';
COMMENT ON COLUMN ta_ocs2d.fid_lib_us IS 'Clé étrangère vers la table TA_LIBELLE';
COMMENT ON COLUMN ta_ocs2d.fid_ocs2d_indice IS 'Clé étrangère vers la table TA_OCS2D_INDICE';
COMMENT ON COLUMN ta_ocs2d.fid_ocs2d_source IS 'Clé étrangère vers la table TA_OCS2D_SOURCE';
COMMENT ON COLUMN ta_ocs2d.fid_metadonnee IS 'Clé étrangère vers la table TA_METADONNEE';
COMMENT ON COLUMN ta_ocs2d.fid_geom IS 'Clé étrangère vers la table TA_OCS2D_GEOM';

-- 5.3. Création de la clé primaire
ALTER TABLE 
	ta_ocs2d
	ADD CONSTRAINT ta_ocs2d_PK 
	PRIMARY KEY("OBJECTID")
	USING INDEX
	TABLESPACE "G_ADT_INDX";

-- 5.4. Création des clé étrangère

-- 5.4.1. vers la table ta_libelle pour les occupations du sol
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "TA_LIBELLE_COUVERT_OBJECTID" 
	FOREIGN KEY ("FID_LIB_CS")
	REFERENCES "TA_LIBELLE"("OBJECTID");

-- 5.4.2. vers la table ta_libelle pour les utilisations du sol
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "TA_LIBELLE_USAGE_OBJECTID"
	FOREIGN KEY ("FID_LIB_US")
	REFERENCES "TA_LIBELLE"("OBJECTID");

-- 5.4.3. vers la table ta_ocs2d_indice pour les indices
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "TA_OCS2D_INDICE_OBJECTID_FK" 
	FOREIGN KEY ("FID_OCS2D_INDICE")
	REFERENCES "TA_OCS2D_INDICE"("OBJECTID");

-- 5.4.4. vers la table ta_ocs2d_source pour les sources OCS2D
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "FID_OCS2D_SOURCE_OBJECTID_FK" 
	FOREIGN KEY ("FID_OCS2D_SOURCE")
	REFERENCES "TA_OCS2D_SOURCE"("OBJECTID");

-- 5.4.5. vers la table ta_metadonnee pour les commentaires OCS2D
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "TA_METADONNEE_OBJECTID_FK" 
	FOREIGN KEY ("FID_METADONNEE")
	REFERENCES "TA_METADONNEE"("OBJECTID");

-- 5.4.6. vers la table ta_ocs2d_geom pour les commentaires OCS2D
ALTER TABLE ta_ocs2d
	ADD CONSTRAINT "TA_OCS2D_GEOM_OBJECTID_FK" 
	FOREIGN KEY ("FID_GEOM")
	REFERENCES "TA_OCS2D_GEOM"("OBJECTID");


-- 6. Création de la table TA_OCS2D_RELATION_COMMENTAIRE
-- 6.1. La table TA_OCS2D_RELATION_COMMENTAIRE est une table qui relie les zones OCS2D avec les commentaires qu'elles peuvent avoir.
CREATE TABLE TA_OCS2D_RELATION_COMMENTAIRE(
	fid_ocs2d NUMBER(38,0),
	fid_ocs2d_commentaire NUMBER(38,0)
);

-- 6.2. Création des commentaires
COMMENT ON TABLE TA_OCS2D_RELATION_COMMENTAIRE IS 'Table contenant les commentaires que peuvent avoir les surfaces OCS2D';
COMMENT ON COLUMN ta_ocs2d_relation_commentaire.fid_ocs2d IS 'Clé étrangère vers la table TA_OCS2D.';
COMMENT ON COLUMN ta_ocs2d_relation_commentaire.fid_ocs2d_commentaire IS 'Clé étrangère vers la table TA_OCS2D_COMMENTAIRE pour connaitre le commentaire de la zone OCS2D concernée.';

-- 6.3. Création de la clé primaire
ALTER TABLE 
	ta_ocs2d_relation_commentaire
	ADD CONSTRAINT ta_ocs2d_relation_commentaire_PK 
	PRIMARY KEY(fid_ocs2d,fid_ocs2d_commentaire)
	USING INDEX TABLESPACE "G_ADT_INDX";

-- 6.4. Création des clé étrangère
-- 6.4.1. vers la table ta_metadonnee pour les commentaires OCS2D
ALTER TABLE ta_ocs2d_relation_commentaire
	ADD CONSTRAINT "TA_OCS2D_OBJECTID_FK"
	FOREIGN KEY ("FID_OCS2D")
	REFERENCES "TA_OCS2D"("OBJECTID");

-- 6.4.2. vers la table ta_ocs2d_geom pour les commentaires OCS2D
ALTER TABLE ta_ocs2d_relation_commentaire
	ADD CONSTRAINT "TA_OCS2D_COMMENTAIRE_OBJECTID_FK" 
	FOREIGN KEY ("FID_OCS2D_COMMENTAIRE")
	REFERENCES "TA_OCS2D_COMMENTAIRE"("OBJECTID");
