/*
SEQ_TA_RTGE_POINT_INTEGRATION_LOG : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_RTGE_POINT_INTEGRATION_LOG
*/

CREATE SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_LOG_OBJECTID START WITH 1 INCREMENT BY 1 NOCACHE;

/
