/*
SEQ_TA_RTGE_POINT_INTEGRATION_LOG : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_RTGE_POINT_INTEGRATION_LOG
*/

CREATE SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_LOG START WITH 1 INCREMENT BY 1;

/
