/*
SEQ_TA_IC_LINEAIRE_LOG_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table SEQ_TA_IC_LINEAIRE_LOG_OBJECTID
*/

CREATE SEQUENCE SEQ_TA_IC_LINEAIRE_LOG_OBJECTID START WITH 1 INCREMENT BY 1 NOCACHE;


/
