-- suppression_seq_initialisation

-- Suppression de la sequence SEQ_TA_OCSMEL_LINEAIRE_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_OCSMEL_LINEAIRE_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_POINT_INTEGRATION_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_POINT_PRODUCTION_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_POINT_PRODUCTION_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_SURFACE_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_SURFACE_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_POINT_INTEGRATION_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_POINT_INTEGRATION_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_POINT_PRODUCTION_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_POINT_PRODUCTION_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_LINEAIRE_PRODUCTION_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_PRODUCTION_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_LINEAIRE_INTEGRATION_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_INTEGRATION_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_LINEAIRE_INTEGRATION_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_INTEGRATION_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_LINEAIRE_SOMMET_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_SOMMET_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_LINEAIRE_PRODUCTION_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_LINEAIRE_PRODUCTION_OBJECTID;

-- Suppression de la sequence SEQ_TA_PTTOPO_INTEGRATION_OBJECTID
DROP SEQUENCE SEQ_TA_PTTOPO_INTEGRATION_OBJECTID;

-- Suppression de la sequence SEQ_TA_OCSMEL_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_OCSMEL_LOG_OBJECTID;

-- Suppression de la sequence SEQ_TA_RTGE_ALTI_OBJECTID
DROP SEQUENCE SEQ_TA_RTGE_ALTI_OBJECTID;

-- Suppression de la sequence SEQ_TA_OCSMEL_LINEAIRE_OBJECTID
DROP SEQUENCE SEQ_TA_OCSMEL_LINEAIRE_OBJECTID;

-- Suppression de la sequence SEQ_TA_OCSMEL_OBJECTID
DROP SEQUENCE SEQ_TA_OCSMEL_OBJECTID;

-- Suppression de la sequence SEQ_TA_IC_LINEAIRE_OBJECTID
DROP SEQUENCE SEQ_TA_IC_LINEAIRE_OBJECTID;

-- Suppression de la sequence SEQ_TA_IC_LINEAIRE_LOG_OBJECTID
DROP SEQUENCE SEQ_TA_IC_LINEAIRE_LOG_OBJECTID;

/
